@startuml
package "Netbeans v1.0.x" as Netbeans_v1.0.x {
	package org {
		package netbeans {
			package modules {
				package vcs {
					package advanced {
						class CommandLineVcsFileSystem {
							-CONFIG_ROOT: Netbeans_v1.0.x.java.lang.String
							-CONFIG_ROOT_FO: Netbeans_v1.0.x.org.openide.filesystems.FileObject
							-D: Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug
							-commandsByName: Netbeans_v1.0.x.java.util.Hashtable
							{const} serialVersionUID: JavaPrimitiveTypes.long = -1017235664394970926
							<<Create>> CommandLineVcsFileSystem()
							getConfigRoot(): Netbeans_v1.0.x.java.lang.String
							getConfigRootFO(): Netbeans_v1.0.x.org.openide.filesystems.FileObject
							getVcsFactory(): Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsFactory
							propertyChange(evt : Netbeans_v1.0.x.java.beans.PropertyChangeEvent)
							#readConfiguration()
							setConfigRoot(s : Netbeans_v1.0.x.java.lang.String)
						}
						class CommandLineVcsFactory {
							<<Create>> CommandLineVcsFactory()
							getVcsAction(fs : Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsFileSystem): Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsAction
							getVcsAdvancedCustomizer(): Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsAdvancedCustomizer
							getVcsDirReader(listener : Netbeans_v1.0.x.org.netbeans.modules.vcs.DirReaderListener, path : Netbeans_v1.0.x.java.lang.String, fileSystem : Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsFileSystem): Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsDirReader
							getVcsDirReaderRecursive(listener : Netbeans_v1.0.x.org.netbeans.modules.vcs.DirReaderListener, path : Netbeans_v1.0.x.java.lang.String, fileSystem : Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsFileSystem): Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsDirReader
						}
						class CommandLineAction {
							-D: Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug
							-E: Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug
							-additionalVars: Netbeans_v1.0.x.java.util.Hashtable
							{const} serialVersionUID: JavaPrimitiveTypes.long = -2475922263910649869
							<<Create>> CommandLineAction(fileSystem : CommandLineVcsFileSystem)
							actionPerformed(e : Netbeans_v1.0.x.java.awt.event.ActionEvent)
							#createItem(name : Netbeans_v1.0.x.java.lang.String): Netbeans_v1.0.x.javax.swing.JMenuItem
							doAdditionalCommand(name : Netbeans_v1.0.x.java.lang.String, files : Netbeans_v1.0.x.java.util.Vector)
							#doCommand(files : Netbeans_v1.0.x.java.util.Vector, cmd : Netbeans_v1.0.x.org.netbeans.modules.vcs.cmdline.UserCommand)
							doDetails(files : Netbeans_v1.0.x.java.util.Vector)
							doEdit(files : Netbeans_v1.0.x.java.util.Vector)
							doList(path : Netbeans_v1.0.x.java.lang.String)
							doLock(files : Netbeans_v1.0.x.java.util.Vector)
							doUnlock(files : Netbeans_v1.0.x.java.util.Vector)
							enable(nodes : Netbeans_v1.0.x.org.openide.nodes.Node): JavaPrimitiveTypes.boolean
							g(s : Netbeans_v1.0.x.java.lang.String): Netbeans_v1.0.x.java.lang.String
							g(s : Netbeans_v1.0.x.java.lang.String, obj : Netbeans_v1.0.x.java.lang.Object): Netbeans_v1.0.x.java.lang.String
							g(s : Netbeans_v1.0.x.java.lang.String, obj1 : Netbeans_v1.0.x.java.lang.Object, obj2 : Netbeans_v1.0.x.java.lang.Object): Netbeans_v1.0.x.java.lang.String
							g(s : Netbeans_v1.0.x.java.lang.String, obj1 : Netbeans_v1.0.x.java.lang.Object, obj2 : Netbeans_v1.0.x.java.lang.Object, obj3 : Netbeans_v1.0.x.java.lang.Object): Netbeans_v1.0.x.java.lang.String
							getFileSystem(): CommandLineVcsFileSystem
							getHelpCtx(): Netbeans_v1.0.x.org.openide.util.HelpCtx
							getName(): Netbeans_v1.0.x.java.lang.String
							getPopupPresenter(): Netbeans_v1.0.x.javax.swing.JMenuItem
							parseFromCache(cacheRecord : Netbeans_v1.0.x.java.lang.String): Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsFile
							performAction(nodes : Netbeans_v1.0.x.org.openide.nodes.Node)
						}
						class CommandLineVcsAdvancedCustomizer {
							<<Create>> CommandLineVcsAdvancedCustomizer()
							getEditor(fileSystem : Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsFileSystem): Netbeans_v1.0.x.java.beans.PropertyEditor
							getPanel(pe : Netbeans_v1.0.x.java.beans.PropertyEditor): Netbeans_v1.0.x.javax.swing.JPanel
							readConfig(props : Netbeans_v1.0.x.java.util.Properties): Netbeans_v1.0.x.java.lang.Object
							writeConfig(props : Netbeans_v1.0.x.java.util.Properties, config : Netbeans_v1.0.x.java.lang.Object)
						}
						Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsFileSystem <|-- CommandLineVcsFileSystem
						Netbeans_v1.0.x.java.beans.PropertyChangeListener <|.. CommandLineVcsFileSystem
						Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsFactory <|.. CommandLineVcsFactory
						Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsAction <|-- CommandLineAction
						Netbeans_v1.0.x.java.awt.event.ActionListener <|.. CommandLineAction
						Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsAdvancedCustomizer <|.. CommandLineVcsAdvancedCustomizer
						Netbeans_v1.0.x.java.lang.String "CONFIG_ROOT" <-- CommandLineVcsFileSystem
						Netbeans_v1.0.x.org.openide.filesystems.FileObject "CONFIG_ROOT_FO" <-- CommandLineVcsFileSystem
						Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug "D" <-- CommandLineVcsFileSystem
						Netbeans_v1.0.x.java.util.Hashtable "commandsByName" <-- CommandLineVcsFileSystem
						JavaPrimitiveTypes.long "serialVersionUID" <-- CommandLineVcsFileSystem
						Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug "D" <-- CommandLineAction
						Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug "E" <-- CommandLineAction
						Netbeans_v1.0.x.java.util.Hashtable "additionalVars" <-- CommandLineAction
						JavaPrimitiveTypes.long "serialVersionUID" <-- CommandLineAction
					}
					package cmdline {
						class CvsFileSystem {
							-{const} CVS_DIRCONTENT: Netbeans_v1.0.x.java.lang.String [*]
							-{const} CVS_DIRNAME: Netbeans_v1.0.x.java.lang.String = CVS
							{const} CVS_SERVER_LOCAL: Netbeans_v1.0.x.java.lang.String = local
							{const} CVS_SERVER_PSERVER: Netbeans_v1.0.x.java.lang.String = pserver
							{const} CVS_SERVER_SERVER: Netbeans_v1.0.x.java.lang.String = server
							-D: Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug
							{const} PS_LOCAL: Netbeans_v1.0.x.java.lang.String
							{const} PS_SERVER: Netbeans_v1.0.x.java.lang.String = /
							-cvsExePath: Netbeans_v1.0.x.java.lang.String
							-cvsModule: Netbeans_v1.0.x.java.lang.String
							-cvsModuleName: Netbeans_v1.0.x.java.lang.String
							-cvsPassword: Netbeans_v1.0.x.java.lang.String
							-cvsRoot: Netbeans_v1.0.x.java.lang.String
							-cvsServer: Netbeans_v1.0.x.java.lang.String
							-cvsServerType: Netbeans_v1.0.x.java.lang.String
							-cvsUser: Netbeans_v1.0.x.java.lang.String
							-cygwinPath: Netbeans_v1.0.x.java.lang.String
							-{static} last_cvsExePath: Netbeans_v1.0.x.java.lang.String
							-{static} last_cvsModule: Netbeans_v1.0.x.java.lang.String
							-{static} last_cvsModuleName: Netbeans_v1.0.x.java.lang.String
							-{static} last_cvsPassword: Netbeans_v1.0.x.java.lang.String
							-{static} last_cvsRoot: Netbeans_v1.0.x.java.lang.String
							-{static} last_cvsServer: Netbeans_v1.0.x.java.lang.String
							-{static} last_cvsServerType: Netbeans_v1.0.x.java.lang.String
							-{static} last_cvsUser: Netbeans_v1.0.x.java.lang.String
							-{static} last_cygwinPath: Netbeans_v1.0.x.java.lang.String
							-needToCheckoutInvoked: JavaPrimitiveTypes.boolean
							{const} serialVersionUID: JavaPrimitiveTypes.long = 3105697696081480308
							<<Create>> CvsFileSystem()
							children(name : Netbeans_v1.0.x.java.lang.String): Netbeans_v1.0.x.java.lang.String
							#g(s : Netbeans_v1.0.x.java.lang.String): Netbeans_v1.0.x.java.lang.String
							getCvcRootForServerType(): Netbeans_v1.0.x.java.lang.String
							getCvsExePath(): Netbeans_v1.0.x.java.lang.String
							getCvsModule(): Netbeans_v1.0.x.java.lang.String
							getCvsModuleName(): Netbeans_v1.0.x.java.lang.String
							getCvsPassword(): Netbeans_v1.0.x.java.lang.String
							getCvsRoot(): Netbeans_v1.0.x.java.lang.String
							getCvsServer(): Netbeans_v1.0.x.java.lang.String
							getCvsServerType(): Netbeans_v1.0.x.java.lang.String
							getCvsUserName(): Netbeans_v1.0.x.java.lang.String
							getCygwinPath(): Netbeans_v1.0.x.java.lang.String
							getLocalFileFilter(): Netbeans_v1.0.x.java.io.FilenameFilter
							getVariablesByName(): Netbeans_v1.0.x.java.util.Hashtable
							getVcsFactory(): Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsFactory
							-initCommands()
							-isCVSDirectory(dir : Netbeans_v1.0.x.java.io.File): JavaPrimitiveTypes.boolean
							-isCVSRoot(dir : Netbeans_v1.0.x.java.io.File): JavaPrimitiveTypes.boolean
							propertyChange(evt : Netbeans_v1.0.x.java.beans.PropertyChangeEvent)
							-readObject(in : Netbeans_v1.0.x.java.io.ObjectInputStream)
							-setConfiguration()
							setCvsExePath(exePath : Netbeans_v1.0.x.java.lang.String)
							setCvsModule(module : Netbeans_v1.0.x.java.lang.String)
							setCvsModuleName(moduleName : Netbeans_v1.0.x.java.lang.String)
							setCvsPassword(password : Netbeans_v1.0.x.java.lang.String)
							setCvsRoot(root : Netbeans_v1.0.x.java.lang.String)
							setCvsServer(server : Netbeans_v1.0.x.java.lang.String)
							#setCvsServerType(serverType : Netbeans_v1.0.x.java.lang.String)
							setCvsUserName(user : Netbeans_v1.0.x.java.lang.String)
							setCygwinPath(path : Netbeans_v1.0.x.java.lang.String)
							#setUseUnixShell(unixShell : JavaPrimitiveTypes.boolean)
							-writeObject(out : Netbeans_v1.0.x.java.io.ObjectOutputStream)
						}
						class CvsFactory {
							<<Create>> CvsFactory()
							getVcsAction(fs : Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsFileSystem): Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsAction
							getVcsAdvancedCustomizer(): Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsAdvancedCustomizer
							getVcsDirReader(listener : Netbeans_v1.0.x.org.netbeans.modules.vcs.DirReaderListener, path : Netbeans_v1.0.x.java.lang.String, fileSystem : Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsFileSystem): Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsDirReader
							getVcsDirReaderRecursive(listener : Netbeans_v1.0.x.org.netbeans.modules.vcs.DirReaderListener, path : Netbeans_v1.0.x.java.lang.String, fileSystem : Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsFileSystem): Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsDirReader
						}
						class CommandLineVcsDirReader {
							-D: Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug
							-E: Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug
							-dir: Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsDir
							-fileSystem: Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsFileSystem
							-list: UserCommand
							-listener: Netbeans_v1.0.x.org.netbeans.modules.vcs.DirReaderListener
							-rawData: Netbeans_v1.0.x.java.util.Vector
							-shouldFail: JavaPrimitiveTypes.boolean
							-vars: Netbeans_v1.0.x.java.util.Hashtable
							<<Create>> CommandLineVcsDirReader(listener : Netbeans_v1.0.x.org.netbeans.modules.vcs.DirReaderListener, fileSystem : Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsFileSystem, list : UserCommand, vars : Netbeans_v1.0.x.java.util.Hashtable)
							g(s : Netbeans_v1.0.x.java.lang.String): Netbeans_v1.0.x.java.lang.String
							g(s : Netbeans_v1.0.x.java.lang.String, obj : Netbeans_v1.0.x.java.lang.Object): Netbeans_v1.0.x.java.lang.String
							g(s : Netbeans_v1.0.x.java.lang.String, obj1 : Netbeans_v1.0.x.java.lang.Object, obj2 : Netbeans_v1.0.x.java.lang.Object): Netbeans_v1.0.x.java.lang.String
							g(s : Netbeans_v1.0.x.java.lang.String, obj1 : Netbeans_v1.0.x.java.lang.Object, obj2 : Netbeans_v1.0.x.java.lang.Object, obj3 : Netbeans_v1.0.x.java.lang.Object): Netbeans_v1.0.x.java.lang.String
							getRawData(): Netbeans_v1.0.x.java.util.Vector
							{static} matchToFile(elements : Netbeans_v1.0.x.java.lang.String, list : UserCommand): Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsFile
							run()
							-runClass(className : Netbeans_v1.0.x.java.lang.String, tokens : Netbeans_v1.0.x.java.util.StringTokenizer, container : OutputContainer)
							-runCommand(exec : Netbeans_v1.0.x.java.lang.String, container : OutputContainer)
						}
						class CommandLineVcsDirReaderRecursive {
							-D: Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug
							-E: Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug
							-dir: Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsDir
							-fileSystem: Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsFileSystem
							-listSub: UserCommand
							-listener: Netbeans_v1.0.x.org.netbeans.modules.vcs.DirReaderListener
							-path: Netbeans_v1.0.x.java.lang.String
							-rawData: Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsDirContainer
							-shouldFail: JavaPrimitiveTypes.boolean
							-vars: Netbeans_v1.0.x.java.util.Hashtable
							<<Create>> CommandLineVcsDirReaderRecursive(listener : Netbeans_v1.0.x.org.netbeans.modules.vcs.DirReaderListener, fileSystem : Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsFileSystem, listSub : UserCommand, vars : Netbeans_v1.0.x.java.util.Hashtable)
							g(s : Netbeans_v1.0.x.java.lang.String): Netbeans_v1.0.x.java.lang.String
							g(s : Netbeans_v1.0.x.java.lang.String, obj : Netbeans_v1.0.x.java.lang.Object): Netbeans_v1.0.x.java.lang.String
							g(s : Netbeans_v1.0.x.java.lang.String, obj1 : Netbeans_v1.0.x.java.lang.Object, obj2 : Netbeans_v1.0.x.java.lang.Object): Netbeans_v1.0.x.java.lang.String
							g(s : Netbeans_v1.0.x.java.lang.String, obj1 : Netbeans_v1.0.x.java.lang.Object, obj2 : Netbeans_v1.0.x.java.lang.Object, obj3 : Netbeans_v1.0.x.java.lang.Object): Netbeans_v1.0.x.java.lang.String
							-putFilesToDir(dir : Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsDir, filesByName : Netbeans_v1.0.x.java.util.Hashtable, rawData : Netbeans_v1.0.x.java.util.Vector)
							-putFilesToDirRecursively(dir : Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsDir, filesByName : Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsDirContainer, rawData : Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsDirContainer)
							run()
							runClass(className : Netbeans_v1.0.x.java.lang.String, tokens : Netbeans_v1.0.x.java.util.StringTokenizer, container : OutputContainer)
							runCommand(exec : Netbeans_v1.0.x.java.lang.String, container : OutputContainer)
						}
						class CvsAction {
							-D: Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug
							-E: Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug
							-additionalVars: Netbeans_v1.0.x.java.util.Hashtable
							-concurrentExecution: JavaPrimitiveTypes.boolean
							{const} serialVersionUID: JavaPrimitiveTypes.long = -6595569895749032164
							<<Create>> CvsAction(fileSystem : CvsFileSystem)
							actionPerformed(e : Netbeans_v1.0.x.java.awt.event.ActionEvent)
							-assignHelp(item : Netbeans_v1.0.x.javax.swing.JMenuItem, commandName : Netbeans_v1.0.x.java.lang.String)
							-createItem(name : Netbeans_v1.0.x.java.lang.String): Netbeans_v1.0.x.javax.swing.JMenuItem
							doAdditionalCommand(name : Netbeans_v1.0.x.java.lang.String, files : Netbeans_v1.0.x.java.util.Vector)
							#doCommand(files : Netbeans_v1.0.x.java.util.Vector, cmd : UserCommand)
							doDetails(files : Netbeans_v1.0.x.java.util.Vector)
							doEdit(files : Netbeans_v1.0.x.java.util.Vector)
							doLock(files : Netbeans_v1.0.x.java.util.Vector)
							doUnlock(files : Netbeans_v1.0.x.java.util.Vector)
							enable(nodes : Netbeans_v1.0.x.org.openide.nodes.Node): JavaPrimitiveTypes.boolean
							g(s : Netbeans_v1.0.x.java.lang.String): Netbeans_v1.0.x.java.lang.String
							g(s : Netbeans_v1.0.x.java.lang.String, obj : Netbeans_v1.0.x.java.lang.Object): Netbeans_v1.0.x.java.lang.String
							g(s : Netbeans_v1.0.x.java.lang.String, obj1 : Netbeans_v1.0.x.java.lang.Object, obj2 : Netbeans_v1.0.x.java.lang.Object): Netbeans_v1.0.x.java.lang.String
							g(s : Netbeans_v1.0.x.java.lang.String, obj1 : Netbeans_v1.0.x.java.lang.Object, obj2 : Netbeans_v1.0.x.java.lang.Object, obj3 : Netbeans_v1.0.x.java.lang.Object): Netbeans_v1.0.x.java.lang.String
							getHelpCtx(): Netbeans_v1.0.x.org.openide.util.HelpCtx
							getName(): Netbeans_v1.0.x.java.lang.String
							getPopupPresenter(): Netbeans_v1.0.x.javax.swing.JMenuItem
							parseFromCache(cacheRecord : Netbeans_v1.0.x.java.lang.String): Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsFile
							performAction(nodes : Netbeans_v1.0.x.org.openide.nodes.Node)
						}
						Netbeans_v1.0.x.java.io.Serializable <|.. UserCommand
						Netbeans_v1.0.x.java.lang.Cloneable <|.. UserCommand
						Netbeans_v1.0.x.javax.swing.JDialog <|-- ErrorCommandDialog
						Netbeans_v1.0.x.org.netbeans.modules.vcs.cmdline.exec.NoRegexListener <|.. OutputContainer
						Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsFileSystem <|-- CvsFileSystem
						Netbeans_v1.0.x.java.beans.PropertyChangeListener <|.. CvsFileSystem
						Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsFactory <|.. CvsFactory
						Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsDirReader <|.. CommandLineVcsDirReader
						Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsDirReader <|.. CommandLineVcsDirReaderRecursive
						Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsAction <|-- CvsAction
						Netbeans_v1.0.x.java.awt.event.ActionListener <|.. CvsAction
						Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug "D" <-- UserCommand
						Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug "E" <-- UserCommand
						JavaPrimitiveTypes.int "attrIndex" <-- UserCommand
						Netbeans_v1.0.x.java.lang.String "confirmationMsg" <-- UserCommand
						Netbeans_v1.0.x.java.lang.String "dataRegex" <-- UserCommand
						JavaPrimitiveTypes.int "dateIndex" <-- UserCommand
						JavaPrimitiveTypes.boolean "displayOutput" <-- UserCommand
						JavaPrimitiveTypes.boolean "doRefresh" <-- UserCommand
						Netbeans_v1.0.x.java.lang.String "errorRegex" <-- UserCommand
						Netbeans_v1.0.x.java.lang.String "exec" <-- UserCommand
						JavaPrimitiveTypes.int "fileNameIndex" <-- UserCommand
						Netbeans_v1.0.x.java.lang.String "input" <-- UserCommand
						Netbeans_v1.0.x.java.lang.String "label" <-- UserCommand
						JavaPrimitiveTypes.int "lockerIndex" <-- UserCommand
						Netbeans_v1.0.x.java.lang.String "name" <-- UserCommand
						JavaPrimitiveTypes.boolean "onDir" <-- UserCommand
						JavaPrimitiveTypes.boolean "onFile" <-- UserCommand
						JavaPrimitiveTypes.boolean "onRoot" <-- UserCommand
						JavaPrimitiveTypes.int "order" <-- UserCommand
						JavaPrimitiveTypes.long "serialVersionUID" <-- UserCommand
						JavaPrimitiveTypes.int "sizeIndex" <-- UserCommand
						JavaPrimitiveTypes.int "statusIndex" <-- UserCommand
						JavaPrimitiveTypes.int "timeIndex" <-- UserCommand
						JavaPrimitiveTypes.long "timeout" <-- UserCommand
						Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug "D" <-- ErrorCommandDialog
						Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug "E" <-- ErrorCommandDialog
						Netbeans_v1.0.x.javax.swing.JButton "closeButton" <-- ErrorCommandDialog
						Netbeans_v1.0.x.javax.swing.JLabel "label" <-- ErrorCommandDialog
						Netbeans_v1.0.x.javax.swing.JScrollPane "listScrollPane" <-- ErrorCommandDialog
						Netbeans_v1.0.x.java.lang.String "separator" <-- ErrorCommandDialog
						JavaPrimitiveTypes.long "serialVersionUID" <-- ErrorCommandDialog
						Netbeans_v1.0.x.javax.swing.JTextArea "textArea" <-- ErrorCommandDialog
						UserCommand "uc" <-- ErrorCommandDialog
						Netbeans_v1.0.x.java.util.Vector "messages" <-- OutputContainer
						Netbeans_v1.0.x.java.lang.String "CVS_DIRCONTENT 0..*" <-- CvsFileSystem
						Netbeans_v1.0.x.java.lang.String "CVS_DIRNAME" <-- CvsFileSystem
						Netbeans_v1.0.x.java.lang.String "CVS_SERVER_LOCAL" <-- CvsFileSystem
						Netbeans_v1.0.x.java.lang.String "CVS_SERVER_PSERVER" <-- CvsFileSystem
						Netbeans_v1.0.x.java.lang.String "CVS_SERVER_SERVER" <-- CvsFileSystem
						Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug "D" <-- CvsFileSystem
						Netbeans_v1.0.x.java.lang.String "PS_LOCAL" <-- CvsFileSystem
						Netbeans_v1.0.x.java.lang.String "PS_SERVER" <-- CvsFileSystem
						Netbeans_v1.0.x.java.lang.String "cvsExePath" <-- CvsFileSystem
						Netbeans_v1.0.x.java.lang.String "cvsModule" <-- CvsFileSystem
						Netbeans_v1.0.x.java.lang.String "cvsModuleName" <-- CvsFileSystem
						Netbeans_v1.0.x.java.lang.String "cvsPassword" <-- CvsFileSystem
						Netbeans_v1.0.x.java.lang.String "cvsRoot" <-- CvsFileSystem
						Netbeans_v1.0.x.java.lang.String "cvsServer" <-- CvsFileSystem
						Netbeans_v1.0.x.java.lang.String "cvsServerType" <-- CvsFileSystem
						Netbeans_v1.0.x.java.lang.String "cvsUser" <-- CvsFileSystem
						Netbeans_v1.0.x.java.lang.String "cygwinPath" <-- CvsFileSystem
						Netbeans_v1.0.x.java.lang.String "last_cvsExePath" <-- CvsFileSystem
						Netbeans_v1.0.x.java.lang.String "last_cvsModule" <-- CvsFileSystem
						Netbeans_v1.0.x.java.lang.String "last_cvsModuleName" <-- CvsFileSystem
						Netbeans_v1.0.x.java.lang.String "last_cvsPassword" <-- CvsFileSystem
						Netbeans_v1.0.x.java.lang.String "last_cvsRoot" <-- CvsFileSystem
						Netbeans_v1.0.x.java.lang.String "last_cvsServer" <-- CvsFileSystem
						Netbeans_v1.0.x.java.lang.String "last_cvsServerType" <-- CvsFileSystem
						Netbeans_v1.0.x.java.lang.String "last_cvsUser" <-- CvsFileSystem
						Netbeans_v1.0.x.java.lang.String "last_cygwinPath" <-- CvsFileSystem
						JavaPrimitiveTypes.boolean "needToCheckoutInvoked" <-- CvsFileSystem
						JavaPrimitiveTypes.long "serialVersionUID" <-- CvsFileSystem
						Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug "D" <-- CommandLineVcsDirReader
						Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug "E" <-- CommandLineVcsDirReader
						Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsDir "dir" <-- CommandLineVcsDirReader
						Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsFileSystem "fileSystem" <-- CommandLineVcsDirReader
						UserCommand "list" <-- CommandLineVcsDirReader
						Netbeans_v1.0.x.org.netbeans.modules.vcs.DirReaderListener "listener" <-- CommandLineVcsDirReader
						Netbeans_v1.0.x.java.util.Vector "rawData" <-- CommandLineVcsDirReader
						JavaPrimitiveTypes.boolean "shouldFail" <-- CommandLineVcsDirReader
						Netbeans_v1.0.x.java.util.Hashtable "vars" <-- CommandLineVcsDirReader
						Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug "D" <-- CommandLineVcsDirReaderRecursive
						Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug "E" <-- CommandLineVcsDirReaderRecursive
						Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsDir "dir" <-- CommandLineVcsDirReaderRecursive
						Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsFileSystem "fileSystem" <-- CommandLineVcsDirReaderRecursive
						UserCommand "listSub" <-- CommandLineVcsDirReaderRecursive
						Netbeans_v1.0.x.org.netbeans.modules.vcs.DirReaderListener "listener" <-- CommandLineVcsDirReaderRecursive
						Netbeans_v1.0.x.java.lang.String "path" <-- CommandLineVcsDirReaderRecursive
						Netbeans_v1.0.x.org.netbeans.modules.vcs.VcsDirContainer "rawData" <-- CommandLineVcsDirReaderRecursive
						JavaPrimitiveTypes.boolean "shouldFail" <-- CommandLineVcsDirReaderRecursive
						Netbeans_v1.0.x.java.util.Hashtable "vars" <-- CommandLineVcsDirReaderRecursive
						Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug "D" <-- CvsAction
						Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug "E" <-- CvsAction
						Netbeans_v1.0.x.java.util.Hashtable "additionalVars" <-- CvsAction
						JavaPrimitiveTypes.boolean "concurrentExecution" <-- CvsAction
						JavaPrimitiveTypes.long "serialVersionUID" <-- CvsAction
					}
					abstract class VcsFileSystem {
						-{const} ASK_FOR: Netbeans_v1.0.x.java.lang.String = ASK_FOR
						-{static} CACHE_ROOT: Netbeans_v1.0.x.java.lang.String
						-D: Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug
						-E: Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug
						-{const} LOCAL_FILES_ADD_VAR: Netbeans_v1.0.x.java.lang.String = SHOWLOCALFILES
						-{const} LOCK_FILES_ON: Netbeans_v1.0.x.java.lang.String = LOCKFILES
						-{const} PROMPT_FOR: Netbeans_v1.0.x.java.lang.String = PROMPT_FOR
						-{const} PROMPT_FOR_LOCK_ON: Netbeans_v1.0.x.java.lang.String = PROMPTFORLOCK
						#{const} REFRESH_TIME: JavaPrimitiveTypes.int = 0
						-{const} VAR_FALSE: Netbeans_v1.0.x.java.lang.String = false
						-{const} VAR_TRUE: Netbeans_v1.0.x.java.lang.String = true
						-action: VcsAction
						-advanced: Netbeans_v1.0.x.java.lang.Object
						-askIfDownloadRecursively: JavaPrimitiveTypes.boolean
						#cache: VcsCache
						-cacheId: JavaPrimitiveTypes.long
						-commandsByName: Netbeans_v1.0.x.java.util.Hashtable
						-config: Netbeans_v1.0.x.java.lang.String
						-debug: JavaPrimitiveTypes.boolean
						-errorDialog: Netbeans_v1.0.x.org.netbeans.modules.vcs.cmdline.ErrorCommandDialog
						-lastCommandFinished: JavaPrimitiveTypes.boolean
						-lastCommandState: JavaPrimitiveTypes.boolean
						-{static} last_refreshTime: JavaPrimitiveTypes.int
						-{static} last_rootFile: Netbeans_v1.0.x.java.io.File
						-{static} last_useUnixShell: JavaPrimitiveTypes.boolean
						-lockFilesOn: JavaPrimitiveTypes.boolean
						-numDoAutoRefreshes: Netbeans_v1.0.x.java.util.Hashtable
						-password: Netbeans_v1.0.x.java.lang.String
						-promptForLockOn: JavaPrimitiveTypes.boolean
						-promptForLockResult: JavaPrimitiveTypes.boolean
						-promptForVarsForEachFile: JavaPrimitiveTypes.boolean
						-readOnly: JavaPrimitiveTypes.boolean
						#ready: JavaPrimitiveTypes.boolean
						#refreshTimeToSet: JavaPrimitiveTypes.int
						-rootFile: Netbeans_v1.0.x.java.io.File
						{const} serialVersionUID: JavaPrimitiveTypes.long = 8108342718973310275
						-unimportantNames: Netbeans_v1.0.x.java.util.Vector
						-useUnixShell: JavaPrimitiveTypes.boolean
						-variables: Netbeans_v1.0.x.java.util.Vector
						#variablesByName: Netbeans_v1.0.x.java.util.Hashtable
						<<Create>> VcsFileSystem()
						annotateIcon(icon : Netbeans_v1.0.x.java.awt.Image, iconType : JavaPrimitiveTypes.int, files : Netbeans_v1.0.x.java.util.Set): Netbeans_v1.0.x.java.awt.Image
						annotateName(name : Netbeans_v1.0.x.java.lang.String, files : Netbeans_v1.0.x.java.util.Set): Netbeans_v1.0.x.java.lang.String
						-checkLocalFolder(name : Netbeans_v1.0.x.java.lang.String)
						children(name : Netbeans_v1.0.x.java.lang.String): Netbeans_v1.0.x.java.lang.String
						#computeSystemName(rootFile : Netbeans_v1.0.x.java.io.File): Netbeans_v1.0.x.java.lang.String
						createData(name : Netbeans_v1.0.x.java.lang.String)
						-createDir(path : Netbeans_v1.0.x.java.lang.String)
						createFolder(name : Netbeans_v1.0.x.java.lang.String)
						#createNewCacheDir(): Netbeans_v1.0.x.java.lang.String
						debug(msg : Netbeans_v1.0.x.java.lang.String)
						debugClear()
						delete(name : Netbeans_v1.0.x.java.lang.String)
						folder(name : Netbeans_v1.0.x.java.lang.String): JavaPrimitiveTypes.boolean
						#g(s : Netbeans_v1.0.x.java.lang.String): Netbeans_v1.0.x.java.lang.String
						#g(s : Netbeans_v1.0.x.java.lang.String, obj : Netbeans_v1.0.x.java.lang.Object): Netbeans_v1.0.x.java.lang.String
						#g(s : Netbeans_v1.0.x.java.lang.String, obj1 : Netbeans_v1.0.x.java.lang.Object, obj2 : Netbeans_v1.0.x.java.lang.Object): Netbeans_v1.0.x.java.lang.String
						#g(s : Netbeans_v1.0.x.java.lang.String, obj1 : Netbeans_v1.0.x.java.lang.Object, obj2 : Netbeans_v1.0.x.java.lang.Object, obj3 : Netbeans_v1.0.x.java.lang.Object): Netbeans_v1.0.x.java.lang.String
						getActions(): Netbeans_v1.0.x.org.openide.util.actions.SystemAction
						getAdditionalCommands(): Netbeans_v1.0.x.java.util.Vector
						getAdvancedConfig(): Netbeans_v1.0.x.java.lang.Object
						getAskIfDownloadRecursively(): JavaPrimitiveTypes.boolean
						getBundleProperty(s : Netbeans_v1.0.x.java.lang.String): Netbeans_v1.0.x.java.lang.String
						getCache(): VcsCache
						getCacheId(): JavaPrimitiveTypes.long
						getCommand(name : Netbeans_v1.0.x.java.lang.String): Netbeans_v1.0.x.org.netbeans.modules.vcs.cmdline.UserCommand
						getCommands(): Netbeans_v1.0.x.java.util.Vector
						getConfig(): Netbeans_v1.0.x.java.lang.String
						getConfigRoot(): Netbeans_v1.0.x.java.lang.String
						getConfigRootFO(): Netbeans_v1.0.x.org.openide.filesystems.FileObject
						getCustomRefreshTime(): JavaPrimitiveTypes.int
						getDebug(): JavaPrimitiveTypes.boolean
						getDisplayName(): Netbeans_v1.0.x.java.lang.String
						getDoAutoRefresh(path : Netbeans_v1.0.x.java.lang.String): JavaPrimitiveTypes.boolean
						getErrorDialog(): Netbeans_v1.0.x.org.netbeans.modules.vcs.cmdline.ErrorCommandDialog
						getFile(name : Netbeans_v1.0.x.java.lang.String): Netbeans_v1.0.x.java.io.File
						-getImportantFiles(oo : Netbeans_v1.0.x.java.lang.Object): Netbeans_v1.0.x.java.util.Vector
						getLastCommandFinished(): JavaPrimitiveTypes.boolean
						getLastCommandState(): JavaPrimitiveTypes.boolean
						getLocalFileFilter(): Netbeans_v1.0.x.java.io.FilenameFilter
						getNumDoAutoRefresh(path : Netbeans_v1.0.x.java.lang.String): JavaPrimitiveTypes.int
						getPassword(): Netbeans_v1.0.x.java.lang.String
						getPromptForLockResult(): JavaPrimitiveTypes.boolean
						getRootDirectory(): Netbeans_v1.0.x.java.io.File
						getStatus(): Netbeans_v1.0.x.org.openide.filesystems.FileSystem.Status
						getVariables(): Netbeans_v1.0.x.java.util.Vector
						getVariablesAsHashtable(): Netbeans_v1.0.x.java.util.Hashtable
						getVcsFactory(): VcsFactory
						#init()
						inputStream(name : Netbeans_v1.0.x.java.lang.String): Netbeans_v1.0.x.java.io.InputStream
						isAdditionalCommand(name : Netbeans_v1.0.x.java.lang.String): JavaPrimitiveTypes.boolean
						isImportant(name : Netbeans_v1.0.x.java.lang.String): JavaPrimitiveTypes.boolean
						isLockFilesOn(): JavaPrimitiveTypes.boolean
						isPromptForLockOn(): JavaPrimitiveTypes.boolean
						isReadOnly(): JavaPrimitiveTypes.boolean
						isUseUnixShell(): JavaPrimitiveTypes.boolean
						lastModified(name : Netbeans_v1.0.x.java.lang.String): Netbeans_v1.0.x.java.util.Date
						lock(name_ : Netbeans_v1.0.x.java.lang.String)
						markUnimportant(name : Netbeans_v1.0.x.java.lang.String)
						mimeType(name : Netbeans_v1.0.x.java.lang.String): Netbeans_v1.0.x.java.lang.String
						-needAskFor(exec : Netbeans_v1.0.x.java.lang.String, vars : Netbeans_v1.0.x.java.util.Hashtable): Netbeans_v1.0.x.java.lang.String
						-needPromptFor(exec : Netbeans_v1.0.x.java.lang.String, vars : Netbeans_v1.0.x.java.util.Hashtable): Netbeans_v1.0.x.java.lang.String
						-needPromptForPR(name : Netbeans_v1.0.x.java.lang.String, exec : Netbeans_v1.0.x.java.lang.String, vars : Netbeans_v1.0.x.java.util.Hashtable): JavaPrimitiveTypes.boolean
						outputStream(name : Netbeans_v1.0.x.java.lang.String): Netbeans_v1.0.x.java.io.OutputStream
						prepareEnvironment(environment : Netbeans_v1.0.x.org.openide.filesystems.FileSystem.Environment)
						promptForVariables(exec : Netbeans_v1.0.x.java.lang.String, vars : Netbeans_v1.0.x.java.util.Hashtable, forEachFile : JavaPrimitiveTypes.boolean): JavaPrimitiveTypes.boolean
						-readObject(in : Netbeans_v1.0.x.java.io.ObjectInputStream)
						readOnly(name : Netbeans_v1.0.x.java.lang.String): JavaPrimitiveTypes.boolean
						removeNumDoAutoRefresh(path : Netbeans_v1.0.x.java.lang.String)
						rename(oldName : Netbeans_v1.0.x.java.lang.String, newName : Netbeans_v1.0.x.java.lang.String)
						setAdvancedConfig(advanced : Netbeans_v1.0.x.java.lang.Object)
						setAskIfDownloadRecursively(ask : JavaPrimitiveTypes.boolean)
						setCache(cache : VcsCache)
						setCommands(commands : Netbeans_v1.0.x.java.util.Vector)
						setConfig(label : Netbeans_v1.0.x.java.lang.String)
						setCustomRefreshTime(time : JavaPrimitiveTypes.int)
						setDebug(debug : JavaPrimitiveTypes.boolean)
						setErrorDialog(errDlg : Netbeans_v1.0.x.org.netbeans.modules.vcs.cmdline.ErrorCommandDialog)
						setImportant(important : JavaPrimitiveTypes.boolean)
						-setInitRootDirectory(r : Netbeans_v1.0.x.java.io.File)
						setLastCommandFinished(lastCommandFinished : JavaPrimitiveTypes.boolean)
						setLastCommandState(lastCommandState : JavaPrimitiveTypes.boolean)
						setLockFilesOn(lock : JavaPrimitiveTypes.boolean)
						setNumDoAutoRefresh(numDoAutoRefresh : JavaPrimitiveTypes.int, path : Netbeans_v1.0.x.java.lang.String)
						setPassword(password : Netbeans_v1.0.x.java.lang.String)
						setPromptForLockOn(prompt : JavaPrimitiveTypes.boolean)
						setPromptForLockResult(promptForLockResult : JavaPrimitiveTypes.boolean)
						setReadOnly(flag : JavaPrimitiveTypes.boolean)
						setRootDirectory(r : Netbeans_v1.0.x.java.io.File)
						setRootFile(rootFile : Netbeans_v1.0.x.java.io.File)
						#setUseUnixShell(unixShell : JavaPrimitiveTypes.boolean)
						setValidFS(v : JavaPrimitiveTypes.boolean)
						setVariables(variables : Netbeans_v1.0.x.java.util.Vector)
						size(name : Netbeans_v1.0.x.java.lang.String): JavaPrimitiveTypes.long
						statusChanged(path : Netbeans_v1.0.x.java.lang.String, recursively : JavaPrimitiveTypes.boolean)
						{static} substractRootDir(rDir : Netbeans_v1.0.x.java.lang.String, module : Netbeans_v1.0.x.java.lang.String): Netbeans_v1.0.x.java.lang.String
						unlock(name : Netbeans_v1.0.x.java.lang.String)
						#warnDirectoriesDoNotExists()
						-writeObject(out : Netbeans_v1.0.x.java.io.ObjectOutputStream)
					}
					abstract class VcsAction {
						-D: Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug
						-E: Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug
						#fileSystem: VcsFileSystem
						<<Create>> VcsAction()
						#addImportantFiles(dd : Netbeans_v1.0.x.org.openide.loaders.DataObject, res : Netbeans_v1.0.x.java.util.Vector)
						doAdditionalCommand(name : Netbeans_v1.0.x.java.lang.String, files : Netbeans_v1.0.x.java.util.Vector)
						#doCommand(files : Netbeans_v1.0.x.java.util.Vector, cmd : Netbeans_v1.0.x.org.netbeans.modules.vcs.cmdline.UserCommand)
						#doCommand(files : Netbeans_v1.0.x.java.util.Vector, cmd : Netbeans_v1.0.x.java.lang.String)
						doDetails(files : Netbeans_v1.0.x.java.util.Vector)
						doEdit(files : Netbeans_v1.0.x.java.util.Vector)
						doList(path : Netbeans_v1.0.x.java.lang.String)
						doListSub(path : Netbeans_v1.0.x.java.lang.String)
						doLock(files : Netbeans_v1.0.x.java.util.Vector)
						doUnlock(files : Netbeans_v1.0.x.java.util.Vector)
						#getNodePath(n : Netbeans_v1.0.x.org.openide.nodes.Node): Netbeans_v1.0.x.java.lang.String
						getPopupPresenter(): Netbeans_v1.0.x.javax.swing.JMenuItem
						#isOnDirectory(): JavaPrimitiveTypes.boolean
						#isOnRoot(): JavaPrimitiveTypes.boolean
						parseFromCache(cacheRecord : Netbeans_v1.0.x.java.lang.String): VcsFile
						setFileSystem(fileSystem : VcsFileSystem)
					}
					interface VcsAdvancedCustomizer {
						getEditor(fileSystem : VcsFileSystem): Netbeans_v1.0.x.java.beans.PropertyEditor
						getPanel(pe : Netbeans_v1.0.x.java.beans.PropertyEditor): Netbeans_v1.0.x.javax.swing.JPanel
						readConfig(props : Netbeans_v1.0.x.java.util.Properties): Netbeans_v1.0.x.java.lang.Object
						writeConfig(props : Netbeans_v1.0.x.java.util.Properties, config : Netbeans_v1.0.x.java.lang.Object)
					}
					interface VcsDirReader {
					}
					Netbeans_v1.0.x.org.openide.filesystems.AbstractFileSystem <|-- VcsFileSystem
					Netbeans_v1.0.x.org.openide.filesystems.AbstractFileSystem.List <|.. VcsFileSystem
					Netbeans_v1.0.x.org.openide.filesystems.AbstractFileSystem.Info <|.. VcsFileSystem
					Netbeans_v1.0.x.org.openide.filesystems.AbstractFileSystem.Change <|.. VcsFileSystem
					Netbeans_v1.0.x.org.openide.filesystems.FileSystem.Status <|.. VcsFileSystem
					Netbeans_v1.0.x.java.io.Serializable <|.. VcsFileSystem
					Netbeans_v1.0.x.org.openide.util.actions.NodeAction <|-- VcsAction
					DirReaderListener <|.. VcsCache
					Netbeans_v1.0.x.org.openide.filesystems.RepositoryListener <|.. VcsCache
					VcsFile <|-- VcsDir
					Netbeans_v1.0.x.java.lang.Runnable <|-- VcsDirReader
					Netbeans_v1.0.x.java.lang.String "ASK_FOR" <-- VcsFileSystem
					Netbeans_v1.0.x.java.lang.String "CACHE_ROOT" <-- VcsFileSystem
					Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug "D" <-- VcsFileSystem
					Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug "E" <-- VcsFileSystem
					Netbeans_v1.0.x.java.lang.String "LOCAL_FILES_ADD_VAR" <-- VcsFileSystem
					Netbeans_v1.0.x.java.lang.String "LOCK_FILES_ON" <-- VcsFileSystem
					Netbeans_v1.0.x.java.lang.String "PROMPT_FOR" <-- VcsFileSystem
					Netbeans_v1.0.x.java.lang.String "PROMPT_FOR_LOCK_ON" <-- VcsFileSystem
					JavaPrimitiveTypes.int "REFRESH_TIME" <-- VcsFileSystem
					Netbeans_v1.0.x.java.lang.String "VAR_FALSE" <-- VcsFileSystem
					Netbeans_v1.0.x.java.lang.String "VAR_TRUE" <-- VcsFileSystem
					Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug "D" <-- VcsAction
					Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug "E" <-- VcsAction
					VcsFileSystem "fileSystem" <-- VcsAction
					Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug "D" <-- VcsFile
					Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug "E" <-- VcsFile
					Netbeans_v1.0.x.java.lang.String "attr" <-- VcsFile
					Netbeans_v1.0.x.java.lang.String "date" <-- VcsFile
					JavaPrimitiveTypes.boolean "local" <-- VcsFile
					Netbeans_v1.0.x.java.lang.String "locker" <-- VcsFile
					Netbeans_v1.0.x.java.lang.String "name" <-- VcsFile
					JavaPrimitiveTypes.int "size" <-- VcsFile
					Netbeans_v1.0.x.java.lang.String "status" <-- VcsFile
					Netbeans_v1.0.x.java.lang.String "time" <-- VcsFile
					VcsAction "action" <-- VcsFileSystem
					Netbeans_v1.0.x.java.lang.Object "advanced" <-- VcsFileSystem
					JavaPrimitiveTypes.boolean "askIfDownloadRecursively" <-- VcsFileSystem
					Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug "E" <-- VcsDir
					JavaPrimitiveTypes.boolean "beingLoaded" <-- VcsDir
					Netbeans_v1.0.x.java.util.Vector "files" <-- VcsDir
					JavaPrimitiveTypes.boolean "loaded" <-- VcsDir
					Netbeans_v1.0.x.java.lang.String "path" <-- VcsDir
					Netbeans_v1.0.x.java.util.Vector "subdirs" <-- VcsDir
					Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug "D" <-- VcsDirContainer
					Netbeans_v1.0.x.java.lang.Object "element" <-- VcsDirContainer
					Netbeans_v1.0.x.java.lang.String "name" <-- VcsDirContainer
					Netbeans_v1.0.x.java.lang.String "path" <-- VcsDirContainer
					Netbeans_v1.0.x.java.util.Vector "subdirs" <-- VcsDirContainer
					Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug "D" <-- VcsCache
					Netbeans_v1.0.x.org.netbeans.modules.vcs.util.Debug "E" <-- VcsCache
					Netbeans_v1.0.x.java.lang.String "cacheDir" <-- VcsCache
					Netbeans_v1.0.x.java.util.Hashtable "dirsByName" <-- VcsCache
					VcsFileSystem "fileSystem" <-- VcsCache
					JavaPrimitiveTypes.boolean "lastCanceled" <-- VcsCache
					JavaPrimitiveTypes.boolean "localFilesAdd" <-- VcsCache
					Netbeans_v1.0.x.java.lang.String "localStatusStr" <-- VcsCache
					JavaPrimitiveTypes.int "numRefreshThreads" <-- VcsCache
					Netbeans_v1.0.x.java.util.Vector "pathsQueue" <-- VcsCache
					VcsCache "cache" <-- VcsFileSystem
					JavaPrimitiveTypes.long "cacheId" <-- VcsFileSystem
					Netbeans_v1.0.x.java.util.Hashtable "commandsByName" <-- VcsFileSystem
					Netbeans_v1.0.x.java.lang.String "config" <-- VcsFileSystem
					JavaPrimitiveTypes.boolean "debug" <-- VcsFileSystem
					Netbeans_v1.0.x.org.netbeans.modules.vcs.cmdline.ErrorCommandDialog "errorDialog" <-- VcsFileSystem
					JavaPrimitiveTypes.boolean "lastCommandFinished" <-- VcsFileSystem
					JavaPrimitiveTypes.boolean "lastCommandState" <-- VcsFileSystem
					JavaPrimitiveTypes.int "last_refreshTime" <-- VcsFileSystem
					Netbeans_v1.0.x.java.io.File "last_rootFile" <-- VcsFileSystem
					JavaPrimitiveTypes.boolean "last_useUnixShell" <-- VcsFileSystem
					JavaPrimitiveTypes.boolean "lockFilesOn" <-- VcsFileSystem
					Netbeans_v1.0.x.java.util.Hashtable "numDoAutoRefreshes" <-- VcsFileSystem
					Netbeans_v1.0.x.java.lang.String "password" <-- VcsFileSystem
					JavaPrimitiveTypes.boolean "promptForLockOn" <-- VcsFileSystem
					JavaPrimitiveTypes.boolean "promptForLockResult" <-- VcsFileSystem
					JavaPrimitiveTypes.boolean "promptForVarsForEachFile" <-- VcsFileSystem
					JavaPrimitiveTypes.boolean "readOnly" <-- VcsFileSystem
					JavaPrimitiveTypes.boolean "ready" <-- VcsFileSystem
					JavaPrimitiveTypes.int "refreshTimeToSet" <-- VcsFileSystem
					Netbeans_v1.0.x.java.io.File "rootFile" <-- VcsFileSystem
					JavaPrimitiveTypes.long "serialVersionUID" <-- VcsFileSystem
					Netbeans_v1.0.x.java.util.Vector "unimportantNames" <-- VcsFileSystem
					JavaPrimitiveTypes.boolean "useUnixShell" <-- VcsFileSystem
					Netbeans_v1.0.x.java.util.Vector "variables" <-- VcsFileSystem
					Netbeans_v1.0.x.java.util.Hashtable "variablesByName" <-- VcsFileSystem
				}
			}
		}
	}
}
@enduml
