@startuml
package "Netbeans v1.0.x" as Netbeans_v1.0.x {
	package org {
		package netbeans {
			package modules {
				package form {
					package compat2 {
						package layouts {
							class GridBagControlCenter {
								-BMButton: Netbeans_v1.0.x.javax.swing.JButton
								-BPButton: Netbeans_v1.0.x.javax.swing.JButton
								-HMButton: Netbeans_v1.0.x.javax.swing.JButton
								-HPButton: Netbeans_v1.0.x.javax.swing.JButton
								-VMButton: Netbeans_v1.0.x.javax.swing.JButton
								-VPButton: Netbeans_v1.0.x.javax.swing.JButton
								-anchorPanel: Netbeans_v1.0.x.javax.swing.JPanel
								-bottomMButton: Netbeans_v1.0.x.javax.swing.JButton
								-bottomPButton: Netbeans_v1.0.x.javax.swing.JButton
								-{const} bundle: Netbeans_v1.0.x.java.util.ResourceBundle
								-cButton: Netbeans_v1.0.x.javax.swing.JToggleButton
								-customizer: GridBagCustomizer
								-eButton: Netbeans_v1.0.x.javax.swing.JToggleButton
								-fillPanel: Netbeans_v1.0.x.javax.swing.JPanel
								-gridSizeHMButton: Netbeans_v1.0.x.javax.swing.JButton
								-gridSizeHPButton: Netbeans_v1.0.x.javax.swing.JButton
								-gridSizePanel: Netbeans_v1.0.x.javax.swing.JPanel
								-gridSizeVMButton: Netbeans_v1.0.x.javax.swing.JButton
								-gridSizeVPButton: Netbeans_v1.0.x.javax.swing.JButton
								-gsRHButton: Netbeans_v1.0.x.javax.swing.JToggleButton
								-gsRVButton: Netbeans_v1.0.x.javax.swing.JToggleButton
								-horizontalFillButton: Netbeans_v1.0.x.javax.swing.JToggleButton
								-insetsPanel: Netbeans_v1.0.x.javax.swing.JPanel
								-ipadHMButton: Netbeans_v1.0.x.javax.swing.JButton
								-ipadHPButton: Netbeans_v1.0.x.javax.swing.JButton
								-ipadPanel: Netbeans_v1.0.x.javax.swing.JPanel
								-ipadVMButton: Netbeans_v1.0.x.javax.swing.JButton
								-ipadVPButton: Netbeans_v1.0.x.javax.swing.JButton
								-jLabel1: Netbeans_v1.0.x.javax.swing.JLabel
								-jLabel2: Netbeans_v1.0.x.javax.swing.JLabel
								-jLabel3: Netbeans_v1.0.x.javax.swing.JLabel
								-jLabel4: Netbeans_v1.0.x.javax.swing.JLabel
								-jLabel5: Netbeans_v1.0.x.javax.swing.JLabel
								-jLabel6: Netbeans_v1.0.x.javax.swing.JLabel
								-jLabel8: Netbeans_v1.0.x.javax.swing.JLabel
								-leftMButton: Netbeans_v1.0.x.javax.swing.JButton
								-leftPButton: Netbeans_v1.0.x.javax.swing.JButton
								-nButton: Netbeans_v1.0.x.javax.swing.JToggleButton
								-neButton: Netbeans_v1.0.x.javax.swing.JToggleButton
								-nwButton: Netbeans_v1.0.x.javax.swing.JToggleButton
								-rightMButton: Netbeans_v1.0.x.javax.swing.JButton
								-rightPButton: Netbeans_v1.0.x.javax.swing.JButton
								-sButton: Netbeans_v1.0.x.javax.swing.JToggleButton
								-seButton: Netbeans_v1.0.x.javax.swing.JToggleButton
								{const} serialVersionUID: JavaPrimitiveTypes.long = -3758289034173265028
								-swButton: Netbeans_v1.0.x.javax.swing.JToggleButton
								-topMButton: Netbeans_v1.0.x.javax.swing.JButton
								-topPButton: Netbeans_v1.0.x.javax.swing.JButton
								-verticalFillButton: Netbeans_v1.0.x.javax.swing.JToggleButton
								-wButton: Netbeans_v1.0.x.javax.swing.JToggleButton
								<<Create>> GridBagControlCenter(customizer : GridBagCustomizer)
								-anchorButtonAction(evt : Netbeans_v1.0.x.java.awt.event.ActionEvent)
								-fillButtonAction(evt : Netbeans_v1.0.x.java.awt.event.ActionEvent)
								-gridSizeButtonAction(evt : Netbeans_v1.0.x.java.awt.event.ActionEvent)
								-initComponents()
								-insetsButtonAction(evt : Netbeans_v1.0.x.java.awt.event.ActionEvent)
								-ipadButtonAction(evt : Netbeans_v1.0.x.java.awt.event.ActionEvent)
								newSelection(proxies : Netbeans_v1.0.x.java.util.List)
							}
							Netbeans_v1.0.x.javax.swing.JPanel <|-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JPanel <|-- GridBagCustomizer
							Netbeans_v1.0.x.java.beans.Customizer <|.. GridBagCustomizer
							Netbeans_v1.0.x.org.netbeans.modules.form.FormListener <|.. GridBagCustomizer
							Netbeans_v1.0.x.org.netbeans.modules.form.util2.NbVersion "nbClassVersion" <-- ConstraintsDescription
							JavaPrimitiveTypes.long "serialVersionUID" <-- ConstraintsDescription
							Netbeans_v1.0.x.javax.swing.JButton "BMButton" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JButton "BPButton" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JButton "HMButton" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JButton "HPButton" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JButton "VMButton" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JButton "VPButton" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JPanel "anchorPanel" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JButton "bottomMButton" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JButton "bottomPButton" <-- GridBagControlCenter
							Netbeans_v1.0.x.java.util.ResourceBundle "bundle" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JToggleButton "cButton" <-- GridBagControlCenter
							JavaPrimitiveTypes.int "BOTTOM" <-- GridBagCustomizer
							JavaPrimitiveTypes.int "HORIZONTAL" <-- GridBagCustomizer
							JavaPrimitiveTypes.int "LEFT" <-- GridBagCustomizer
							JavaPrimitiveTypes.int "MINUS" <-- GridBagCustomizer
							JavaPrimitiveTypes.int "PLUS" <-- GridBagCustomizer
							Netbeans_v1.0.x.javax.swing.ImageIcon "REMAINDER_ICON" <-- GridBagCustomizer
							JavaPrimitiveTypes.int "RIGHT" <-- GridBagCustomizer
							JavaPrimitiveTypes.int "TOP" <-- GridBagCustomizer
							JavaPrimitiveTypes.int "VERTICAL" <-- GridBagCustomizer
							Netbeans_v1.0.x.java.util.ResourceBundle "bundle" <-- GridBagCustomizer
							JavaPrimitiveTypes.boolean "empties 0..*" <-- GBContainerProxy
							Netbeans_v1.0.x.java.awt.GridBagLayout "layout" <-- GBContainerProxy
							JavaPrimitiveTypes.long "serialVersionUID" <-- GBContainerProxy
							Netbeans_v1.0.x.java.awt.Color "CELL_COLOR" <-- GBComponentProxy
							Netbeans_v1.0.x.java.awt.Color "INSETS_COLOR" <-- GBComponentProxy
							Netbeans_v1.0.x.org.netbeans.modules.form.RADVisualComponent "component" <-- GBComponentProxy
							Netbeans_v1.0.x.java.awt.GridBagConstraints "componentConstraints" <-- GBComponentProxy
							Netbeans_v1.0.x.javax.swing.JLabel "componentLabel" <-- GBComponentProxy
							Netbeans_v1.0.x.javax.swing.border.CompoundBorder "compoundBorder" <-- GBComponentProxy
							Netbeans_v1.0.x.javax.swing.border.MatteBorder "insetsBorder" <-- GBComponentProxy
							JavaPrimitiveTypes.boolean "isSelected" <-- GBComponentProxy
							Netbeans_v1.0.x.java.awt.GridBagLayout "layout" <-- GBComponentProxy
							ComponentProxyNode "node" <-- GBComponentProxy
							GBContainerProxy "parentProxy" <-- GBComponentProxy
							Netbeans_v1.0.x.javax.swing.border.MatteBorder "remainderBorder" <-- GBComponentProxy
							JavaPrimitiveTypes.long "serialVersionUID" <-- GBComponentProxy
							Netbeans_v1.0.x.java.lang.String "ATTR_ANCHOR" <-- GridBagConstraintsDescription
							Netbeans_v1.0.x.java.lang.String "ATTR_FILL" <-- GridBagConstraintsDescription
							Netbeans_v1.0.x.java.lang.String "ATTR_GRID_H" <-- GridBagConstraintsDescription
							Netbeans_v1.0.x.java.lang.String "ATTR_GRID_W" <-- GridBagConstraintsDescription
							Netbeans_v1.0.x.java.lang.String "ATTR_GRID_X" <-- GridBagConstraintsDescription
							Netbeans_v1.0.x.java.lang.String "ATTR_GRID_Y" <-- GridBagConstraintsDescription
							Netbeans_v1.0.x.java.lang.String "ATTR_INSETS_BOTTOM" <-- GridBagConstraintsDescription
							Netbeans_v1.0.x.java.lang.String "ATTR_INSETS_LEFT" <-- GridBagConstraintsDescription
							Netbeans_v1.0.x.java.lang.String "ATTR_INSETS_RIGHT" <-- GridBagConstraintsDescription
							Netbeans_v1.0.x.java.lang.String "ATTR_INSETS_TOP" <-- GridBagConstraintsDescription
							Netbeans_v1.0.x.java.lang.String "ATTR_IPAD_X" <-- GridBagConstraintsDescription
							Netbeans_v1.0.x.java.lang.String "ATTR_IPAD_Y" <-- GridBagConstraintsDescription
							Netbeans_v1.0.x.java.lang.String "ATTR_WEIGHT_X" <-- GridBagConstraintsDescription
							Netbeans_v1.0.x.java.lang.String "ATTR_WEIGHT_Y" <-- GridBagConstraintsDescription
							Netbeans_v1.0.x.java.lang.String "XML_GRIDBAG_CONSTRAINTS" <-- GridBagConstraintsDescription
							Netbeans_v1.0.x.java.awt.GridBagConstraints "constraints" <-- GridBagConstraintsDescription
							Netbeans_v1.0.x.org.netbeans.modules.form.util2.NbVersion "nbClassVersion" <-- GridBagConstraintsDescription
							JavaPrimitiveTypes.long "serialVersionUID" <-- GridBagConstraintsDescription
							Netbeans_v1.0.x.java.awt.Point "hotSpot" <-- DragLabel
							Netbeans_v1.0.x.java.awt.Point "lastIndex" <-- DragLabel
							Netbeans_v1.0.x.java.awt.Point "origin" <-- DragLabel
							Netbeans_v1.0.x.java.awt.Point "originalIndex" <-- DragLabel
							Netbeans_v1.0.x.java.awt.Dimension "preferredSize" <-- DragLabel
							JavaPrimitiveTypes.long "serialVersionUID" <-- DragLabel
							GBContainerProxy "containerProxy" <-- GridBagCustomizer
							GridBagControlCenter "controlCenter" <-- GridBagCustomizer
							Netbeans_v1.0.x.javax.swing.JLayeredPane "designLayeredPane" <-- GridBagCustomizer
							DesignGridBagLayout "designLayout" <-- GridBagCustomizer
							Netbeans_v1.0.x.javax.swing.JPanel "designPanel" <-- GridBagCustomizer
							Netbeans_v1.0.x.javax.swing.JScrollPane "designScrollPane" <-- GridBagCustomizer
							DragLabel "dragLabel" <-- GridBagCustomizer
							JavaPrimitiveTypes.boolean "firstPaint" <-- GridBagCustomizer
							Netbeans_v1.0.x.org.netbeans.modules.form.FormManager2 "formManager" <-- GridBagCustomizer
							GBComponentProxy "gbcProxies 0..*" <-- GridBagCustomizer
							Netbeans_v1.0.x.org.openide.explorer.propertysheet.PropertySheet "propertySheet" <-- GridBagCustomizer
							Netbeans_v1.0.x.java.beans.PropertyChangeSupport "propertySupport" <-- GridBagCustomizer
							Netbeans_v1.0.x.org.netbeans.modules.form.RADVisualComponent "radComponents 0..*" <-- GridBagCustomizer
							Netbeans_v1.0.x.org.netbeans.modules.form.RADVisualContainer "radContainer" <-- GridBagCustomizer
							JavaPrimitiveTypes.long "serialVersionUID" <-- GridBagCustomizer
							Netbeans_v1.0.x.org.openide.awt.SplittedPanel "splitPanel" <-- GridBagCustomizer
							GridBagCustomizer "customizer" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JToggleButton "eButton" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JPanel "fillPanel" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JButton "gridSizeHMButton" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JButton "gridSizeHPButton" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JPanel "gridSizePanel" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JButton "gridSizeVMButton" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JButton "gridSizeVPButton" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JToggleButton "gsRHButton" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JToggleButton "gsRVButton" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JToggleButton "horizontalFillButton" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JPanel "insetsPanel" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JButton "ipadHMButton" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JButton "ipadHPButton" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JPanel "ipadPanel" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JButton "ipadVMButton" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JButton "ipadVPButton" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JLabel "jLabel1" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JLabel "jLabel2" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JLabel "jLabel3" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JLabel "jLabel4" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JLabel "jLabel5" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JLabel "jLabel6" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JLabel "jLabel8" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JButton "leftMButton" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JButton "leftPButton" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JToggleButton "nButton" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JToggleButton "neButton" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JToggleButton "nwButton" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JButton "rightMButton" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JButton "rightPButton" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JToggleButton "sButton" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JToggleButton "seButton" <-- GridBagControlCenter
							JavaPrimitiveTypes.long "serialVersionUID" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JToggleButton "swButton" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JButton "topMButton" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JButton "topPButton" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JToggleButton "verticalFillButton" <-- GridBagControlCenter
							Netbeans_v1.0.x.javax.swing.JToggleButton "wButton" <-- GridBagControlCenter
						}
					}
					class FormManager2 {
						{const} MIN_DRAG_DIST: JavaPrimitiveTypes.int = 3
						-addItem: Netbeans_v1.0.x.org.netbeans.modules.form.palette.PaletteItem
						-addingDragMode: JavaPrimitiveTypes.boolean
						-addingMode: JavaPrimitiveTypes.boolean
						-codeGenerator: CodeGenerator
						-componentToLayer: Netbeans_v1.0.x.java.util.HashMap
						-connectionSource: RADComponent
						-currentSelection: RADComponent [*]
						-deletingNodes: JavaPrimitiveTypes.boolean
						-{static} designModeAction: Netbeans_v1.0.x.org.netbeans.modules.form.actions.DesignModeAction
						-dragConstraints: Netbeans_v1.0.x.org.netbeans.modules.form.compat2.layouts.DesignLayout.ConstraintsDescription
						-dragLayout: Netbeans_v1.0.x.org.netbeans.modules.form.compat2.layouts.DesignLayout
						-dragPoint: Netbeans_v1.0.x.java.awt.Point
						-encoding: Netbeans_v1.0.x.java.lang.String
						-eventsManager: EventsManager
						-formContainer: Netbeans_v1.0.x.java.awt.Container
						-formEditorSupport: FormEditorSupport
						-formListeners: Netbeans_v1.0.x.java.util.ArrayList
						-formObject: FormDataObject
						-formWindow: FormTopComponent
						-ignoreMouse: JavaPrimitiveTypes.boolean
						-initialized: JavaPrimitiveTypes.boolean
						-{static} lastSelectedNodes: Netbeans_v1.0.x.org.openide.nodes.Node [*]
						-mListener: MoveListener
						-mma: ManagerMouseAdapter
						-mode: JavaPrimitiveTypes.int
						-mouseMotionProcessor: MouseMotionProcessor
						-mouseProcessor: MouseProcessor
						-movingDragMode: JavaPrimitiveTypes.boolean
						-movingMode: JavaPrimitiveTypes.boolean
						-movingRADVisualComponent: RADVisualComponent
						-nonVisChildren: NonVisualChildren
						-nonVisList: Netbeans_v1.0.x.java.util.ArrayList
						-nonVisualsContainer: ComponentContainer
						-originalDragConstraints: Netbeans_v1.0.x.org.netbeans.modules.form.compat2.layouts.DesignLayout.ConstraintsDescription
						-originalDragPoint: Netbeans_v1.0.x.java.awt.Point
						-originalHotSpot: Netbeans_v1.0.x.java.awt.Point
						-originalLocation: Netbeans_v1.0.x.java.awt.Point
						-outerMovingMode: JavaPrimitiveTypes.boolean
						-{static} palette: Netbeans_v1.0.x.org.netbeans.modules.form.palette.ComponentPalette
						-parentRADContainer: RADVisualContainer
						-rListener: ResizeListener
						-radForm: RADForm
						-radToSelection: Netbeans_v1.0.x.java.util.HashMap
						-resizingMode: JavaPrimitiveTypes.boolean
						-savedDesignMode: JavaPrimitiveTypes.int
						-savedFormBounds: Netbeans_v1.0.x.java.awt.Rectangle
						-testMode: JavaPrimitiveTypes.boolean
						-variablesPool: VariablesPool
						-visualToRAD: Netbeans_v1.0.x.java.util.HashMap
						<<Create>> FormManager2(formObject : FormDataObject, radForm : RADForm)
						-addComponentsRecursively(cont : ComponentContainer, list : Netbeans_v1.0.x.java.util.ArrayList)
						addFormListener(l : FormListener)
						-addMouseAdapters(node : RADVisualComponent, cont : Netbeans_v1.0.x.java.awt.Container, parent : Netbeans_v1.0.x.java.awt.Component)
						addMouseAdaptersForAdditional(comp : Netbeans_v1.0.x.java.awt.Component, parent : RADVisualContainer)
						-addMouseAdaptersRecursively(comp : Netbeans_v1.0.x.java.awt.Component, parent : Netbeans_v1.0.x.java.awt.Component, table : Netbeans_v1.0.x.java.util.Map)
						addNonVisualComponent(comp : RADComponent, parentContainer : ComponentContainer)
						addVisualComponent(comp : RADVisualComponent, parentContainer : RADVisualContainer, constraints : Netbeans_v1.0.x.org.netbeans.modules.form.compat2.layouts.DesignLayout.ConstraintsDescription)
						addVisualComponentsRecursively(parent : RADVisualContainer)
						cancelSelection()
						-checkComponentNames(comp : RADComponent)
						-createParentEvent(evt : Netbeans_v1.0.x.java.awt.event.MouseEvent, parent : Netbeans_v1.0.x.java.awt.Component): Netbeans_v1.0.x.java.awt.event.MouseEvent
						deleteComponent(comp : RADComponent)
						-deleteVariables(comp : RADComponent)
						finalize()
						-{static} findDelta(from : RADComponent, to : RADComponent): RADComponent
						findRADComponent(name : Netbeans_v1.0.x.java.lang.String): RADComponent
						-finishConnection(source : RADComponent, target : RADComponent, cw1 : ConnectionWizard1, cw2 : ConnectionWizard2, cw3 : ConnectionWizard3)
						#fireCodeChange()
						#fireComponentChanged(comp : RADComponent, propertyName : Netbeans_v1.0.x.java.lang.String, oldValue : Netbeans_v1.0.x.java.lang.Object, newValue : Netbeans_v1.0.x.java.lang.Object)
						#fireComponentsAdded(comps : RADComponent)
						#fireComponentsRemoved(comps : RADComponent)
						#fireComponentsReordered(cont : ComponentContainer)
						#fireEventAdded(comp : RADComponent, event : EventHandler)
						#fireEventRemoved(comp : RADComponent, event : EventHandler)
						#fireEventRenamed(comp : RADComponent, event : EventHandler, oldName : Netbeans_v1.0.x.java.lang.String)
						#fireFormChange()
						#fireFormLoaded()
						#fireFormToBeSaved()
						fireLayoutChanged(cont : RADVisualContainer, comp : RADVisualComponent, propName : Netbeans_v1.0.x.java.lang.String, oldVal : Netbeans_v1.0.x.java.lang.Object, newVal : Netbeans_v1.0.x.java.lang.Object)
						#firePropertyChanged(comp : RADComponent, propertyName : Netbeans_v1.0.x.java.lang.String, oldValue : Netbeans_v1.0.x.java.lang.Object, newValue : Netbeans_v1.0.x.java.lang.Object)
						getAllComponents(): Netbeans_v1.0.x.java.util.Collection
						getCodeGenerator(): CodeGenerator
						-{static} getComponentsFromNodes(nodes : Netbeans_v1.0.x.org.openide.nodes.Node): RADComponent
						getEncoding(): Netbeans_v1.0.x.java.lang.String
						getEventsManager(): EventsManager
						getFormEditorSupport(): FormEditorSupport
						getFormObject(): FormDataObject
						getFormTopComponent(): FormTopComponent
						getMode(): JavaPrimitiveTypes.int
						getNonVisualChildren(): NonVisualChildren
						getNonVisualComponents(): RADComponent
						getNonVisualsContainer(): ComponentContainer
						getRADForm(): RADForm
						-getRealLocation(radComp : RADVisualComponent): Netbeans_v1.0.x.java.awt.Point
						getVariablesPool(): VariablesPool
						getVisualComponents(): Netbeans_v1.0.x.java.util.Collection
						getVisualRepresentation(radComp : RADComponent): Netbeans_v1.0.x.java.awt.Component
						initFormTopComponent(ftc : FormTopComponent)
						initNonVisualComponents(comps : RADComponent)
						initialize()
						isInitialized(): JavaPrimitiveTypes.boolean
						-isSelected(radComp : RADComponent): JavaPrimitiveTypes.boolean
						isTestMode(): JavaPrimitiveTypes.boolean
						{static} recalculatePoint(evt : Netbeans_v1.0.x.java.awt.event.MouseEvent): Netbeans_v1.0.x.java.awt.Point
						removeFormListener(l : FormListener)
						reorderNonVisualComponents(perm : JavaPrimitiveTypes.int)
						selectComponent(radComp : RADComponent, multiSelect : JavaPrimitiveTypes.boolean)
						setCodeGenerator(codeGenerator : CodeGenerator)
						setDesignLayout(cont : RADVisualContainer, layout : Netbeans_v1.0.x.org.netbeans.modules.form.palette.PaletteItem)
						setEncoding(encoding : Netbeans_v1.0.x.java.lang.String)
						setMode(value : JavaPrimitiveTypes.int)
						-setModeRecursively(cont : RADVisualContainer, mode : JavaPrimitiveTypes.int)
						setTestMode(value : JavaPrimitiveTypes.boolean)
						-startConnection(source : RADComponent, target : RADComponent)
						updateSelection(newSelectionNodes : Netbeans_v1.0.x.org.openide.nodes.Node)
					}
					interface FormListener {
						codeChanged()
						componentChanged(evt : FormPropertyEvent)
						componentsAdded(comps : RADComponent)
						componentsRemoved(comps : RADComponent)
						componentsReordered(cont : ComponentContainer)
						eventAdded(evt : FormEventEvent)
						eventRemoved(evt : FormEventEvent)
						eventRenamed(evt : FormEventEvent)
						formChanged()
						formLoaded()
						formToBeSaved()
						layoutChanged(container : RADVisualContainer, component : RADVisualComponent, propertyName : Netbeans_v1.0.x.java.lang.String, oldValue : Netbeans_v1.0.x.java.lang.Object, newValue : Netbeans_v1.0.x.java.lang.Object)
						propertyChanged(evt : FormPropertyEvent)
					}
					class FormAdapter {
						<<Create>> FormAdapter()
						codeChanged()
						componentChanged(evt : FormPropertyEvent)
						componentsAdded(comps : RADComponent)
						componentsRemoved(comps : RADComponent)
						componentsReordered(cont : ComponentContainer)
						eventAdded(evt : FormEventEvent)
						eventRemoved(evt : FormEventEvent)
						eventRenamed(evt : FormEventEvent)
						formChanged()
						formLoaded()
						formToBeSaved()
						layoutChanged(container : RADVisualContainer, component : RADVisualComponent, propertyName : Netbeans_v1.0.x.java.lang.String, oldValue : Netbeans_v1.0.x.java.lang.Object, newValue : Netbeans_v1.0.x.java.lang.Object)
						propertyChanged(evt : FormPropertyEvent)
					}
					class JavaCodeGenerator {
						#{const} AUX_CODE_GENERATION: Netbeans_v1.0.x.java.lang.String = JavaCodeGenerator_CodeGeneration
						#{const} AUX_CREATE_CODE_CUSTOM: Netbeans_v1.0.x.java.lang.String = JavaCodeGenerator_CreateCodeCustom
						#{const} AUX_CREATE_CODE_POST: Netbeans_v1.0.x.java.lang.String = JavaCodeGenerator_CreateCodePost
						#{const} AUX_CREATE_CODE_PRE: Netbeans_v1.0.x.java.lang.String = JavaCodeGenerator_CreateCodePre
						#{const} AUX_INIT_CODE_POST: Netbeans_v1.0.x.java.lang.String = JavaCodeGenerator_InitCodePost
						#{const} AUX_INIT_CODE_PRE: Netbeans_v1.0.x.java.lang.String = JavaCodeGenerator_InitCodePre
						#{const} AUX_SERIALIZE_TO: Netbeans_v1.0.x.java.lang.String = JavaCodeGenerator_SerializeTo
						#{const} AUX_VARIABLE_MODIFIER: Netbeans_v1.0.x.java.lang.String = JavaCodeGenerator_VariableModifier
						-{const} EVT_SECTION_PREFIX: Netbeans_v1.0.x.java.lang.String = event_
						-{static} GEN_LOCK: Netbeans_v1.0.x.java.lang.Object
						-{const} INIT_COMPONENTS_FOOTER: Netbeans_v1.0.x.java.lang.String
						-{const} INIT_COMPONENTS_HEADER: Netbeans_v1.0.x.java.lang.String
						#{const} SECTION_EVENT_PREFIX: Netbeans_v1.0.x.java.lang.String = event_
						#{const} SECTION_INIT_COMPONENTS: Netbeans_v1.0.x.java.lang.String = initComponents
						#{const} SECTION_VARIABLES: Netbeans_v1.0.x.java.lang.String = variables
						{const} VALUE_GENERATE_CODE: Netbeans_v1.0.x.java.lang.Integer
						{const} VALUE_SERIALIZE: Netbeans_v1.0.x.java.lang.Integer
						-{const} VARIABLES_FOOTER: Netbeans_v1.0.x.java.lang.String
						-{const} VARIABLES_HEADER: Netbeans_v1.0.x.java.lang.String
						-errorInitializing: JavaPrimitiveTypes.boolean
						-formManager: FormManager2
						-initComponentsSection: Netbeans_v1.0.x.org.netbeans.modules.java.JavaEditor.SimpleSection
						-initialized: JavaPrimitiveTypes.boolean
						-listener: JCGFormListener
						-{const} oneIndent: Netbeans_v1.0.x.java.lang.String =   
						-variablesSection: Netbeans_v1.0.x.org.netbeans.modules.java.JavaEditor.SimpleSection
						<<Create>> JavaCodeGenerator()
						-addCreateCode(comp : RADComponent, initCodeWriter : Netbeans_v1.0.x.java.io.Writer)
						-addInitCode(comp : RADComponent, initCodeWriter : Netbeans_v1.0.x.java.io.Writer, initCodeBuffer : AWTIndentStringWriter, level : JavaPrimitiveTypes.int)
						-addVariables(cont : ComponentContainer, variablesWriter : Netbeans_v1.0.x.java.io.Writer)
						changeEventHandler(handlerName : Netbeans_v1.0.x.java.lang.String, paramTypes : Netbeans_v1.0.x.java.lang.String, bodyText : Netbeans_v1.0.x.java.lang.String): JavaPrimitiveTypes.boolean
						-clearUndo()
						deleteEventHandler(handlerName : Netbeans_v1.0.x.java.lang.String): JavaPrimitiveTypes.boolean
						finalize()
						-generateComponentAddCode(comp : RADComponent, container : RADVisualContainer, initCodeWriter : Netbeans_v1.0.x.java.io.Writer)
						-generateComponentCreate(comp : RADComponent, initCodeWriter : Netbeans_v1.0.x.java.io.Writer)
						-generateComponentEvents(comp : RADComponent, initCodeWriter : Netbeans_v1.0.x.java.io.Writer)
						-generateComponentInit(comp : RADComponent, initCodeWriter : Netbeans_v1.0.x.java.io.Writer)
						generateEventHandler(handlerName : Netbeans_v1.0.x.java.lang.String, paramTypes : Netbeans_v1.0.x.java.lang.String, bodyText : Netbeans_v1.0.x.java.lang.String): JavaPrimitiveTypes.boolean
						-generateMenuAddCode(comp : RADComponent, container : RADMenuComponent, initCodeWriter : Netbeans_v1.0.x.java.io.Writer)
						-generatePropertySetter(comp : RADComponent, prop : RADProperty, initCodeWriter : Netbeans_v1.0.x.java.io.Writer)
						-getDefaultEventBody(): Netbeans_v1.0.x.java.lang.String
						-getDefaultSerializedName(component : RADComponent): Netbeans_v1.0.x.java.lang.String
						-getEventHandlerBody(handlerName : Netbeans_v1.0.x.java.lang.String, paramTypes : Netbeans_v1.0.x.java.lang.String, bodyText : Netbeans_v1.0.x.java.lang.String): Netbeans_v1.0.x.java.lang.String
						-getEventHandlerFooter(handlerName : Netbeans_v1.0.x.java.lang.String, paramTypes : Netbeans_v1.0.x.java.lang.String): Netbeans_v1.0.x.java.lang.String
						-getEventHandlerHeader(handlerName : Netbeans_v1.0.x.java.lang.String, paramTypes : Netbeans_v1.0.x.java.lang.String): Netbeans_v1.0.x.java.lang.String
						-getEventHandlerSection(eventName : Netbeans_v1.0.x.java.lang.String): Netbeans_v1.0.x.org.netbeans.modules.java.JavaEditor.InteriorSection
						-getEventSectionName(handlerName : Netbeans_v1.0.x.java.lang.String): Netbeans_v1.0.x.java.lang.String
						-getMethodHeaderText(m : Netbeans_v1.0.x.java.lang.reflect.Method, paramNames : Netbeans_v1.0.x.java.lang.String): Netbeans_v1.0.x.java.lang.String
						getSyntheticProperties(component : RADComponent): Netbeans_v1.0.x.org.openide.nodes.Node.Property
						-{static} getVariableGenString(comp : RADComponent, containerCode : JavaPrimitiveTypes.boolean): Netbeans_v1.0.x.java.lang.String
						gotoEventHandler(handlerName : Netbeans_v1.0.x.java.lang.String)
						initialize(formManager : FormManager2)
						-regenerateInitializer()
						-regenerateVariables()
						renameEventHandler(oldHandlerName : Netbeans_v1.0.x.java.lang.String, newHandlerName : Netbeans_v1.0.x.java.lang.String, paramTypes : Netbeans_v1.0.x.java.lang.String): JavaPrimitiveTypes.boolean
					}
					Netbeans_v1.0.x.org.openide.nodes.AbstractNode <|-- RADComponentNode
					RADComponentCookie <|.. RADComponentNode
					FormCookie <|.. RADComponentNode
					Netbeans_v1.0.x.org.openide.nodes.Node.Cookie <|-- RADComponentCookie
					Netbeans_v1.0.x.org.openide.nodes.Node.Cookie <|-- FormCookie
					Netbeans_v1.0.x.org.openide.cookies.InstanceCookie <|.. RADComponentInstance
					Netbeans_v1.0.x.org.openide.options.SystemOption <|-- FormLoaderSettings
					Netbeans_v1.0.x.org.netbeans.modules.java.JavaEditor <|-- FormEditorSupport
					FormCookie <|.. FormEditorSupport
					Netbeans_v1.0.x.org.netbeans.modules.java.JavaDataObject <|-- FormDataObject
					Netbeans_v1.0.x.org.netbeans.modules.java.JavaDataLoader <|-- FormDataLoader
					Netbeans_v1.0.x.org.openide.windows.TopComponent <|-- FormTopComponent
					RADComponent <|-- RADVisualComponent
					RADVisualComponent <|-- RADVisualContainer
					ComponentContainer <|.. RADVisualContainer
					Netbeans_v1.0.x.org.openide.nodes.AbstractNode <|-- RADLayoutNode
					FormLayoutCookie <|.. RADLayoutNode
					FormCookie <|.. RADLayoutNode
					Netbeans_v1.0.x.org.openide.nodes.Node.Cookie <|-- FormLayoutCookie
					Netbeans_v1.0.x.org.openide.nodes.Children.Keys <|-- NonVisualChildren
					ComponentContainer <|-- FormContainer
					Netbeans_v1.0.x.java.util.EventListener <|-- FormListener
					FormEvent <|-- FormPropertyEvent
					Netbeans_v1.0.x.java.util.EventObject <|-- FormEvent
					FormEvent <|-- FormEventEvent
					Netbeans_v1.0.x.javax.swing.JDialog <|-- ConnectionWizard1
					Netbeans_v1.0.x.javax.swing.JDialog <|-- ConnectionWizard2
					Netbeans_v1.0.x.javax.swing.JDialog <|-- ConnectionWizard3
					Netbeans_v1.0.x.javax.swing.JPanel <|-- ParametersPicker
					Netbeans_v1.0.x.org.openide.explorer.propertysheet.editors.EnhancedCustomPropertyEditor <|.. ParametersPicker
					Netbeans_v1.0.x.javax.swing.JDialog <|-- MethodPicker
					Netbeans_v1.0.x.javax.swing.JDialog <|-- PropertyPicker
					Netbeans_v1.0.x.java.io.Serializable <|-- FormDesignValue
					FormListener <|.. FormAdapter
					CodeGenerator <|-- JavaCodeGenerator
					RADMenuItemComponent <|-- RADMenuComponent
					ComponentContainer <|.. RADMenuComponent
					RADComponent <|-- RADMenuItemComponent
					JavaPrimitiveTypes.int "MIN_DRAG_DIST" <-- FormManager2
					Netbeans_v1.0.x.org.netbeans.modules.form.palette.PaletteItem "addItem" <-- FormManager2
					JavaPrimitiveTypes.boolean "addingDragMode" <-- FormManager2
					JavaPrimitiveTypes.boolean "addingMode" <-- FormManager2
					Netbeans_v1.0.x.org.openide.util.datatransfer.NewType "NO_NEW_TYPES 0..*" <-- RADComponent
					Netbeans_v1.0.x.org.openide.nodes.Node.Property "NO_PROPERTIES 0..*" <-- RADComponent
					Netbeans_v1.0.x.java.lang.String "PROP_NAME" <-- RADComponent
					Netbeans_v1.0.x.java.lang.String "SYNTHETIC_PREFIX" <-- RADComponent
					RADProperty "allProperties 0..*" <-- RADComponent
					Netbeans_v1.0.x.java.util.HashMap "auxValues" <-- RADComponent
					Netbeans_v1.0.x.java.lang.Class "beanClass" <-- RADComponent
					Netbeans_v1.0.x.org.openide.nodes.Node.Property "beanEvents 0..*" <-- RADComponent
					Netbeans_v1.0.x.org.openide.nodes.Node.Property "beanExpertProperties 0..*" <-- RADComponent
					Netbeans_v1.0.x.java.beans.BeanInfo "beanInfo" <-- RADComponent
					Netbeans_v1.0.x.java.lang.Object "beanInstance" <-- RADComponent
					Netbeans_v1.0.x.org.openide.nodes.Node.Property "beanProperties 0..*" <-- RADComponent
					Netbeans_v1.0.x.org.openide.nodes.Node.PropertySet "beanPropertySets 0..*" <-- RADComponent
					Netbeans_v1.0.x.java.lang.String "componentName" <-- RADComponent
					Netbeans_v1.0.x.java.awt.datatransfer.DataFlavor "RAD_COMPONENT_COPY_FLAVOR" <-- RADComponentNode
					Netbeans_v1.0.x.java.awt.datatransfer.DataFlavor "RAD_COMPONENT_CUT_FLAVOR" <-- RADComponentNode
					RADComponent "component" <-- RADComponentNode
					Netbeans_v1.0.x.java.text.MessageFormat "formNameFormat" <-- RADComponentNode
					Netbeans_v1.0.x.java.text.MessageFormat "nameFormat" <-- RADComponentNode
					RADComponent "component" <-- RADComponentInstance
					RADComponentInstance "radComponentInstance" <-- RADComponentNode
					Netbeans_v1.0.x.org.openide.cookies.InstanceCookie "cookie" <-- InstancePaste
					JavaPrimitiveTypes.long "serialVersionUID" <-- RADDataFlavor
					Netbeans_v1.0.x.java.awt.datatransfer.Transferable "transferable" <-- RADPaste
					Netbeans_v1.0.x.java.awt.datatransfer.DataFlavor "flavors 0..*" <-- RADTransferable
					RADComponent "radComponent" <-- RADTransferable
					RADComponentNode "componentNode" <-- RADComponent
					Netbeans_v1.0.x.java.util.Map "defaultPropertyValues" <-- RADComponent
					Netbeans_v1.0.x.java.util.HashMap "editorsCache" <-- RADComponent
					Netbeans_v1.0.x.java.lang.String "PROP_HANDLER" <-- EventsList
					Netbeans_v1.0.x.java.beans.EventSetDescriptor "desc" <-- EventSet
					Netbeans_v1.0.x.java.util.Vector "eventHandlers" <-- Event
					Netbeans_v1.0.x.java.lang.reflect.Method "listenerMethod" <-- Event
					Netbeans_v1.0.x.java.beans.PropertyChangeSupport "propertySupport" <-- Event
					Netbeans_v1.0.x.java.util.Vector "attachedEvents" <-- EventHandler
					Netbeans_v1.0.x.java.lang.String "handlerName" <-- EventHandler
					Netbeans_v1.0.x.java.lang.String "parameterTypes 0..*" <-- EventHandler
					JavaPrimitiveTypes.long "serialVersionUID" <-- EventHandler
					Event "events 0..*" <-- EventSet
					EventSet "eventSetHandlers 0..*" <-- EventsList
					EventsManager "eventsManager" <-- EventsList
					JavaPrimitiveTypes.int "MAX_SELECTION_BORDER_SIZE" <-- FormLoaderSettings
					JavaPrimitiveTypes.int "MIN_GRID_X" <-- FormLoaderSettings
					JavaPrimitiveTypes.int "MIN_GRID_Y" <-- FormLoaderSettings
					JavaPrimitiveTypes.int "MIN_SELECTION_BORDER_SIZE" <-- FormLoaderSettings
					JavaPrimitiveTypes.int "OUTPUT_MAXIMUM" <-- FormLoaderSettings
					JavaPrimitiveTypes.int "OUTPUT_MINIMUM" <-- FormLoaderSettings
					JavaPrimitiveTypes.int "OUTPUT_NORMAL" <-- FormLoaderSettings
					Netbeans_v1.0.x.java.lang.String "PROP_APPLY_GRID_TO_POSITION" <-- FormLoaderSettings
					Netbeans_v1.0.x.java.lang.String "PROP_APPLY_GRID_TO_SIZE" <-- FormLoaderSettings
					Netbeans_v1.0.x.java.lang.String "PROP_CONNECTION_BORDER_COLOR" <-- FormLoaderSettings
					Netbeans_v1.0.x.java.lang.String "PROP_DISPLAY_WRITABLE_ONLY" <-- FormLoaderSettings
					Netbeans_v1.0.x.java.lang.String "PROP_DRAG_BORDER_COLOR" <-- FormLoaderSettings
					Netbeans_v1.0.x.java.lang.String "PROP_EDITOR_SEARCH_PATH" <-- FormLoaderSettings
					Netbeans_v1.0.x.java.lang.String "PROP_EVENT_VARIABLE_NAME" <-- FormLoaderSettings
					Netbeans_v1.0.x.java.lang.String "PROP_GRID_X" <-- FormLoaderSettings
					Netbeans_v1.0.x.java.lang.String "PROP_GRID_Y" <-- FormLoaderSettings
					Netbeans_v1.0.x.java.lang.String "PROP_INDENT_AWT_HIERARCHY" <-- FormLoaderSettings
					Netbeans_v1.0.x.java.lang.String "PROP_NULL_LAYOUT" <-- FormLoaderSettings
					Netbeans_v1.0.x.java.lang.String "PROP_OUTPUT_LEVEL" <-- FormLoaderSettings
					Netbeans_v1.0.x.java.lang.String "PROP_REGISTERED_EDITORS" <-- FormLoaderSettings
					Netbeans_v1.0.x.java.lang.String "PROP_SELECTION_BORDER_COLOR" <-- FormLoaderSettings
					Netbeans_v1.0.x.java.lang.String "PROP_SELECTION_BORDER_SIZE" <-- FormLoaderSettings
					Netbeans_v1.0.x.java.lang.String "PROP_SHORT_BEAN_NAMES" <-- FormLoaderSettings
					Netbeans_v1.0.x.java.lang.String "PROP_SHOW_GRID" <-- FormLoaderSettings
					Netbeans_v1.0.x.java.lang.String "PROP_SORT_EVENT_SETS" <-- FormLoaderSettings
					Netbeans_v1.0.x.java.lang.String "PROP_VARIABLES_MODIFIER" <-- FormLoaderSettings
					Netbeans_v1.0.x.java.lang.String "PROP_WORKSPACE" <-- FormLoaderSettings
					JavaPrimitiveTypes.boolean "applyGridToPosition" <-- FormLoaderSettings
					JavaPrimitiveTypes.boolean "applyGridToSize" <-- FormLoaderSettings
					Netbeans_v1.0.x.java.awt.Color "connectionBorderColor" <-- FormLoaderSettings
					JavaPrimitiveTypes.boolean "displayWritableOnly" <-- FormLoaderSettings
					Netbeans_v1.0.x.java.awt.Color "dragBorderColor" <-- FormLoaderSettings
					Netbeans_v1.0.x.java.lang.String "editorSearchPath 0..*" <-- FormLoaderSettings
					JavaPrimitiveTypes.int "emptyFormType" <-- FormLoaderSettings
					Netbeans_v1.0.x.java.lang.String "eventVariableName" <-- FormLoaderSettings
					JavaPrimitiveTypes.int "gridX" <-- FormLoaderSettings
					JavaPrimitiveTypes.int "gridY" <-- FormLoaderSettings
					JavaPrimitiveTypes.boolean "indentAWTHierarchy" <-- FormLoaderSettings
					JavaPrimitiveTypes.boolean "nullLayout" <-- FormLoaderSettings
					JavaPrimitiveTypes.int "outputLevel" <-- FormLoaderSettings
					Netbeans_v1.0.x.java.lang.String "registeredEditors 0..*" <-- FormLoaderSettings
					Netbeans_v1.0.x.java.awt.Color "selectionBorderColor" <-- FormLoaderSettings
					JavaPrimitiveTypes.int "selectionBorderSize" <-- FormLoaderSettings
					JavaPrimitiveTypes.long "serialVersionUID" <-- FormLoaderSettings
					JavaPrimitiveTypes.boolean "shortBeanNames" <-- FormLoaderSettings
					JavaPrimitiveTypes.boolean "showGrid" <-- FormLoaderSettings
					JavaPrimitiveTypes.boolean "sortEventSets" <-- FormLoaderSettings
					JavaPrimitiveTypes.int "variablesModifier" <-- FormLoaderSettings
					Netbeans_v1.0.x.java.lang.String "workspace" <-- FormLoaderSettings
					FormLoaderSettings "formSettings" <-- EventsList
					JavaPrimitiveTypes.boolean "preserveEmptyHandlers" <-- EventsList
					RADComponent "radComponent" <-- EventsList
					EventsList "eventsList" <-- RADComponent
					FormManager2 "formManager" <-- RADComponent
					Netbeans_v1.0.x.java.lang.String "gotoMethod" <-- RADComponent
					Netbeans_v1.0.x.java.util.HashMap "nameToProperty" <-- RADComponent
					Netbeans_v1.0.x.java.lang.String "storedName" <-- RADComponent
					Netbeans_v1.0.x.org.openide.nodes.Node.Property "syntheticProperties 0..*" <-- RADComponent
					Netbeans_v1.0.x.java.util.HashMap "valuesCache" <-- RADComponent
					Event "event" <-- EventProperty
					Netbeans_v1.0.x.java.lang.String "lastSelectedHandler" <-- EventProperty
					Netbeans_v1.0.x.java.util.Vector "added" <-- HandlerSetChange
					Netbeans_v1.0.x.java.util.Vector "removed" <-- HandlerSetChange
					Netbeans_v1.0.x.java.util.Vector "renamedNewName" <-- HandlerSetChange
					Netbeans_v1.0.x.java.util.Vector "renamedOldName" <-- HandlerSetChange
					JavaPrimitiveTypes.boolean "changed" <-- RADIndexedPropertyImpl
					Netbeans_v1.0.x.java.beans.PropertyEditor "currentEditor" <-- RADIndexedPropertyImpl
					Netbeans_v1.0.x.java.beans.IndexedPropertyDescriptor "desc" <-- RADIndexedPropertyImpl
					Netbeans_v1.0.x.java.lang.String "postCode" <-- RADIndexedPropertyImpl
					Netbeans_v1.0.x.java.lang.String "preCode" <-- RADIndexedPropertyImpl
					JavaPrimitiveTypes.boolean "changed" <-- RADPropertyImpl
					Netbeans_v1.0.x.java.beans.PropertyEditor "currentPropertyEditor" <-- RADPropertyImpl
					Netbeans_v1.0.x.java.beans.PropertyDescriptor "desc" <-- RADPropertyImpl
					Netbeans_v1.0.x.java.lang.String "postCode" <-- RADPropertyImpl
					Netbeans_v1.0.x.java.lang.String "preCode" <-- RADPropertyImpl
					CodeGenerator "codeGenerator" <-- FormManager2
					Netbeans_v1.0.x.java.util.HashMap "componentToLayer" <-- FormManager2
					RADComponent "connectionSource" <-- FormManager2
					RADComponent "currentSelection 0..*" <-- FormManager2
					JavaPrimitiveTypes.boolean "deletingNodes" <-- FormManager2
					Netbeans_v1.0.x.org.netbeans.modules.form.actions.DesignModeAction "designModeAction" <-- FormManager2
					Netbeans_v1.0.x.org.netbeans.modules.form.compat2.layouts.DesignLayout.ConstraintsDescription "dragConstraints" <-- FormManager2
					Netbeans_v1.0.x.org.netbeans.modules.form.compat2.layouts.DesignLayout "dragLayout" <-- FormManager2
					Netbeans_v1.0.x.java.awt.Point "dragPoint" <-- FormManager2
					Netbeans_v1.0.x.java.lang.String "encoding" <-- FormManager2
					EventsManager "eventsManager" <-- FormManager2
					Netbeans_v1.0.x.java.awt.Container "formContainer" <-- FormManager2
					Netbeans_v1.0.x.java.lang.Object "OPEN_FORM_LOCK" <-- FormEditorSupport
					Netbeans_v1.0.x.java.beans.PropertyChangeListener "editorFocusChangeListener" <-- FormEditorSupport
					JavaPrimitiveTypes.boolean "formLoaded" <-- FormEditorSupport
					FormManager2 "formManager" <-- FormEditorSupport
					Netbeans_v1.0.x.java.lang.Object "OPEN_FORM_LOCK" <-- FormDataObject
					JavaPrimitiveTypes.boolean "componentRefRegistered" <-- FormDataObject
					Netbeans_v1.0.x.java.util.ResourceBundle "formBundle" <-- FormDataObject
					FormEditorSupport "formEditor" <-- FormDataObject
					Netbeans_v1.0.x.org.openide.loaders.FileEntry "formEntry" <-- FormDataObject
					JavaPrimitiveTypes.boolean "modifiedInit" <-- FormDataObject
					JavaPrimitiveTypes.long "serialVersionUID" <-- FormDataObject
					JavaPrimitiveTypes.boolean "templateInit" <-- FormDataObject
					Netbeans_v1.0.x.java.lang.String "FORM_EXTENSION" <-- FormDataLoader
					JavaPrimitiveTypes.long "serialVersionUID" <-- FormDataLoader
					FormDataObject "formObject" <-- FormEditorSupport
					RADComponentNode "formRootNode" <-- FormEditorSupport
					JavaPrimitiveTypes.boolean "listenerRegistered" <-- FormEditorSupport
					Netbeans_v1.0.x.java.util.Hashtable "openForms" <-- FormEditorSupport
					JavaPrimitiveTypes.boolean "openOnEditing" <-- FormEditorSupport
					Netbeans_v1.0.x.java.util.ArrayList "managers" <-- PersistenceManager
					PersistenceManager "saveManager" <-- FormEditorSupport
					Netbeans_v1.0.x.java.beans.PropertyChangeListener "settingsListener" <-- FormEditorSupport
					Netbeans_v1.0.x.org.openide.awt.UndoRedo.Manager "undoManager" <-- FormEditorSupport
					Netbeans_v1.0.x.java.beans.PropertyChangeListener "workspacesListener" <-- FormEditorSupport
					Netbeans_v1.0.x.javax.swing.JPopupMenu "displayedPopup" <-- FormTopComponent
					FormManager2 "formManager" <-- FormTopComponent
					FormDataObject "formObject" <-- FormTopComponent
					JavaPrimitiveTypes.long "serialVersionUID" <-- FormTopComponent
					FormEditorSupport "formEditorSupport" <-- FormManager2
					Netbeans_v1.0.x.java.util.ArrayList "formListeners" <-- FormManager2
					FormDataObject "formObject" <-- FormManager2
					FormTopComponent "formWindow" <-- FormManager2
					JavaPrimitiveTypes.boolean "ignoreMouse" <-- FormManager2
					JavaPrimitiveTypes.boolean "initialized" <-- FormManager2
					Netbeans_v1.0.x.org.openide.nodes.Node "lastSelectedNodes 0..*" <-- FormManager2
					Netbeans_v1.0.x.java.util.HashMap "constraints" <-- RADVisualComponent
					Netbeans_v1.0.x.java.awt.Container "containerDelegate" <-- RADVisualContainer
					Netbeans_v1.0.x.org.netbeans.modules.form.compat2.layouts.DesignLayout "designLayout" <-- RADVisualContainer
					RADVisualContainer "container" <-- RADLayoutNode
					Netbeans_v1.0.x.java.text.MessageFormat "nameFormat" <-- RADLayoutNode
					RADLayoutNode "layoutNode" <-- RADVisualContainer
					Netbeans_v1.0.x.org.netbeans.modules.form.compat2.layouts.DesignLayout "previousLayout" <-- RADVisualContainer
					Netbeans_v1.0.x.java.util.ArrayList "subComponents" <-- RADVisualContainer
					RADVisualContainer "parent" <-- RADVisualComponent
					Netbeans_v1.0.x.org.openide.nodes.Node.PropertySet "visualPropertySet 0..*" <-- RADVisualComponent
					MoveListener "mListener" <-- FormManager2
					ManagerMouseAdapter "mma" <-- FormManager2
					JavaPrimitiveTypes.int "mode" <-- FormManager2
					Netbeans_v1.0.x.java.awt.event.MouseMotionListener "mouseMotionListener" <-- MouseMotionProcessor
					Netbeans_v1.0.x.java.awt.Component "translateParent" <-- MouseMotionProcessor
					MouseMotionProcessor "mouseMotionProcessor" <-- FormManager2
					Netbeans_v1.0.x.java.awt.event.MouseListener "mouseListener" <-- MouseProcessor
					Netbeans_v1.0.x.java.awt.Component "translateParent" <-- MouseProcessor
					MouseProcessor "mouseProcessor" <-- FormManager2
					JavaPrimitiveTypes.boolean "movingDragMode" <-- FormManager2
					JavaPrimitiveTypes.boolean "movingMode" <-- FormManager2
					RADVisualComponent "movingRADVisualComponent" <-- FormManager2
					FormManager2 "manager" <-- NonVisualChildren
					NonVisualChildren "nonVisChildren" <-- FormManager2
					Netbeans_v1.0.x.java.util.ArrayList "nonVisList" <-- FormManager2
					ComponentContainer "nonVisualsContainer" <-- FormManager2
					Netbeans_v1.0.x.org.netbeans.modules.form.compat2.layouts.DesignLayout.ConstraintsDescription "originalDragConstraints" <-- FormManager2
					Netbeans_v1.0.x.java.awt.Point "originalDragPoint" <-- FormManager2
					Netbeans_v1.0.x.java.awt.Point "originalHotSpot" <-- FormManager2
					Netbeans_v1.0.x.java.awt.Point "originalLocation" <-- FormManager2
					JavaPrimitiveTypes.boolean "outerMovingMode" <-- FormManager2
					Netbeans_v1.0.x.org.netbeans.modules.form.palette.ComponentPalette "palette" <-- FormManager2
					RADVisualContainer "parentRADContainer" <-- FormManager2
					ResizeListener "rListener" <-- FormManager2
					Netbeans_v1.0.x.org.netbeans.modules.form.forminfo.FormInfo "formInfo" <-- RADForm
					RADComponent "topRADComponent" <-- RADForm
					RADForm "radForm" <-- FormManager2
					Netbeans_v1.0.x.java.util.HashMap "radToSelection" <-- FormManager2
					JavaPrimitiveTypes.boolean "resizingMode" <-- FormManager2
					JavaPrimitiveTypes.int "savedDesignMode" <-- FormManager2
					Netbeans_v1.0.x.java.awt.Rectangle "savedFormBounds" <-- FormManager2
					JavaPrimitiveTypes.boolean "testMode" <-- FormManager2
					FormManager2 "manager" <-- VariablesPool
					Netbeans_v1.0.x.java.util.HashMap "nameSpace" <-- VariablesPool
					Netbeans_v1.0.x.java.util.HashMap "nameSpaceFixed" <-- VariablesPool
					Netbeans_v1.0.x.java.util.HashMap "usedIndexes" <-- VariablesPool
					Netbeans_v1.0.x.java.util.ArrayList "variables" <-- VariablesPool
					Netbeans_v1.0.x.java.lang.String "className" <-- Variable
					Netbeans_v1.0.x.java.lang.String "variableName" <-- Variable
					VariablesPool "variablesPool" <-- FormManager2
					Netbeans_v1.0.x.java.util.HashMap "visualToRAD" <-- FormManager2
					JavaPrimitiveTypes.long "serialVersionUID" <-- FormEvent
					Netbeans_v1.0.x.java.lang.Object "newValue" <-- FormPropertyEvent
					Netbeans_v1.0.x.java.lang.Object "oldValue" <-- FormPropertyEvent
					Netbeans_v1.0.x.java.lang.String "propertyName" <-- FormPropertyEvent
					JavaPrimitiveTypes.long "serialVersionUID" <-- FormPropertyEvent
					EventHandler "event" <-- FormEventEvent
					JavaPrimitiveTypes.long "serialVersionUID" <-- FormEventEvent
					JavaPrimitiveTypes.int "CANCEL" <-- ConnectionWizard1
					JavaPrimitiveTypes.int "NEXT" <-- ConnectionWizard1
					Netbeans_v1.0.x.javax.swing.JPanel "buttonsPanel" <-- ConnectionWizard1
					Netbeans_v1.0.x.javax.swing.JButton "cancelButton" <-- ConnectionWizard1
					Netbeans_v1.0.x.javax.swing.JPanel "eventHandlerPanel" <-- ConnectionWizard1
					Netbeans_v1.0.x.javax.swing.JComboBox "eventNameCombo" <-- ConnectionWizard1
					Netbeans_v1.0.x.javax.swing.JLabel "eventNameLabel" <-- ConnectionWizard1
					JavaPrimitiveTypes.boolean "eventNameModified" <-- ConnectionWizard1
					Netbeans_v1.0.x.javax.swing.JLabel "eventSelectLabel" <-- ConnectionWizard1
					Netbeans_v1.0.x.javax.swing.JPanel "eventSelectLabelPanel" <-- ConnectionWizard1
					Netbeans_v1.0.x.javax.swing.JScrollPane "eventSelectScroll" <-- ConnectionWizard1
					Netbeans_v1.0.x.javax.swing.JTree "eventSelectTree" <-- ConnectionWizard1
					Netbeans_v1.0.x.javax.swing.JPanel "insidePanel" <-- ConnectionWizard1
					Netbeans_v1.0.x.javax.swing.JButton "nextButton" <-- ConnectionWizard1
					JavaPrimitiveTypes.int "returnStatus" <-- ConnectionWizard1
					Netbeans_v1.0.x.javax.swing.JPanel "rightButtonsPanel" <-- ConnectionWizard1
					Event "selectedEvent" <-- ConnectionWizard1
					JavaPrimitiveTypes.long "serialVersionUID" <-- ConnectionWizard1
					RADComponent "sourceComponent" <-- ConnectionWizard1
					Netbeans_v1.0.x.javax.swing.JLabel "sourceComponentName" <-- ConnectionWizard1
					Netbeans_v1.0.x.javax.swing.JPanel "sourceInfoPanel" <-- ConnectionWizard1
					Netbeans_v1.0.x.javax.swing.JLabel "sourceNameLabel" <-- ConnectionWizard1
					Netbeans_v1.0.x.javax.swing.JPanel "sourceNamePanel" <-- ConnectionWizard1
					Netbeans_v1.0.x.javax.swing.JPanel "sourcePanel" <-- ConnectionWizard1
					Netbeans_v1.0.x.java.lang.String "storedEventName" <-- ConnectionWizard1
					Event "event" <-- EventNode
					Netbeans_v1.0.x.javax.swing.tree.TreeNode "parent" <-- EventNode
					EventSet "eventSet" <-- EventSetNode
					Netbeans_v1.0.x.javax.swing.tree.TreeNode "parent" <-- EventSetNode
					Netbeans_v1.0.x.java.util.Vector "subNodes" <-- EventSetNode
					JavaPrimitiveTypes.int "CANCEL" <-- ConnectionWizard2
					JavaPrimitiveTypes.int "CODE_TYPE" <-- ConnectionWizard2
					JavaPrimitiveTypes.int "METHOD_TYPE" <-- ConnectionWizard2
					JavaPrimitiveTypes.int "NEXT" <-- ConnectionWizard2
					JavaPrimitiveTypes.int "PREVIOUS" <-- ConnectionWizard2
					JavaPrimitiveTypes.int "PROPERTY_TYPE" <-- ConnectionWizard2
					Netbeans_v1.0.x.javax.swing.JList "actionList" <-- ConnectionWizard2
					Netbeans_v1.0.x.javax.swing.JScrollPane "actionPanel" <-- ConnectionWizard2
					Netbeans_v1.0.x.javax.swing.JPanel "actionTypePanel" <-- ConnectionWizard2
					Netbeans_v1.0.x.javax.swing.JPanel "buttonsPanel" <-- ConnectionWizard2
					Netbeans_v1.0.x.javax.swing.JButton "cancelButton" <-- ConnectionWizard2
					Netbeans_v1.0.x.javax.swing.JRadioButton "codeButton" <-- ConnectionWizard2
					Netbeans_v1.0.x.javax.swing.JPanel "insidePanel" <-- ConnectionWizard2
					Netbeans_v1.0.x.javax.swing.JPanel "leftButtonsPanel" <-- ConnectionWizard2
					Netbeans_v1.0.x.javax.swing.JRadioButton "methodButton" <-- ConnectionWizard2
					Netbeans_v1.0.x.java.beans.MethodDescriptor "methodDescriptors 0..*" <-- ConnectionWizard2
					Netbeans_v1.0.x.java.lang.Object "methodListData 0..*" <-- ConnectionWizard2
					Netbeans_v1.0.x.javax.swing.JButton "nextButton" <-- ConnectionWizard2
					Netbeans_v1.0.x.javax.swing.JButton "previousButton" <-- ConnectionWizard2
					Netbeans_v1.0.x.java.beans.PropertyDescriptor "propDescriptors 0..*" <-- ConnectionWizard2
					Netbeans_v1.0.x.javax.swing.JRadioButton "propertyButton" <-- ConnectionWizard2
					Netbeans_v1.0.x.java.lang.Object "propertyListData 0..*" <-- ConnectionWizard2
					JavaPrimitiveTypes.int "returnStatus" <-- ConnectionWizard2
					Netbeans_v1.0.x.javax.swing.JPanel "rightButtonsPanel" <-- ConnectionWizard2
					JavaPrimitiveTypes.long "serialVersionUID" <-- ConnectionWizard2
					Netbeans_v1.0.x.javax.swing.JPanel "targerInfoPanel" <-- ConnectionWizard2
					RADComponent "targetComponent" <-- ConnectionWizard2
					Netbeans_v1.0.x.javax.swing.JLabel "targetComponentName" <-- ConnectionWizard2
					Netbeans_v1.0.x.javax.swing.JLabel "targetNameLabel" <-- ConnectionWizard2
					Netbeans_v1.0.x.javax.swing.JPanel "targetNamePanel" <-- ConnectionWizard2
					Netbeans_v1.0.x.javax.swing.JPanel "targetPanel" <-- ConnectionWizard2
					JavaPrimitiveTypes.int "CANCEL" <-- ConnectionWizard3
					JavaPrimitiveTypes.int "NEXT" <-- ConnectionWizard3
					JavaPrimitiveTypes.int "PREVIOUS" <-- ConnectionWizard3
					Netbeans_v1.0.x.javax.swing.JPanel "buttonsPanel" <-- ConnectionWizard3
					Netbeans_v1.0.x.javax.swing.JButton "cancelButton" <-- ConnectionWizard3
					Netbeans_v1.0.x.javax.swing.JPanel "insidePanel" <-- ConnectionWizard3
					Netbeans_v1.0.x.javax.swing.JPanel "leftButtonsPanel" <-- ConnectionWizard3
					FormManager2 "manager" <-- ConnectionWizard3
					Netbeans_v1.0.x.javax.swing.JButton "nextButton" <-- ConnectionWizard3
					Netbeans_v1.0.x.javax.swing.JTabbedPane "parameterTabs" <-- ConnectionWizard3
					Netbeans_v1.0.x.java.lang.Class "parameters 0..*" <-- ConnectionWizard3
					Netbeans_v1.0.x.javax.swing.JRadioButton "beanButton" <-- ParametersPicker
					Netbeans_v1.0.x.javax.swing.JComboBox "beanCombo" <-- ParametersPicker
					Netbeans_v1.0.x.javax.swing.DefaultComboBoxModel "beanComboModel" <-- ParametersPicker
					Netbeans_v1.0.x.java.util.ArrayList "beansList" <-- ParametersPicker
					Netbeans_v1.0.x.javax.swing.JEditorPane "codeArea" <-- ParametersPicker
					Netbeans_v1.0.x.javax.swing.JRadioButton "codeButton" <-- ParametersPicker
					Netbeans_v1.0.x.javax.swing.JScrollPane "codeScrollPane" <-- ParametersPicker
					JavaPrimitiveTypes.boolean "currentFilledState" <-- ParametersPicker
					Netbeans_v1.0.x.java.util.ArrayList "listeners" <-- ParametersPicker
					FormManager2 "manager" <-- ParametersPicker
					Netbeans_v1.0.x.javax.swing.JRadioButton "methodButton" <-- ParametersPicker
					Netbeans_v1.0.x.javax.swing.JButton "methodDetailsButton" <-- ParametersPicker
					Netbeans_v1.0.x.javax.swing.JLabel "methodLabel" <-- ParametersPicker
					JavaPrimitiveTypes.int "CANCEL" <-- MethodPicker
					JavaPrimitiveTypes.int "OK" <-- MethodPicker
					Netbeans_v1.0.x.javax.swing.JPanel "buttonsPanel" <-- MethodPicker
					Netbeans_v1.0.x.javax.swing.JButton "cancelButton" <-- MethodPicker
					Netbeans_v1.0.x.javax.swing.JLabel "componentLabel" <-- MethodPicker
					RADComponent "components 0..*" <-- MethodPicker
					Netbeans_v1.0.x.javax.swing.JComboBox "componentsCombo" <-- MethodPicker
					Netbeans_v1.0.x.java.beans.MethodDescriptor "descriptors 0..*" <-- MethodPicker
					Netbeans_v1.0.x.javax.swing.JPanel "insidePanel" <-- MethodPicker
					Netbeans_v1.0.x.javax.swing.JPanel "jPanel1" <-- MethodPicker
					Netbeans_v1.0.x.javax.swing.JPanel "leftButtonsPanel" <-- MethodPicker
					FormManager2 "manager" <-- MethodPicker
					Netbeans_v1.0.x.javax.swing.JList "methodList" <-- MethodPicker
					Netbeans_v1.0.x.javax.swing.JButton "okButton" <-- MethodPicker
					Netbeans_v1.0.x.javax.swing.JButton "parametersButton" <-- MethodPicker
					Netbeans_v1.0.x.javax.swing.JScrollPane "propertiesScrollPane" <-- MethodPicker
					Netbeans_v1.0.x.java.lang.Class "requiredType" <-- MethodPicker
					JavaPrimitiveTypes.int "returnStatus" <-- MethodPicker
					Netbeans_v1.0.x.javax.swing.JPanel "rightButtonsPanel" <-- MethodPicker
					RADComponent "selectedComponent" <-- MethodPicker
					Netbeans_v1.0.x.java.beans.MethodDescriptor "selectedMethod" <-- MethodPicker
					JavaPrimitiveTypes.long "serialVersionUID" <-- MethodPicker
					MethodPicker "methodPicker" <-- ParametersPicker
					Netbeans_v1.0.x.javax.swing.JRadioButton "propertyButton" <-- ParametersPicker
					Netbeans_v1.0.x.javax.swing.JButton "propertyDetailsButton" <-- ParametersPicker
					Netbeans_v1.0.x.javax.swing.JLabel "propertyLabel" <-- ParametersPicker
					JavaPrimitiveTypes.int "CANCEL" <-- PropertyPicker
					JavaPrimitiveTypes.int "OK" <-- PropertyPicker
					Netbeans_v1.0.x.javax.swing.JPanel "buttonsPanel" <-- PropertyPicker
					Netbeans_v1.0.x.javax.swing.JButton "cancelButton" <-- PropertyPicker
					Netbeans_v1.0.x.javax.swing.JLabel "componentLabel" <-- PropertyPicker
					RADComponent "components 0..*" <-- PropertyPicker
					Netbeans_v1.0.x.javax.swing.JComboBox "componentsCombo" <-- PropertyPicker
					Netbeans_v1.0.x.java.beans.PropertyDescriptor "descriptors 0..*" <-- PropertyPicker
					Netbeans_v1.0.x.javax.swing.JPanel "insidePanel" <-- PropertyPicker
					Netbeans_v1.0.x.javax.swing.JPanel "jPanel1" <-- PropertyPicker
					Netbeans_v1.0.x.javax.swing.JPanel "leftButtonsPanel" <-- PropertyPicker
					FormManager2 "manager" <-- PropertyPicker
					Netbeans_v1.0.x.javax.swing.JButton "okButton" <-- PropertyPicker
					Netbeans_v1.0.x.javax.swing.JScrollPane "propertiesScrollPane" <-- PropertyPicker
					Netbeans_v1.0.x.javax.swing.JList "propertyList" <-- PropertyPicker
					Netbeans_v1.0.x.java.lang.Class "requiredType" <-- PropertyPicker
					JavaPrimitiveTypes.int "returnStatus" <-- PropertyPicker
					Netbeans_v1.0.x.javax.swing.JPanel "rightButtonsPanel" <-- PropertyPicker
					RADComponent "selectedComponent" <-- PropertyPicker
					Netbeans_v1.0.x.java.beans.PropertyDescriptor "selectedProperty" <-- PropertyPicker
					JavaPrimitiveTypes.long "serialVersionUID" <-- PropertyPicker
					PropertyPicker "propertyPicker" <-- ParametersPicker
					Netbeans_v1.0.x.java.lang.Class "requiredType" <-- ParametersPicker
					RADComponent "selectedComponent" <-- ParametersPicker
					Netbeans_v1.0.x.java.beans.MethodDescriptor "selectedMethod" <-- ParametersPicker
					Netbeans_v1.0.x.java.beans.PropertyDescriptor "selectedProperty" <-- ParametersPicker
					Netbeans_v1.0.x.java.lang.String "selectedPropertyText" <-- ParametersPicker
					JavaPrimitiveTypes.long "serialVersionUID" <-- ParametersPicker
					RADComponent "sourceComponent" <-- ParametersPicker
					Netbeans_v1.0.x.javax.swing.JRadioButton "valueButton" <-- ParametersPicker
					Netbeans_v1.0.x.javax.swing.JTextField "valueField" <-- ParametersPicker
					Netbeans_v1.0.x.java.lang.Object "IGNORED_VALUE" <-- FormDesignValue
					JavaPrimitiveTypes.long "serialVersionUID" <-- FormDesignValue
					JavaPrimitiveTypes.long "serialVersionUID" <-- Listener
					JavaPrimitiveTypes.int "TYPE_BEAN" <-- RADConnectionDesignValue
					JavaPrimitiveTypes.int "TYPE_CODE" <-- RADConnectionDesignValue
					JavaPrimitiveTypes.int "TYPE_METHOD" <-- RADConnectionDesignValue
					JavaPrimitiveTypes.int "TYPE_PROPERTY" <-- RADConnectionDesignValue
					JavaPrimitiveTypes.int "TYPE_VALUE" <-- RADConnectionDesignValue
					FormManager2 "formManager" <-- RADConnectionDesignValue
					Netbeans_v1.0.x.java.beans.MethodDescriptor "method" <-- RADConnectionDesignValue
					Netbeans_v1.0.x.java.lang.String "methodName" <-- RADConnectionDesignValue
					JavaPrimitiveTypes.boolean "needsInit" <-- RADConnectionDesignValue
					Netbeans_v1.0.x.java.beans.PropertyDescriptor "property" <-- RADConnectionDesignValue
					Netbeans_v1.0.x.java.lang.String "propertyName" <-- RADConnectionDesignValue
					RADComponent "radComponent" <-- RADConnectionDesignValue
					Netbeans_v1.0.x.java.lang.String "radComponentName" <-- RADConnectionDesignValue
					Netbeans_v1.0.x.java.lang.String "requiredTypeName" <-- RADConnectionDesignValue
					JavaPrimitiveTypes.long "serialVersionUID" <-- RADConnectionDesignValue
					JavaPrimitiveTypes.int "type" <-- RADConnectionDesignValue
					Netbeans_v1.0.x.java.lang.String "userCode" <-- RADConnectionDesignValue
					Netbeans_v1.0.x.java.lang.String "value" <-- RADConnectionDesignValue
					ParametersPicker "pickers 0..*" <-- ConnectionWizard3
					Netbeans_v1.0.x.javax.swing.JLabel "previewLabel" <-- ConnectionWizard3
					Netbeans_v1.0.x.javax.swing.JButton "previousButton" <-- ConnectionWizard3
					JavaPrimitiveTypes.int "returnStatus" <-- ConnectionWizard3
					Netbeans_v1.0.x.javax.swing.JPanel "rightButtonsPanel" <-- ConnectionWizard3
					JavaPrimitiveTypes.long "serialVersionUID" <-- ConnectionWizard3
					RADComponent "sourceComponent" <-- ConnectionWizard3
					Netbeans_v1.0.x.java.lang.String "AUX_CODE_GENERATION" <-- JavaCodeGenerator
					Netbeans_v1.0.x.java.lang.String "AUX_CREATE_CODE_CUSTOM" <-- JavaCodeGenerator
					Netbeans_v1.0.x.java.lang.String "AUX_CREATE_CODE_POST" <-- JavaCodeGenerator
					Netbeans_v1.0.x.java.lang.String "AUX_CREATE_CODE_PRE" <-- JavaCodeGenerator
					Netbeans_v1.0.x.java.lang.String "AUX_INIT_CODE_POST" <-- JavaCodeGenerator
					Netbeans_v1.0.x.java.lang.String "AUX_INIT_CODE_PRE" <-- JavaCodeGenerator
					Netbeans_v1.0.x.java.lang.String "AUX_SERIALIZE_TO" <-- JavaCodeGenerator
					Netbeans_v1.0.x.java.lang.String "AUX_VARIABLE_MODIFIER" <-- JavaCodeGenerator
					Netbeans_v1.0.x.java.lang.String "EVT_SECTION_PREFIX" <-- JavaCodeGenerator
					Netbeans_v1.0.x.java.lang.Object "GEN_LOCK" <-- JavaCodeGenerator
					Netbeans_v1.0.x.java.lang.String "INIT_COMPONENTS_FOOTER" <-- JavaCodeGenerator
					Netbeans_v1.0.x.java.lang.String "INIT_COMPONENTS_HEADER" <-- JavaCodeGenerator
					Netbeans_v1.0.x.java.lang.String "SECTION_EVENT_PREFIX" <-- JavaCodeGenerator
					Netbeans_v1.0.x.java.lang.String "SECTION_INIT_COMPONENTS" <-- JavaCodeGenerator
					Netbeans_v1.0.x.java.lang.String "SECTION_VARIABLES" <-- JavaCodeGenerator
					Netbeans_v1.0.x.java.lang.Integer "VALUE_GENERATE_CODE" <-- JavaCodeGenerator
					Netbeans_v1.0.x.java.lang.Integer "VALUE_SERIALIZE" <-- JavaCodeGenerator
					Netbeans_v1.0.x.java.lang.String "VARIABLES_FOOTER" <-- JavaCodeGenerator
					Netbeans_v1.0.x.java.lang.String "VARIABLES_HEADER" <-- JavaCodeGenerator
					JavaPrimitiveTypes.boolean "errorInitializing" <-- JavaCodeGenerator
					FormManager2 "formManager" <-- JavaCodeGenerator
					Netbeans_v1.0.x.org.netbeans.modules.java.JavaEditor.SimpleSection "initComponentsSection" <-- JavaCodeGenerator
					JavaPrimitiveTypes.boolean "initialized" <-- JavaCodeGenerator
					JCGFormListener "listener" <-- JavaCodeGenerator
					Netbeans_v1.0.x.java.lang.String "oneIndent" <-- JavaCodeGenerator
					Netbeans_v1.0.x.org.netbeans.modules.java.JavaEditor.SimpleSection "variablesSection" <-- JavaCodeGenerator
					Netbeans_v1.0.x.java.lang.String "currentIndent" <-- AWTIndentStringWriter
					Netbeans_v1.0.x.java.lang.Object "DUMMY_SEPARATOR_INSTANCE" <-- RADMenuItemComponent
					JavaPrimitiveTypes.int "MASK_AWT" <-- RADMenuItemComponent
					JavaPrimitiveTypes.int "MASK_CONTAINER" <-- RADMenuItemComponent
					JavaPrimitiveTypes.int "MASK_ROOT" <-- RADMenuItemComponent
					JavaPrimitiveTypes.int "MASK_SEPARATOR" <-- RADMenuItemComponent
					JavaPrimitiveTypes.int "MASK_SWING" <-- RADMenuItemComponent
					JavaPrimitiveTypes.int "T_CHECKBOXMENUITEM" <-- RADMenuItemComponent
					JavaPrimitiveTypes.int "T_JCHECKBOXMENUITEM" <-- RADMenuItemComponent
					JavaPrimitiveTypes.int "T_JMENU" <-- RADMenuItemComponent
					JavaPrimitiveTypes.int "T_JMENUBAR" <-- RADMenuItemComponent
					JavaPrimitiveTypes.int "T_JMENUITEM" <-- RADMenuItemComponent
					JavaPrimitiveTypes.int "T_JPOPUPMENU" <-- RADMenuItemComponent
					JavaPrimitiveTypes.int "T_JRADIOBUTTONMENUITEM" <-- RADMenuItemComponent
					JavaPrimitiveTypes.int "T_JSEPARATOR" <-- RADMenuItemComponent
					JavaPrimitiveTypes.int "T_MENU" <-- RADMenuItemComponent
					JavaPrimitiveTypes.int "T_MENUBAR" <-- RADMenuItemComponent
					JavaPrimitiveTypes.int "T_MENUITEM" <-- RADMenuItemComponent
					JavaPrimitiveTypes.int "T_POPUPMENU" <-- RADMenuItemComponent
					JavaPrimitiveTypes.int "T_SEPARATOR" <-- RADMenuItemComponent
					Netbeans_v1.0.x.java.text.MessageFormat "menuNameFormat" <-- RADMenuItemComponent
					Netbeans_v1.0.x.java.util.HashMap "menusByFM" <-- RADMenuItemComponent
					RADMenuComponent "parent" <-- RADMenuItemComponent
					JavaPrimitiveTypes.int "type" <-- RADMenuItemComponent
					Netbeans_v1.0.x.java.util.HashMap "designTimeMenus" <-- DesignTimeMenus
					Netbeans_v1.0.x.java.util.ArrayList "subComponents" <-- RADMenuComponent
					Netbeans_v1.0.x.java.util.HashMap "supportedNewMenu" <-- RADMenuComponent
					Netbeans_v1.0.x.java.lang.Class "item" <-- NewMenuType
					RADComponent "component" <-- CodeGenerateEditor
					Netbeans_v1.0.x.java.lang.String "generateName" <-- CodeGenerateEditor
					Netbeans_v1.0.x.java.lang.String "serializeName" <-- CodeGenerateEditor
				}
			}
		}
	}
}
@enduml
