@startuml
package "DrJava v20040326" as DrJava_v20040326 {
	package edu {
		package rice {
			package cs {
				package drjava {
					package model {
						package definitions {
							package reducedmodel {
								abstract class AbstractReducedModel {
									{const} PTR_CHAR: JavaPrimitiveTypes.char = #
									_cursor: Iterator
									_tokens: TokenList
									<<Create>> AbstractReducedModel()
									#_augmentCurrentGap(length : JavaPrimitiveTypes.int)
									#_augmentGapToLeft(length : JavaPrimitiveTypes.int)
									#_gapToLeft(): JavaPrimitiveTypes.boolean
									#_gapToRight(): JavaPrimitiveTypes.boolean
									_insertGap(length : JavaPrimitiveTypes.int)
									#_insertNewGap(length : JavaPrimitiveTypes.int)
									absOffset(): JavaPrimitiveTypes.int
									#current(): ReducedToken
									getBlockOffset(): JavaPrimitiveTypes.int
									#getStateAtCurrent(): ReducedModelState
									insertChar(ch : JavaPrimitiveTypes.char)
									#insertGapBetweenMultiCharBrace(length : JavaPrimitiveTypes.int)
									makeCopyCursor(): Iterator
									#moveWalkerGetState(relLocation : JavaPrimitiveTypes.int): ReducedModelState
									#next()
									#prev()
									#resetWalkerLocationToCursor()
									setBlockOffset(offset : JavaPrimitiveTypes.int)
									simpleString(): DrJava_v20040326.java.lang.String
								}
								class ReducedModelBrace {
									-_parent: ReducedModelControl
									<<Create>> ReducedModelBrace(parent : ReducedModelControl)
									-_insertBrace(text : DrJava_v20040326.java.lang.String)
									-_isCurrentBraceMatchable(): JavaPrimitiveTypes.boolean
									balanceBackward(): JavaPrimitiveTypes.int
									balanceForward(): JavaPrimitiveTypes.int
									closedBraceImmediatelyLeft(): JavaPrimitiveTypes.boolean
									delete(count : JavaPrimitiveTypes.int)
									#getDistToEnclosingBrace(braceInfo : IndentInfo)
									#getDistToEnclosingBraceCurrent(braceInfo : IndentInfo)
									insertChar(ch : JavaPrimitiveTypes.char)
									#insertGapBetweenMultiCharBrace(length : JavaPrimitiveTypes.int)
									move(count : JavaPrimitiveTypes.int)
									#moveWalkerGetState(relDistance : JavaPrimitiveTypes.int): ReducedModelState
									nextBrace(): JavaPrimitiveTypes.int
									openBraceImmediatelyLeft(): JavaPrimitiveTypes.boolean
									previousBrace(): JavaPrimitiveTypes.int
									#resetWalkerLocationToCursor()
								}
								class ReducedModelComment {
									_walker: Iterator
									<<Create>> ReducedModelComment()
									-_checkPreviousInsertBackSlash()
									-_checkPreviousInsertCommentChar(special : DrJava_v20040326.java.lang.String)
									-_checkPreviousInsertSpecial(special : DrJava_v20040326.java.lang.String)
									-_getDistToPreviousNewline(copyCursor : Iterator): JavaPrimitiveTypes.int
									-_getQuoteType(quote : DrJava_v20040326.java.lang.String): DrJava_v20040326.java.lang.String
									-_insertNewEndOfLine()
									-_insertNewQuote(quote : DrJava_v20040326.java.lang.String)
									-_updateBasedOnCurrentState()
									delete(count : JavaPrimitiveTypes.int)
									getDistToCurrentBraceNewline(braceInfo : IndentInfo)
									getDistToIndentNewline(braceInfo : IndentInfo)
									getDistToNextNewline(): JavaPrimitiveTypes.int
									getDistToPreviousNewline(braceInfo : IndentInfo)
									getDistToPreviousNewline(relLoc : JavaPrimitiveTypes.int): JavaPrimitiveTypes.int
									insertChar(ch : JavaPrimitiveTypes.char)
									#insertGapBetweenMultiCharBrace(length : JavaPrimitiveTypes.int)
									insertNewline()
									insertQuote(quote : DrJava_v20040326.java.lang.String)
									-insertSpecial(special : DrJava_v20040326.java.lang.String)
									move(count : JavaPrimitiveTypes.int)
									#moveWalkerGetState(relLocation : JavaPrimitiveTypes.int): ReducedModelState
									#resetWalkerLocationToCursor()
								}
								ReducedModelStates <|.. AbstractReducedModel
								ReducedModelState <|-- Free
								ReducedModelStates <|.. ReducedModelState
								ReducedModelStates <|.. ReducedToken
								ReducedModelState <|-- InsideBlockComment
								ReducedModelState <|-- InsideDoubleQuote
								ReducedModelState <|-- InsideLineComment
								ReducedModelState <|-- InsideSingleQuote
								ReducedModelState <|-- Stutter
								AbstractReducedModel <|-- ReducedModelBrace
								BraceReduction <|.. ReducedModelControl
								AbstractReducedModel <|-- ReducedModelComment
								ReducedModelState "_state" <-- ReducedToken
								ReducedToken "_item" <-- Node
								Node "_point" <-- Iterator
								JavaPrimitiveTypes.int "_pos" <-- Iterator
								JavaPrimitiveTypes.int "_offset" <-- Iterator
								Free "FREE" <-- ReducedModelStates
								InsideBlockComment "INSIDE_BLOCK_COMMENT" <-- ReducedModelStates
								InsideDoubleQuote "INSIDE_DOUBLE_QUOTE" <-- ReducedModelStates
								InsideLineComment "INSIDE_LINE_COMMENT" <-- ReducedModelStates
								InsideSingleQuote "INSIDE_SINGLE_QUOTE" <-- ReducedModelStates
								Stutter "STUTTER" <-- ReducedModelStates
								JavaPrimitiveTypes.char "PTR_CHAR" <-- AbstractReducedModel
								Iterator "_cursor" <-- AbstractReducedModel
								TokenList "_tokens" <-- AbstractReducedModel
								JavaPrimitiveTypes.int "COMMENTED" <-- HighlightStatus
								JavaPrimitiveTypes.int "DOUBLE_QUOTED" <-- HighlightStatus
								JavaPrimitiveTypes.int "KEYWORD" <-- HighlightStatus
								JavaPrimitiveTypes.int "NORMAL" <-- HighlightStatus
								JavaPrimitiveTypes.int "NUMBER" <-- HighlightStatus
								JavaPrimitiveTypes.int "SINGLE_QUOTED" <-- HighlightStatus
								JavaPrimitiveTypes.int "TYPE" <-- HighlightStatus
								JavaPrimitiveTypes.int "_length" <-- HighlightStatus
								JavaPrimitiveTypes.int "_location" <-- HighlightStatus
								JavaPrimitiveTypes.int "_state" <-- HighlightStatus
								DrJava_v20040326.java.lang.String "braceType" <-- IndentInfo
								DrJava_v20040326.java.lang.String "braceTypeCurrent" <-- IndentInfo
								JavaPrimitiveTypes.int "distToBrace" <-- IndentInfo
								JavaPrimitiveTypes.int "distToBraceCurrent" <-- IndentInfo
								JavaPrimitiveTypes.int "distToNewline" <-- IndentInfo
								JavaPrimitiveTypes.int "distToNewlineCurrent" <-- IndentInfo
								JavaPrimitiveTypes.int "distToPrevNewline" <-- IndentInfo
								DrJava_v20040326.java.lang.String "noBrace" <-- IndentInfo
								DrJava_v20040326.java.lang.String "openBracket" <-- IndentInfo
								DrJava_v20040326.java.lang.String "openParen" <-- IndentInfo
								DrJava_v20040326.java.lang.String "openSquiggly" <-- IndentInfo
								JavaPrimitiveTypes.int "_offset" <-- ReducedModelControl
								ReducedModelBrace "rmb" <-- ReducedModelControl
								Iterator "_walker" <-- ReducedModelComment
								ReducedModelComment "rmc" <-- ReducedModelControl
								ReducedModelControl "_parent" <-- ReducedModelBrace
							}
						}
					}
				}
			}
		}
	}
}
@enduml
