@startuml
package dpd_jdt {
	package Abstractfactory {
		package non_abstract_factory {
			class TokenEntry {
				{const} EOF: TokenEntry
				-{static} TokenCount: JavaPrimitiveTypes.int
				-{const} Tokens: java.util.Map
				-beginLine: JavaPrimitiveTypes.int
				-hashCode: JavaPrimitiveTypes.int
				-identifier: JavaPrimitiveTypes.int
				-index: JavaPrimitiveTypes.int
				-tokenSrcID: java.lang.String
				-<<Create>> TokenEntry()
				<<Create>> TokenEntry(image : java.lang.String, tokenSrcID : java.lang.String, beginLine : JavaPrimitiveTypes.int)
				{static} clearImages()
				compareTo(o : java.lang.Object): JavaPrimitiveTypes.int
				equals(o : java.lang.Object): JavaPrimitiveTypes.boolean
				getBeginLine(): JavaPrimitiveTypes.int
				{static} getEOF(): TokenEntry
				getIdentifier(): JavaPrimitiveTypes.int
				getIndex(): JavaPrimitiveTypes.int
				getTokenSrcID(): java.lang.String
				hashCode(): JavaPrimitiveTypes.int
				setHashCode(hashCode : JavaPrimitiveTypes.int)
			}
		}
	}
	java.lang.Comparable <|.. Abstractfactory.non_abstract_factory.TokenEntry
	JavaPrimitiveTypes.int "TokenCount" <-- Abstractfactory.non_abstract_factory.TokenEntry
	java.util.Map "Tokens" <-- Abstractfactory.non_abstract_factory.TokenEntry
	JavaPrimitiveTypes.int "beginLine" <-- Abstractfactory.non_abstract_factory.TokenEntry
	JavaPrimitiveTypes.int "hashCode" <-- Abstractfactory.non_abstract_factory.TokenEntry
	JavaPrimitiveTypes.int "identifier" <-- Abstractfactory.non_abstract_factory.TokenEntry
	JavaPrimitiveTypes.int "index" <-- Abstractfactory.non_abstract_factory.TokenEntry
	java.lang.String "tokenSrcID" <-- Abstractfactory.non_abstract_factory.TokenEntry
}
@enduml
