@startuml
package dpd_jdt {
	package Abstractfactory {
		package non_abstract_factory {
			'The package selector dialog box
			'@author    Chris Seguin
			class PackageSelectorDialog {
				-buttons: ButtonPanel
				-selection: PackageSelectorArea
				-summary: PackageSummary
				'Constructor for the PackageSelectorDialog object
				'@param parent  the parent dialog rame
				<<Create>> PackageSelectorDialog(parent : javax.swing.JFrame)
				'Selects the package when the user presses OK
				'@param evt  the action event
				actionPerformed(evt : java.awt.event.ActionEvent)
				'Gets the summary that has been selected
				'@return    the selected package summary
				getSummary(): PackageSummary
				'The main program for the PackageSelectorDialog class
				'@param args  The command line arguments
				{static} main(args : java.lang.String)
			}
		}
	}
	java.awt.event.ActionListener <|.. Abstractfactory.non_abstract_factory.PackageSelectorDialog
	javax.swing.JDialog <|-- Abstractfactory.non_abstract_factory.PackageSelectorDialog
	java.awt.event.ActionListener "listener" <-- Abstractfactory.non_abstract_factory.PackageSelectorDialog.ButtonPanel
	java.awt.Dimension "preferredSize" <-- Abstractfactory.non_abstract_factory.PackageSelectorDialog.ButtonPanel
	Abstractfactory.non_abstract_factory.PackageSelectorDialog.ButtonPanel "buttons" <-- Abstractfactory.non_abstract_factory.PackageSelectorDialog
	Abstractfactory.non_abstract_factory.PackageSelectorArea "selection" <-- Abstractfactory.non_abstract_factory.PackageSelectorDialog
	Abstractfactory.non_abstract_factory.PackageSummary "summary" <-- Abstractfactory.non_abstract_factory.PackageSelectorDialog
}
@enduml
