@startuml
package dpd_jdt {
	package Abstractfactory {
		package non_abstract_factory {
			'@class FileAction
			'@date 08-20-2001
			'@author Eric Crahen
			'@version 1.0Action that provides a smarter JFileChooser
			abstract class FileAction {
				-chooser: SmartChooser
				'Create a new action
				<<Create>> FileAction(name : java.lang.String, icon : javax.swing.Icon)
				'Create a new action
				<<Create>> FileAction(name : java.lang.String)
				'Get the JFileChooser shared among all FileActions
				#getChooser(): SmartChooser
			}
		}
	}
	javax.swing.AbstractAction <|-- Abstractfactory.non_abstract_factory.FileAction
	java.io.File "lastDirectory" <-- Abstractfactory.non_abstract_factory.FileAction.SmartChooser
	Abstractfactory.non_abstract_factory.FileAction.SmartChooser "chooser" <-- Abstractfactory.non_abstract_factory.FileAction
	java.lang.String "description" <-- Abstractfactory.non_abstract_factory.FileAction.SimpleFilter
	java.lang.String "extensions 0..*" <-- Abstractfactory.non_abstract_factory.FileAction.SimpleFilter
}
@enduml
