@startuml
package dpd_jdt {
	package Abstractfactory {
		package non_abstract_factory {
			'@interface DiagramModel
			'@date 08-20-2001
			'@author Eric Crahen
			'@version 1.0
			interface DiagramModel {
				'@param Figure
				add(figure : Figure)
				'Add a new listener to this model.
				'@param DiagramModelListener
				addDiagramDataListener(listener : DiagramModelListener)
				'Remove all figures from the model
				clear()
				'Get value associated with a Figure 
				'@param Figure 
				'@return Object
				getValue(figure : Figure): java.lang.Object
				'Get an iterator over the figures in this model
				'@return Iterator
				iterator(): java.util.Iterator
				'@param Figure
				remove(figure : Figure)
				'Remove a listener to this model.
				'@param DiagramModelListener
				removeDiagramDataListener(listener : DiagramModelListener)
				'Associate a value with a Figure 
				'@param Figure 
				'@param Object
				setValue(figure : Figure, value : java.lang.Object)
				'Get the number of Figures in this model
				size(): JavaPrimitiveTypes.int
				'Get all selected items. The items returned will be pruned by the arryas element class if any. Passing a Figure[] array would return all Figure classes & subclasses in the selection model.
				'@param Object[] - avoid allocating a new array
				'@return Object[]
				toArray(array : java.lang.Object): java.lang.Object
			}
		}
	}
	java.lang.Cloneable <|-- Abstractfactory.non_abstract_factory.Figure
	java.io.Serializable <|-- Abstractfactory.non_abstract_factory.Figure
}
@enduml
