@startuml
'Design pattern Abstract Factory
package "Netbeans v1.0.x" as Netbeans_v1.0.x {
	package org {
		package netbeans {
			package editor {
				'/** 
				' * Find management
				' * @author Miloslav Metelka
				' * @version 1.00
				' */
				'DP role: client
				class FindSupport {
					-{const} FOUND_DEFAULT: Netbeans_v1.0.x.java.lang.String = found at
					-{const} FOUND_LOCALE: Netbeans_v1.0.x.java.lang.String = find-found
					-{const} ITEMS_REPLACED_DEFAULT: Netbeans_v1.0.x.java.lang.String = items replaced
					-{const} ITEMS_REPLACED_LOCALE: Netbeans_v1.0.x.java.lang.String = find-items-replaced
					-{const} NOT_FOUND_DEFAULT: Netbeans_v1.0.x.java.lang.String = not found
					-{const} NOT_FOUND_LOCALE: Netbeans_v1.0.x.java.lang.String = find-not-found
					-{const} WRAP_END_DEFAULT: Netbeans_v1.0.x.java.lang.String = Begining of document reached. Continuing search from end.
					-{const} WRAP_END_LOCALE: Netbeans_v1.0.x.java.lang.String = find-wrap-end
					-{const} WRAP_START_DEFAULT: Netbeans_v1.0.x.java.lang.String = End of document reached. Continuing search from begining.
					-{const} WRAP_START_LOCALE: Netbeans_v1.0.x.java.lang.String = find-wrap-start
					changeSupport: WeakPropertyChangeSupport
					-findProps: Netbeans_v1.0.x.java.util.Map
					-findPropsInited: JavaPrimitiveTypes.boolean
					{static} findSupport: FindSupport
					finderCreator: FinderCreator
					-<<Create>> FindSupport()
					'/** 
					' * Add weak listener to listen to change of any property. The caller must hold the listener object in some instance variable to prevent it from being garbage collected.
					' */
					addPropertyChangeListener(l : Netbeans_v1.0.x.java.beans.PropertyChangeListener)
					addPropertyChangeListener(findPropertyName : Netbeans_v1.0.x.java.lang.String, l : Netbeans_v1.0.x.java.beans.PropertyChangeListener)
					'/** 
					' * Find the text from the caret position.
					' * @param props search properties
					' * @param oppositeDir whether search in opposite direction
					' */
					find(props : Netbeans_v1.0.x.java.util.Map, oppositeDir : JavaPrimitiveTypes.boolean): JavaPrimitiveTypes.boolean
					'/** 
					' * Find the searched expression
					' * @param startPos position from which to search. It must be inside the block.
					' * @param blockStartPos starting position of the block. It mustbe valid position greater or equal than zero. It must be lower than or equal to blockEndPos (except blockEndPos=-1).
					' * @param blockEndPos ending position of the block. It can be -1 for the endof document. It must be greater or equal than blockStartPos (except blockEndPos=-1).
					' * @param props search properties
					' * @param oppositeDir whether search in opposite direction
					' * @param displayWrap whether display messages about the wrapping
					' * @return either null when nothing was found or integer array with three membersret[0] - starting position of the found string ret[1] - ending position of the found string ret[2] - 1 or 0 when wrap was or wasn't performed in order to find the string 
					' */
					findInBlock(c : Netbeans_v1.0.x.javax.swing.text.JTextComponent, startPos : JavaPrimitiveTypes.int, blockStartPos : JavaPrimitiveTypes.int, blockEndPos : JavaPrimitiveTypes.int, props : Netbeans_v1.0.x.java.util.Map, oppositeDir : JavaPrimitiveTypes.boolean): JavaPrimitiveTypes.int
					firePropertyChange(settingName : Netbeans_v1.0.x.java.lang.String, oldValue : Netbeans_v1.0.x.java.lang.Object, newValue : Netbeans_v1.0.x.java.lang.Object)
					getBlocks(blocks : JavaPrimitiveTypes.int, doc : BaseDocument, startPos : JavaPrimitiveTypes.int, endPos : JavaPrimitiveTypes.int): JavaPrimitiveTypes.int
					'/** 
					' * Get position pairs finder depending on find properties 
					' */
					getBlocksFinder(doc : BaseDocument, props : Netbeans_v1.0.x.java.util.Map): BlocksFinder
					getDefaultFindProperties(): Netbeans_v1.0.x.java.util.Map
					getFindProperties(): Netbeans_v1.0.x.java.util.Map
					'/** 
					' * Get find property with specified name 
					' */
					getFindProperty(name : Netbeans_v1.0.x.java.lang.String): Netbeans_v1.0.x.java.lang.Object
					'/** 
					' * Get shared instance of find support 
					' */
					{static} getFindSupport(): FindSupport
					'/** 
					' * Get current finder creator 
					' */
					getFinderCreator(): FinderCreator
					'/** 
					' * Get find property without performing initialization of find properties. This is useful for example for base document when it wants to query whether it should do highlight search.
					' */
					getPropertyNoInit(name : Netbeans_v1.0.x.java.lang.String): Netbeans_v1.0.x.java.lang.Object
					'/** 
					' * Get opposite direction finder depending on find properties 
					' */
					getStringBwdFinder(doc : BaseDocument, props : Netbeans_v1.0.x.java.util.Map): StringFinder
					'/** 
					' * Get finder depending on find properties 
					' */
					getStringFinder(doc : BaseDocument, props : Netbeans_v1.0.x.java.util.Map): StringFinder
					-getValidFindProperties(props : Netbeans_v1.0.x.java.util.Map): Netbeans_v1.0.x.java.util.Map
					'/** 
					' * Get position of wrap mark for some document 
					' */
					getWrapSearchMarkPos(doc : BaseDocument): JavaPrimitiveTypes.int
					incSearch(props : Netbeans_v1.0.x.java.util.Map): JavaPrimitiveTypes.boolean
					incSearchReset()
					-isBackSearch(props : Netbeans_v1.0.x.java.util.Map, oppositeDir : JavaPrimitiveTypes.boolean): JavaPrimitiveTypes.boolean
					'/** 
					' * Add/replace properties from some other map to current find properties. If the added properties are different than the original ones, the property change is fired.
					' */
					putFindProperties(propsToAdd : Netbeans_v1.0.x.java.util.Map)
					'/** 
					' * Set find property with specified name and fire change.
					' */
					putFindProperty(name : Netbeans_v1.0.x.java.lang.String, newValue : Netbeans_v1.0.x.java.lang.Object)
					'/** 
					' * Remove listener for changes in properties 
					' */
					removePropertyChangeListener(l : Netbeans_v1.0.x.java.beans.PropertyChangeListener)
					replace(props : Netbeans_v1.0.x.java.util.Map, oppositeDir : JavaPrimitiveTypes.boolean): JavaPrimitiveTypes.boolean
					replaceAll(props : Netbeans_v1.0.x.java.util.Map)
					'/** 
					' * Set customized finder creator 
					' */
					setFinderCreator(finderCreator : FinderCreator)
					'/** 
					' * Set new position of wrap mark for some document 
					' */
					setWrapSearchMarkPos(doc : BaseDocument, pos : JavaPrimitiveTypes.int)
				}
				'DP role: abstractProduct
				interface Finder {
					find(bufferStartPos : JavaPrimitiveTypes.int, buffer : JavaPrimitiveTypes.char, offset1 : JavaPrimitiveTypes.int, offset2 : JavaPrimitiveTypes.int, reqPos : JavaPrimitiveTypes.int, limitPos : JavaPrimitiveTypes.int): JavaPrimitiveTypes.int
					isFound(): JavaPrimitiveTypes.boolean
					reset()
				}
				Netbeans_v1.0.x.javax.swing.text.AbstractDocument <|-- BaseDocument
				SettingsChangeListener <|.. BaseDocument
				Netbeans_v1.0.x.java.util.EventListener <|-- SettingsChangeListener
				Netbeans_v1.0.x.java.util.EventObject <|-- SettingsChangeEvent
				TreeMark <|-- Mark
				Netbeans_v1.0.x.javax.swing.event.ChangeListener <|.. ExtUI
				Netbeans_v1.0.x.java.beans.PropertyChangeListener <|.. ExtUI
				SettingsChangeListener <|.. ExtUI
				SettingsChangeListener <|.. Abbrev
				Netbeans_v1.0.x.java.beans.PropertyChangeListener <|.. Abbrev
				Netbeans_v1.0.x.java.beans.PropertyChangeListener <|.. StatusBar
				SettingsChangeListener <|.. StatusBar
				Netbeans_v1.0.x.java.io.Serializable <|.. Coloring
				Netbeans_v1.0.x.java.awt.event.MouseAdapter <|-- ToolTipSupport
				Netbeans_v1.0.x.java.awt.event.MouseMotionListener <|.. ToolTipSupport
				Netbeans_v1.0.x.java.awt.event.ActionListener <|.. ToolTipSupport
				Netbeans_v1.0.x.java.beans.PropertyChangeListener <|.. ToolTipSupport
				SettingsChangeListener <|.. ToolTipSupport
				AbstractFinder <|-- WordMatch
				SettingsChangeListener <|.. WordMatch
				Netbeans_v1.0.x.java.beans.PropertyChangeListener <|.. WordMatch
				Netbeans_v1.0.x.java.util.HashMap <|-- StringMap
				Netbeans_v1.0.x.javax.swing.text.Element <|.. BaseElement
				Netbeans_v1.0.x.javax.swing.text.AbstractDocument.Content <|.. DocOp
				Netbeans_v1.0.x.javax.swing.text.AbstractDocument.DefaultDocumentEvent <|-- BaseDocumentEvent
				Netbeans_v1.0.x.java.lang.String "FOUND_DEFAULT" <-- FindSupport
				Netbeans_v1.0.x.java.lang.String "FOUND_LOCALE" <-- FindSupport
				Netbeans_v1.0.x.java.lang.String "ITEMS_REPLACED_DEFAULT" <-- FindSupport
				Netbeans_v1.0.x.java.lang.String "ITEMS_REPLACED_LOCALE" <-- FindSupport
				Netbeans_v1.0.x.java.lang.String "NOT_FOUND_DEFAULT" <-- FindSupport
				Netbeans_v1.0.x.java.lang.String "NOT_FOUND_LOCALE" <-- FindSupport
				Netbeans_v1.0.x.java.lang.String "WRAP_END_DEFAULT" <-- FindSupport
				Netbeans_v1.0.x.java.lang.String "WRAP_END_LOCALE" <-- FindSupport
				Netbeans_v1.0.x.java.lang.String "WRAP_START_DEFAULT" <-- FindSupport
				Netbeans_v1.0.x.java.lang.String "WRAP_START_LOCALE" <-- FindSupport
				Netbeans_v1.0.x.java.util.ArrayList "interestNames" <-- WeakPropertyChangeSupport
				Netbeans_v1.0.x.java.util.ArrayList "listeners" <-- WeakPropertyChangeSupport
				WeakPropertyChangeSupport "changeSupport" <-- FindSupport
				Netbeans_v1.0.x.java.util.Map "findProps" <-- FindSupport
				JavaPrimitiveTypes.boolean "findPropsInited" <-- FindSupport
				Netbeans_v1.0.x.java.lang.Class "kitClass" <-- SettingsChangeEvent
				Netbeans_v1.0.x.java.lang.Object "newValue" <-- SettingsChangeEvent
				Netbeans_v1.0.x.java.lang.Object "oldValue" <-- SettingsChangeEvent
				Netbeans_v1.0.x.java.lang.String "settingName" <-- SettingsChangeEvent
				Netbeans_v1.0.x.java.lang.String "BLOCKS_FINDER_PROP" <-- BaseDocument
				Netbeans_v1.0.x.java.lang.String "FILE_NAME_PROP" <-- BaseDocument
				Netbeans_v1.0.x.java.lang.String "ID_PROP" <-- BaseDocument
				Netbeans_v1.0.x.java.lang.String "KIT_CLASS_PROP" <-- BaseDocument
				JavaPrimitiveTypes.char "LAYER_ADDED 0..*" <-- BaseDocument
				Netbeans_v1.0.x.java.lang.String "LINE_BATCH_SIZE" <-- BaseDocument
				Netbeans_v1.0.x.java.lang.String "LINE_LIMIT_PROP" <-- BaseDocument
				Netbeans_v1.0.x.java.lang.String "LS_CR" <-- BaseDocument
				Netbeans_v1.0.x.java.lang.String "LS_CRLF" <-- BaseDocument
				Netbeans_v1.0.x.java.lang.String "LS_LF" <-- BaseDocument
				JavaPrimitiveTypes.int "MAX_READ_THREADS" <-- BaseDocument
				Netbeans_v1.0.x.java.lang.String "READ_LINE_SEPARATOR_PROP" <-- BaseDocument
				Netbeans_v1.0.x.java.lang.String "STRING_BWD_FINDER_PROP" <-- BaseDocument
				Netbeans_v1.0.x.java.lang.String "STRING_FINDER_PROP" <-- BaseDocument
				Netbeans_v1.0.x.java.lang.String "UNDO_MANAGER_PROP" <-- BaseDocument
				Netbeans_v1.0.x.java.lang.String "WRAP_SEARCH_MARK_PROP" <-- BaseDocument
				Netbeans_v1.0.x.java.lang.String "WRITE_LINE_SEPARATOR_PROP" <-- BaseDocument
				Netbeans_v1.0.x.java.lang.String "WRITE_LOCK_MISSING" <-- BaseDocument
				JavaPrimitiveTypes.int "atomicDepth" <-- BaseDocument
				Netbeans_v1.0.x.javax.swing.undo.CompoundEdit "atomicEdits" <-- BaseDocument
				JavaPrimitiveTypes.boolean "insertAfter" <-- TreeMark
				JavaPrimitiveTypes.int "relLine" <-- TreeMark
				JavaPrimitiveTypes.int "relPos" <-- TreeMark
				DocMarks "docMarks" <-- Plane
				JavaPrimitiveTypes.int "markCnt" <-- Plane
				TreeMark "marks 0..*" <-- Plane
				JavaPrimitiveTypes.int "tmpInt" <-- Plane
				DocMarks "marks" <-- Mark
				JavaPrimitiveTypes.boolean "valid" <-- Mark
				JavaPrimitiveTypes.boolean "stayBOL" <-- ContextMark
				JavaPrimitiveTypes.boolean "activateLayer" <-- DrawMark
				Netbeans_v1.0.x.java.lang.ref.WeakReference "extUIRef" <-- DrawMark
				Netbeans_v1.0.x.java.lang.String "layerName" <-- DrawMark
				Netbeans_v1.0.x.java.lang.String "COMPONENT_PROPERTY" <-- ExtUI
				Netbeans_v1.0.x.java.awt.Dimension "NULL_DIMENSION" <-- ExtUI
				Netbeans_v1.0.x.java.awt.Insets "NULL_INSETS" <-- ExtUI
				Netbeans_v1.0.x.java.lang.String "OVERWRITE_MODE_PROPERTY" <-- ExtUI
				Netbeans_v1.0.x.java.lang.String "POPUP_MENU_PROPERTY" <-- ExtUI
				JavaPrimitiveTypes.int "SCROLL_DEFAULT" <-- ExtUI
				JavaPrimitiveTypes.int "SCROLL_FIND" <-- ExtUI
				JavaPrimitiveTypes.int "SCROLL_MOVE" <-- ExtUI
				JavaPrimitiveTypes.int "SCROLL_SMALLEST" <-- ExtUI
				JavaPrimitiveTypes.int "STYLE_CNT" <-- ExtUI
				Netbeans_v1.0.x.java.util.HashMap "abbrevMap" <-- Abbrev
				Netbeans_v1.0.x.java.lang.StringBuffer "abbrevSB" <-- Abbrev
				Acceptor "addTypedAcceptor" <-- Abbrev
				JavaPrimitiveTypes.boolean "checkDocText" <-- Abbrev
				JavaPrimitiveTypes.boolean "checkTextDelimiter" <-- Abbrev
				Acceptor "doExpandAcceptor" <-- Abbrev
				ExtUI "extUI" <-- Abbrev
				Acceptor "resetAcceptor" <-- Abbrev
				Abbrev "abbrev" <-- ExtUI
				JavaPrimitiveTypes.int "ascents 0..*" <-- ExtUI
				JavaPrimitiveTypes.int "baseLeftMargin" <-- ExtUI
				JavaPrimitiveTypes.int "charHeight" <-- ExtUI
				Netbeans_v1.0.x.java.util.Map "coloringMap" <-- ExtUI
				Netbeans_v1.0.x.javax.swing.text.JTextComponent "component" <-- ExtUI
				JavaPrimitiveTypes.int "componentID" <-- ExtUI
				Netbeans_v1.0.x.java.awt.Dimension "componentSizeIncrement" <-- ExtUI
				JavaPrimitiveTypes.int "defaultSpaceWidth" <-- ExtUI
				JavaPrimitiveTypes.boolean "active" <-- DrawLayer
				JavaPrimitiveTypes.boolean "extendEOL" <-- DrawLayer
				JavaPrimitiveTypes.boolean "extendEmptyLine" <-- DrawLayer
				Netbeans_v1.0.x.java.lang.String "name" <-- DrawLayer
				JavaPrimitiveTypes.int "nextUpdateStatusPos" <-- DrawLayer
				JavaPrimitiveTypes.boolean "updateStatusEOL" <-- DrawLayer
				JavaPrimitiveTypes.int "visibility" <-- DrawLayer
				DrawLayer "EMPTY 0..*" <-- DrawLayerList
				DrawLayer "layers 0..*" <-- DrawLayerList
				DrawLayerList "drawLayerList" <-- ExtUI
				Netbeans_v1.0.x.javax.swing.JComponent "extComponent" <-- ExtUI
				JavaPrimitiveTypes.boolean "fixedFont" <-- ExtUI
				Netbeans_v1.0.x.java.awt.event.FocusAdapter "focusL" <-- ExtUI
				JavaPrimitiveTypes.boolean "fontsInited" <-- ExtUI
				JavaPrimitiveTypes.boolean "highlightSearch" <-- ExtUI
				Netbeans_v1.0.x.java.awt.Rectangle "lastExtentBounds" <-- ExtUI
				JavaPrimitiveTypes.float "lineHeightCorrection" <-- ExtUI
				JavaPrimitiveTypes.int "lineNumberAscent" <-- ExtUI
				JavaPrimitiveTypes.int "lineNumberDigitWidth" <-- ExtUI
				JavaPrimitiveTypes.boolean "lineNumberEnabled" <-- ExtUI
				Netbeans_v1.0.x.java.awt.Insets "lineNumberMargin" <-- ExtUI
				JavaPrimitiveTypes.int "lineNumberMaxDigitCnt" <-- ExtUI
				JavaPrimitiveTypes.boolean "lineNumberVisible" <-- ExtUI
				JavaPrimitiveTypes.boolean "lineNumberVisibleSetting" <-- ExtUI
				JavaPrimitiveTypes.int "lineNumberWidth" <-- ExtUI
				BaseDocument "printDoc" <-- ExtUI
				Netbeans_v1.0.x.java.beans.PropertyChangeSupport "propertyChangeSupport" <-- ExtUI
				Netbeans_v1.0.x.java.util.Hashtable "props" <-- ExtUI
				Netbeans_v1.0.x.java.util.Map "renderingHints" <-- ExtUI
				Netbeans_v1.0.x.java.awt.Insets "scrollFindInsets" <-- ExtUI
				Netbeans_v1.0.x.java.awt.Insets "scrollJumpInsets" <-- ExtUI
				Netbeans_v1.0.x.java.beans.PropertyChangeListener "settingsListener" <-- ExtUI
				JavaPrimitiveTypes.int "spaceWidths 0..*" <-- ExtUI
				Netbeans_v1.0.x.javax.swing.border.Border "CELL_BORDER" <-- StatusBar
				Netbeans_v1.0.x.java.lang.String "CELL_MAIN" <-- StatusBar
				Netbeans_v1.0.x.java.lang.String "CELL_POSITION" <-- StatusBar
				Netbeans_v1.0.x.java.lang.String "CELL_TYPING_MODE" <-- StatusBar
				Netbeans_v1.0.x.java.lang.String "INSERT_DEFAULT" <-- StatusBar
				Netbeans_v1.0.x.java.lang.String "INSERT_LOCALE" <-- StatusBar
				Netbeans_v1.0.x.java.awt.Insets "NULL_INSETS" <-- StatusBar
				Netbeans_v1.0.x.java.lang.String "OVERWRITE_DEFAULT" <-- StatusBar
				Netbeans_v1.0.x.java.lang.String "OVERWRITE_LOCALE" <-- StatusBar
				Netbeans_v1.0.x.java.lang.String "POS_MAX_STRINGS 0..*" <-- StatusBar
				Netbeans_v1.0.x.java.awt.Color "backColor" <-- Coloring
				Netbeans_v1.0.x.java.awt.Font "font" <-- Coloring
				Netbeans_v1.0.x.java.awt.Color "foreColor" <-- Coloring
				JavaPrimitiveTypes.long "serialVersionUID" <-- Coloring
				Coloring "boldColoring" <-- StatusBar
				JavaPrimitiveTypes.int "caretDelay" <-- StatusBar
				Netbeans_v1.0.x.javax.swing.Timer "timer" <-- CaretListener
				CaretListener "caretL" <-- StatusBar
				Netbeans_v1.0.x.java.util.List "cellList" <-- StatusBar
				Coloring "coloring" <-- StatusBar
				ExtUI "extUI" <-- StatusBar
				Netbeans_v1.0.x.java.lang.String "insText" <-- StatusBar
				JavaPrimitiveTypes.boolean "overwriteModeDisplayed" <-- StatusBar
				Netbeans_v1.0.x.java.lang.String "ovrText" <-- StatusBar
				Netbeans_v1.0.x.javax.swing.JPanel "panel" <-- StatusBar
				JavaPrimitiveTypes.long "serialVersionUID" <-- StatusBar
				JavaPrimitiveTypes.boolean "visible" <-- StatusBar
				Netbeans_v1.0.x.java.awt.Dimension "maxDimension" <-- Cell
				JavaPrimitiveTypes.long "serialVersionUID" <-- Cell
				Netbeans_v1.0.x.java.lang.String "widestStrings 0..*" <-- Cell
				StatusBar "statusBar" <-- ExtUI
				JavaPrimitiveTypes.boolean "superFixedFont" <-- ExtUI
				Netbeans_v1.0.x.java.awt.Color "textLimitLineColor" <-- ExtUI
				JavaPrimitiveTypes.boolean "textLimitLineVisible" <-- ExtUI
				JavaPrimitiveTypes.int "textLimitWidth" <-- ExtUI
				Netbeans_v1.0.x.java.awt.Insets "textMargin" <-- ExtUI
				JavaPrimitiveTypes.int "DISMISS_DELAY" <-- ToolTipSupport
				JavaPrimitiveTypes.int "INITIAL_DELAY" <-- ToolTipSupport
				Netbeans_v1.0.x.java.lang.String "NO_ROOT_PANE_DEFAULT" <-- ToolTipSupport
				Netbeans_v1.0.x.java.lang.String "NO_ROOT_PANE_LOCALE" <-- ToolTipSupport
				Netbeans_v1.0.x.java.lang.String "UI_PREFIX" <-- ToolTipSupport
				Netbeans_v1.0.x.java.awt.event.ComponentAdapter "componentL" <-- ToolTipSupport
				JavaPrimitiveTypes.boolean "enabled" <-- ToolTipSupport
				Netbeans_v1.0.x.javax.swing.Timer "enterTimer" <-- ToolTipSupport
				Netbeans_v1.0.x.javax.swing.Timer "exitTimer" <-- ToolTipSupport
				ExtUI "extUI" <-- ToolTipSupport
				JavaPrimitiveTypes.int "lastMouseX" <-- ToolTipSupport
				JavaPrimitiveTypes.int "lastMouseY" <-- ToolTipSupport
				Netbeans_v1.0.x.javax.swing.JLabel "toolTip" <-- ToolTipSupport
				ToolTipSupport "toolTipSupport" <-- ExtUI
				Netbeans_v1.0.x.java.awt.Rectangle "virtualSize" <-- ExtUI
				JavaPrimitiveTypes.boolean "virtualSizeUpdated" <-- ExtUI
				JavaPrimitiveTypes.boolean "found" <-- AbstractFinder
				Netbeans_v1.0.x.java.lang.Object "NULL_DOC" <-- WordMatch
				JavaPrimitiveTypes.char "baseWord 0..*" <-- WordMatch
				ExtUI "extUI" <-- WordMatch
				JavaPrimitiveTypes.boolean "forwardSearch" <-- WordMatch
				Netbeans_v1.0.x.java.lang.String "lastWord" <-- WordMatch
				JavaPrimitiveTypes.boolean "matchCase" <-- WordMatch
				JavaPrimitiveTypes.boolean "matchOneChar" <-- WordMatch
				JavaPrimitiveTypes.int "maxSearchLen" <-- WordMatch
				Netbeans_v1.0.x.java.lang.String "previousWord" <-- WordMatch
				JavaPrimitiveTypes.boolean "realMatchCase" <-- WordMatch
				JavaPrimitiveTypes.int "searchLen" <-- WordMatch
				JavaPrimitiveTypes.boolean "smartCase" <-- WordMatch
				BaseDocument "startDoc" <-- WordMatch
				Netbeans_v1.0.x.java.util.HashMap "staticWordsDocs" <-- WordMatch
				JavaPrimitiveTypes.char "word 0..*" <-- WordMatch
				Netbeans_v1.0.x.java.util.ArrayList "wordInfoList" <-- WordMatch
				JavaPrimitiveTypes.int "wordLen" <-- WordMatch
				JavaPrimitiveTypes.int "wordsIndex" <-- WordMatch
				JavaPrimitiveTypes.long "serialVersionUID" <-- StringMap
				JavaPrimitiveTypes.char "testChars 0..*" <-- StringMap
				JavaPrimitiveTypes.int "testLen" <-- StringMap
				JavaPrimitiveTypes.int "testOffset" <-- StringMap
				StringMap "wordsMap" <-- WordMatch
				JavaPrimitiveTypes.boolean "wrapSearch" <-- WordMatch
				BaseDocument "doc" <-- WordInfo
				Netbeans_v1.0.x.javax.swing.text.Position "pos" <-- WordInfo
				Netbeans_v1.0.x.java.lang.String "word" <-- WordInfo
				WordMatch "wordMatch" <-- ExtUI
				ChainDrawMark "chain" <-- MarkChain
				ChainDrawMark "curMark" <-- MarkChain
				BaseDocument "doc" <-- MarkChain
				Netbeans_v1.0.x.java.lang.String "layerName" <-- MarkChain
				MarkChain "bookmarkChain" <-- BaseDocument
				Netbeans_v1.0.x.javax.swing.text.AbstractDocument.LeafElement "composedTextElement" <-- BaseDocument
				JavaPrimitiveTypes.boolean "debugEditor" <-- BaseDocument
				Netbeans_v1.0.x.java.lang.String "ElementNameAttribute" <-- BaseElement
				Netbeans_v1.0.x.javax.swing.text.AttributeSet "attrs" <-- BaseElement
				BaseDocument "doc" <-- BaseElement
				BaseElement "defaultRootElem" <-- BaseDocument
				DrawLayerList "drawLayerList" <-- BaseDocument
				Netbeans_v1.0.x.java.beans.PropertyChangeListener "findSupportListener" <-- BaseDocument
				Acceptor "identifierAcceptor" <-- BaseDocument
				JavaPrimitiveTypes.boolean "inited" <-- BaseDocument
				Netbeans_v1.0.x.java.lang.Class "kitClass" <-- BaseDocument
				LineRootElement "lineRootElement" <-- BaseDocument
				Netbeans_v1.0.x.javax.swing.event.EventListenerList "listenerList" <-- BaseDocument
				JavaPrimitiveTypes.boolean "modified" <-- BaseDocument
				JavaPrimitiveTypes.int "CACHE_LEN" <-- DocOp
				Netbeans_v1.0.x.java.lang.String "DOC_LEN" <-- DocOp
				JavaPrimitiveTypes.int "MARK_DISTANCE" <-- DocOp
				JavaPrimitiveTypes.int "MAX_MARK_DISTANCE" <-- DocOp
				JavaPrimitiveTypes.int "MIN_MARK_DISTANCE" <-- DocOp
				JavaPrimitiveTypes.int "SYNTAX_UPDATE_BATCH_SIZE" <-- DocOp
				Netbeans_v1.0.x.java.lang.String "WRONG_POSITION" <-- DocOp
				JavaPrimitiveTypes.int "bolPos" <-- BEOLLineFwdFinder
				JavaPrimitiveTypes.int "fwdLines" <-- BEOLLineFwdFinder
				BEOLLineFwdFinder "beolLineFwdFinder" <-- DocOp
				JavaPrimitiveTypes.int "bolPos" <-- BEOLPosFwdFinder
				JavaPrimitiveTypes.int "line" <-- BEOLPosFwdFinder
				JavaPrimitiveTypes.int "tgtPos" <-- BEOLPosFwdFinder
				BEOLPosFwdFinder "beolPosFwdFinder" <-- DocOp
				BOLBwdFinder "bolBwdFinder" <-- DocOp
				JavaPrimitiveTypes.int "MIN_FRAGMENT_BACK_OVERLAP_LEN" <-- DocCache
				JavaPrimitiveTypes.char "buffer 0..*" <-- Fragment
				JavaPrimitiveTypes.int "firstMod" <-- Fragment
				JavaPrimitiveTypes.int "fragLen" <-- Fragment
				JavaPrimitiveTypes.int "lastMod" <-- Fragment
				JavaPrimitiveTypes.boolean "modified" <-- Fragment
				JavaPrimitiveTypes.int "origLen" <-- Fragment
				JavaPrimitiveTypes.int "startPos" <-- Fragment
				JavaPrimitiveTypes.boolean "valid" <-- Fragment
				Fragment "defFrag" <-- DocCache
				JavaPrimitiveTypes.boolean "directMode" <-- DocCache
				JavaPrimitiveTypes.int "docLenDelta" <-- DocCache
				Fragment "frags 0..*" <-- DocCache
				JavaPrimitiveTypes.int "statBackOverlapCnt" <-- DocCache
				JavaPrimitiveTypes.int "statFragSetEmpty" <-- DocCache
				JavaPrimitiveTypes.int "statFragSwitchCnt" <-- DocCache
				JavaPrimitiveTypes.int "statInsert" <-- DocCache
				JavaPrimitiveTypes.int "statOverlapCnt" <-- DocCache
				JavaPrimitiveTypes.int "statRead" <-- DocCache
				JavaPrimitiveTypes.int "statReadFragCnt" <-- DocCache
				JavaPrimitiveTypes.int "statRemove" <-- DocCache
				JavaPrimitiveTypes.int "statWriteFragCnt" <-- DocCache
				JavaPrimitiveTypes.int "SAVE_BUFFER_LEN" <-- DocCacheSupport
				JavaPrimitiveTypes.int "docLen" <-- DocCacheSupport
				JavaPrimitiveTypes.long "statCharsRead" <-- DocCacheSupport
				JavaPrimitiveTypes.long "statCharsWritten" <-- DocCacheSupport
				DocCacheSupport "support" <-- DocCache
				DocCache "cache" <-- DocOp
				DocCacheSupport "cacheSupport" <-- DocOp
				BaseDocument "doc" <-- DocOp
				JavaPrimitiveTypes.int "docLen" <-- DocOp
				Mark "endMark" <-- DocOp
				EOLFwdFinder "eolFwdFinder" <-- DocOp
				StateInfo "stateInfo" <-- SyntaxMark
				SyntaxMark "eolMark" <-- DocOp
				SyntaxMark "leftUpdateMark" <-- DocOp
				JavaPrimitiveTypes.int "bol" <-- CacheEntry
				JavaPrimitiveTypes.int "eol" <-- CacheEntry
				JavaPrimitiveTypes.int "line" <-- CacheEntry
				CacheEntry "lineCache 0..*" <-- DocOp
				DocMarks "marks" <-- DocOp
				JavaPrimitiveTypes.int "tabSize" <-- PosVisColFwdFinder
				JavaPrimitiveTypes.int "visCol" <-- PosVisColFwdFinder
				PosVisColFwdFinder "posVisColFwdFinder" <-- DocOp
				JavaPrimitiveTypes.int "statCacheHit" <-- DocOp
				JavaPrimitiveTypes.int "statCacheMiss" <-- DocOp
				DocMarks "marks" <-- Renderer
				JavaPrimitiveTypes.boolean "remove" <-- SyntaxUpdateRenderer
				Netbeans_v1.0.x.java.lang.ref.WeakReference "segDocRef" <-- Slot
				JavaPrimitiveTypes.int "segLen" <-- Slot
				JavaPrimitiveTypes.int "segPos" <-- Slot
				Slot "slot" <-- SyntaxUpdateRenderer
				Syntax "syntax" <-- SyntaxUpdateRenderer
				JavaPrimitiveTypes.char "chars 0..*" <-- ModifyUndoEdit
				JavaPrimitiveTypes.int "lfCount" <-- ModifyUndoEdit
				JavaPrimitiveTypes.int "line" <-- ModifyUndoEdit
				JavaPrimitiveTypes.int "offset" <-- ModifyUndoEdit
				JavaPrimitiveTypes.boolean "remove" <-- ModifyUndoEdit
				JavaPrimitiveTypes.int "syntaxUpdateOffset" <-- ModifyUndoEdit
				Netbeans_v1.0.x.java.lang.String "text" <-- ModifyUndoEdit
				ModifyUndoEdit "undoEdit" <-- SyntaxUpdateRenderer
				SyntaxUpdateRenderer "suRenderer" <-- DocOp
				JavaPrimitiveTypes.int "tmpLine 0..*" <-- DocOp
				JavaPrimitiveTypes.int "curVisCol" <-- VisColPosFwdFinder
				ExtUI "extUI" <-- VisColPosFwdFinder
				JavaPrimitiveTypes.int "tabSize" <-- VisColPosFwdFinder
				JavaPrimitiveTypes.int "visCol" <-- VisColPosFwdFinder
				VisColPosFwdFinder "visColPosFwdFinder" <-- DocOp
				DocOp "op" <-- BaseDocument
				Netbeans_v1.0.x.java.util.ArrayList "posFreeList" <-- BaseDocument
				Netbeans_v1.0.x.java.util.ArrayList "posList" <-- BaseDocument
				Netbeans_v1.0.x.java.util.ArrayList "syntaxList" <-- BaseDocument
				JavaPrimitiveTypes.int "DOT" <-- SyntaxSupport
				JavaPrimitiveTypes.int "EMPTY_INT_ARRAY 0..*" <-- SyntaxSupport
				Acceptor "EXPRESSION_ACCEPTORS 0..*" <-- SyntaxSupport
				JavaPrimitiveTypes.int "ID" <-- SyntaxSupport
				JavaPrimitiveTypes.int "LAST_COUNT" <-- SyntaxSupport
				JavaPrimitiveTypes.char "baseLeftBrackets 0..*" <-- SyntaxSupport
				JavaPrimitiveTypes.char "baseRightBrackets 0..*" <-- SyntaxSupport
				BaseDocument "doc" <-- SyntaxSupport
				Acceptor "endVarAcceptor" <-- SyntaxSupport
				JavaPrimitiveTypes.boolean "lastMatchArrays 0..*" <-- SyntaxSupport
				JavaPrimitiveTypes.int "lastTokenArrays 0..*" <-- SyntaxSupport
				JavaPrimitiveTypes.char "leftBrackets 0..*" <-- SyntaxSupport
				JavaPrimitiveTypes.char "rightBrackets 0..*" <-- SyntaxSupport
				JavaPrimitiveTypes.int "tokenBlocks 0..*" <-- SyntaxSupport
				Acceptor "varAcceptor" <-- SyntaxSupport
				JavaPrimitiveTypes.boolean "forward" <-- GenericFinder
				JavaPrimitiveTypes.char "bracketChar" <-- BracketFinder
				JavaPrimitiveTypes.int "depth" <-- BracketFinder
				JavaPrimitiveTypes.char "matchChar" <-- BracketFinder
				JavaPrimitiveTypes.int "moveCount" <-- BracketFinder
				JavaPrimitiveTypes.char "buffer 0..*" <-- CommentOrWhitespaceTP
				JavaPrimitiveTypes.int "commentTokens 0..*" <-- CommentOrWhitespaceTP
				JavaPrimitiveTypes.boolean "nonEmpty" <-- CommentOrWhitespaceTP
				JavaPrimitiveTypes.int "tokenID" <-- TokenIDTP
				JavaPrimitiveTypes.char "bracketChars 0..*" <-- UnmatchedBracketFinder
				JavaPrimitiveTypes.int "depths 0..*" <-- UnmatchedBracketFinder
				JavaPrimitiveTypes.char "matchChars 0..*" <-- UnmatchedBracketFinder
				JavaPrimitiveTypes.int "moveCount" <-- UnmatchedBracketFinder
				SyntaxSupport "syntaxSupport" <-- BaseDocument
				JavaPrimitiveTypes.boolean "undoMergeReset" <-- BaseDocument
				Acceptor "whitespaceAcceptor" <-- BaseDocument
				JavaPrimitiveTypes.int "writeDeep" <-- BaseDocument
				JavaPrimitiveTypes.boolean "inRedo" <-- BaseDocumentEvent
				JavaPrimitiveTypes.boolean "inUndo" <-- BaseDocumentEvent
				ModifyUndoEdit "modifyUndoEdit" <-- BaseDocumentEvent
				JavaPrimitiveTypes.long "serialVersionUID" <-- BaseDocumentEvent
				Netbeans_v1.0.x.java.lang.String "drawLayerName" <-- DrawLayerChange
				Netbeans_v1.0.x.java.lang.ref.WeakReference "lineElemRef" <-- LineMark
				LineMark "startMark" <-- LineElement
				FinderCreator "finderCreator" <-- FindSupport
			}
		}
	}
}
@enduml
