@startuml
'Design pattern Adapter
package "JRefactory v2.6.24" as JRefactory_v2.6.24 {
	package org {
		package acm {
			package seguin {
				package uml {
					'/** 
					' * UMLPopupMenu
					' * @author    Chris Seguin
					' */
					'DP role: client
					class UMLPopupMenu {
						-activeComponent: JRefactory_v2.6.24.javax.swing.JPanel
						-current: UMLPackage
						-popupMenu: JRefactory_v2.6.24.javax.swing.JPopupMenu
						'/** 
						' * Constructor for the UMLPopupMenu object
						' * @param top   the package diagram
						' * @param init  the specific panel
						' */
						<<Create>> UMLPopupMenu(top : UMLPackage, init : JRefactory_v2.6.24.javax.swing.JPanel)
						'/** 
						' * Adds a feature to the FieldRefactorings attribute of the UMLPopupMenu object
						' * @param menu  The feature to be added to the FieldRefactorings attribute
						' */
						-addFieldRefactorings(menu : JRefactory_v2.6.24.javax.swing.JPopupMenu)
						'/** 
						' * Adds a feature to the MethodRefactorings attribute of the UMLPopupMenu object
						' * @param menu  The feature to be added to the MethodRefactorings attribute
						' */
						-addMethodRefactorings(menu : JRefactory_v2.6.24.javax.swing.JPopupMenu)
						'/** 
						' * Refactorings
						' * @param menu  The feature to be added to the Refactorings attribute
						' */
						#addRefactorings(menu : JRefactory_v2.6.24.javax.swing.JPopupMenu)
						'/** 
						' * Adds a feature to the TypeRefactorings attribute of the UMLPopupMenu object
						' * @param menu  The feature to be added to the TypeRefactorings attribute
						' */
						-addTypeRefactorings(menu : JRefactory_v2.6.24.javax.swing.JPopupMenu)
						'/** 
						' * Create the popup menu
						' * @return    Description of the Returned Value
						' */
						#createPopupMenu(): JRefactory_v2.6.24.javax.swing.JPopupMenu
						'/** 
						' * Get the popup menu
						' * @return    the popup menu
						' */
						getMenu(): JRefactory_v2.6.24.javax.swing.JPopupMenu
						'/** 
						' * Add in the metrics
						' * @param menu  Description of Parameter
						' * @return       the metrics
						' */
						#getMetricsMenu(menu : JRefactory_v2.6.24.javax.swing.JPopupMenu): JRefactory_v2.6.24.javax.swing.JMenuItem
						'/** 
						' * Gets the Type attribute of the UMLPopupMenu object
						' * @return    The Type value
						' */
						-getType(): UMLType
						'/** 
						' * Gets the Type attribute of the UMLPopupMenu object
						' * @return    The Type value
						' */
						-getTypeSummary(): JRefactory_v2.6.24.org.acm.seguin.summary.TypeSummary
					}
					JRefactory_v2.6.24.org.acm.seguin.uml.line.LinedPanel <|-- UMLPackage
					JRefactory_v2.6.24.org.acm.seguin.io.Saveable <|.. UMLPackage
					JRefactory_v2.6.24.org.acm.seguin.uml.line.EndPointPanel <|-- UMLType
					ISourceful <|.. UMLType
					JRefactory_v2.6.24.javax.swing.JPanel <|-- RoleHolder
					JRefactory_v2.6.24.java.awt.event.MouseAdapter <|-- UMLMouseAdapter
					UMLLine <|-- UMLField
					ISourceful <|.. UMLField
					JRefactory_v2.6.24.org.acm.seguin.uml.line.EndPointPanel <|-- UMLLine
					JRefactory_v2.6.24.javax.swing.Icon <|.. UMLIcon
					JRefactory_v2.6.24.javax.swing.JPanel "activeComponent" <-- UMLPopupMenu
					JRefactory_v2.6.24.org.acm.seguin.ide.common.ClassListPanel "classListPanel" <-- UMLPackage
					JRefactory_v2.6.24.org.acm.seguin.uml.line.SegmentedLine "currentLine" <-- UMLPackage
					JavaPrimitiveTypes.boolean "first" <-- UMLPackage
					JavaPrimitiveTypes.boolean "hasChanged" <-- UMLPackage
					JavaPrimitiveTypes.boolean "loading" <-- UMLPackage
					JRefactory_v2.6.24.java.lang.String "packageName" <-- UMLPackage
					JRefactory_v2.6.24.javax.swing.JScrollPane "scrollPane" <-- UMLPackage
					JRefactory_v2.6.24.org.acm.seguin.summary.PackageSummary "summary" <-- UMLPackage
					JavaPrimitiveTypes.int "DEFAULT" <-- UMLType
					JavaPrimitiveTypes.int "FOREIGN" <-- UMLType
					JavaPrimitiveTypes.int "SELECTED" <-- UMLType
					JavaPrimitiveTypes.int "TITLE_BORDER" <-- UMLType
					JavaPrimitiveTypes.int "borderWidth" <-- UMLType
					JRefactory_v2.6.24.java.awt.Color "defaultBG" <-- UMLType
					JRefactory_v2.6.24.java.awt.Color "foreignBG" <-- UMLType
					JavaPrimitiveTypes.int "high" <-- UMLType
					JavaPrimitiveTypes.int "lineSize" <-- UMLType
					JRefactory_v2.6.24.org.acm.seguin.uml.line.SizableLabel "nameLabel" <-- UMLType
					UMLPackage "parent" <-- UMLType
					JavaPrimitiveTypes.int "high" <-- RoleHolder
					JRefactory_v2.6.24.java.util.LinkedList "labels" <-- RoleHolder
					JRefactory_v2.6.24.org.acm.seguin.uml.line.DragPanelAdapter "panelDragAdapter" <-- RoleHolder
					JRefactory_v2.6.24.javax.swing.JPanel "child" <-- UMLMouseAdapter
					UMLPackage "current" <-- UMLMouseAdapter
					UMLType "type" <-- UMLMouseAdapter
					UMLMouseAdapter "popupMenuListener" <-- RoleHolder
					JavaPrimitiveTypes.int "wide" <-- RoleHolder
					RoleHolder "roles" <-- UMLType
					JRefactory_v2.6.24.java.awt.Color "selectedBG" <-- UMLType
					JRefactory_v2.6.24.java.awt.Color "selectedForeignBG" <-- UMLType
					JavaPrimitiveTypes.int "state" <-- UMLType
					JavaPrimitiveTypes.int "titleHeight" <-- UMLType
					JRefactory_v2.6.24.org.acm.seguin.summary.TypeSummary "type" <-- UMLType
					JavaPrimitiveTypes.int "wide" <-- UMLType
					JavaPrimitiveTypes.int "DEFAULT" <-- UMLLine
					JavaPrimitiveTypes.int "PRIVATE" <-- UMLLine
					JavaPrimitiveTypes.int "PROTECTED" <-- UMLLine
					JavaPrimitiveTypes.int "PROTECTED_PRIVATE" <-- UMLLine
					JavaPrimitiveTypes.int "PUBLIC" <-- UMLLine
					JRefactory_v2.6.24.java.awt.Font "abstractFont" <-- UMLLine
					JRefactory_v2.6.24.java.awt.Font "abstractTitleFont" <-- UMLLine
					JRefactory_v2.6.24.java.awt.Font "defaultFont" <-- UMLLine
					JRefactory_v2.6.24.java.awt.Font "font" <-- UMLLine
					JavaPrimitiveTypes.int "high" <-- UMLLine
					JavaPrimitiveTypes.int "iconHeight" <-- UMLIcon
					JavaPrimitiveTypes.int "iconWidth" <-- UMLIcon
					JavaPrimitiveTypes.double "scale" <-- UMLIcon
					UMLIcon "icon" <-- UMLLine
					JavaPrimitiveTypes.int "iconHeight" <-- UMLLine
					JavaPrimitiveTypes.int "iconMargin" <-- UMLLine
					JavaPrimitiveTypes.int "iconWidth" <-- UMLLine
					JRefactory_v2.6.24.org.acm.seguin.uml.line.SizableLabel "label" <-- UMLLine
					JavaPrimitiveTypes.int "labelMargin" <-- UMLLine
					UMLType "parent" <-- UMLLine
					JavaPrimitiveTypes.int "protection" <-- UMLLine
					JRefactory_v2.6.24.java.awt.Color "protectionColors 0..*" <-- UMLLine
					JRefactory_v2.6.24.java.awt.Font "staticFont" <-- UMLLine
					JRefactory_v2.6.24.java.awt.Font "titleFont" <-- UMLLine
					JavaPrimitiveTypes.int "wide" <-- UMLLine
					JavaPrimitiveTypes.boolean "association" <-- UMLField
					UMLPackage "current" <-- UMLField
					JRefactory_v2.6.24.org.acm.seguin.uml.line.DragPanelAdapter "fieldDragAdapter" <-- UMLField
					JRefactory_v2.6.24.org.acm.seguin.uml.line.DragPanelAdapter "parentDragAdapter" <-- UMLField
					JRefactory_v2.6.24.org.acm.seguin.summary.FieldSummary "summary" <-- UMLField
					UMLPackage "current" <-- UMLPopupMenu
					JRefactory_v2.6.24.javax.swing.JPopupMenu "popupMenu" <-- UMLPopupMenu
				}
				package ide {
					package common {
						'/** 
						' * Generic adapter for browsing source code
						' * @author    Chris Seguin
						' */
						'DP role: adapter
						class SourceBrowserAdapter {
							-activeComponent: JRefactory_v2.6.24.org.acm.seguin.uml.ISourceful
							'/** 
							' * Constructor for the SourceBrowserAdapter object
							' * @param component  Description of Parameter
							' */
							<<Create>> SourceBrowserAdapter(component : JRefactory_v2.6.24.org.acm.seguin.uml.ISourceful)
							'/** 
							' * Responds to this item being selected
							' * @param evt  Description of Parameter
							' */
							actionPerformed(evt : JRefactory_v2.6.24.java.awt.event.ActionEvent)
							'/** 
							' * Look up the chain of Summary parents to find the File the activeComponent is sourced in.
							' * @return    The File.
							' */
							#findFile(): JRefactory_v2.6.24.java.io.File
							'/** 
							' * Get the line number of the start of the current activeComponent.
							' * @return    The line number.
							' */
							#getLine(): JavaPrimitiveTypes.int
							'/** 
							' * Get the Summary of the activeComponent.
							' * @return    The Summary of the activeComponent.
							' */
							#getSummary(): JRefactory_v2.6.24.org.acm.seguin.summary.Summary
						}
						'/** 
						' * Base class for source browsing. This is the generic base class.
						' * @author    Chris Seguin
						' */
						'DP role: adaptee
						abstract class SourceBrowser {
							-{static} singleton: SourceBrowser
							<<Create>> SourceBrowser()
							'/** 
							' * Determines if the system is in a state where it can browse the source code
							' * @return    true if the source code browsing is enabled
							' */
							canBrowseSource(): JavaPrimitiveTypes.boolean
							'/** 
							' * Gets the singleton source browser
							' * @return    the current source browser
							' */
							{static} get(): SourceBrowser
							'/** 
							' * Actually browses to the file
							' * @param line      the line in the file
							' * @param file      Description of Parameter
							' */
							gotoSource(file : JRefactory_v2.6.24.java.io.File, line : JavaPrimitiveTypes.int)
							'/** 
							' * Sets the singleton source browser
							' * @param value  the new singleton
							' */
							{static} set(value : SourceBrowser)
						}
						JRefactory_v2.6.24.javax.swing.JPanel <|-- ClassListPanel
						JRefactory_v2.6.24.java.awt.event.ActionListener <|.. SourceBrowserAdapter
						JRefactory_v2.6.24.org.acm.seguin.summary.PackageSummary "summary" <-- ClassListPanel
						JRefactory_v2.6.24.org.acm.seguin.uml.UMLPackage "umlPackage" <-- ClassListPanel
						JRefactory_v2.6.24.org.acm.seguin.uml.ISourceful "activeComponent" <-- SourceBrowserAdapter
					}
				}
			}
		}
	}
	package java {
		package awt {
			package event {
				'/** 
				' * The listener interface for receiving action events. The class that is interested in processing an action event implements this interface, and the object created with that class is registered with a component, using the component's {@code addActionListener} method. When the action eventoccurs, that object's  {@code actionPerformed} method isinvoked.
				' * @see ActionEvent
				' * @see <a href="https://docs.oracle.com/javase/tutorial/uiswing/events/actionlistener.html">How to Write an Action Listener</a>
				' * @author Carl Quinn
				' * @since 1.1
				' */
				'DP role: target
				interface ActionListener {
					'/** 
					' * Invoked when an action occurs.
					' * @param e the event to be processed
					' */
					actionPerformed(e : ActionEvent)
				}
				JRefactory_v2.6.24.java.util.EventListener <|-- ActionListener
			}
		}
	}
}
@enduml
