@startuml
'Design pattern Adapter
package "JRefactory v2.6.24" as JRefactory_v2.6.24 {
	package org {
		package acm {
			package seguin {
				package ide {
					package common {
						'/** 
						' * Holds the list of classes
						' * @author    Chris Seguin
						' */
						'DP role: client
						class ClassListPanel {
							-summary: JRefactory_v2.6.24.org.acm.seguin.summary.PackageSummary
							-umlPackage: JRefactory_v2.6.24.org.acm.seguin.uml.UMLPackage
							'/** 
							' * Constructor for the ClassListPanel object
							' * @param init         Description of Parameter
							' * @param initPackage  Description of Parameter
							' */
							<<Create>> ClassListPanel(init : JRefactory_v2.6.24.org.acm.seguin.summary.PackageSummary, initPackage : JRefactory_v2.6.24.org.acm.seguin.uml.UMLPackage)
							'/** 
							' * Adds a feature to the TypeToPanel attribute of the ClassListPanel object
							' * @param nextType  The feature to be added to the TypeToPanel attribute
							' * @param gbc       The feature to be added to the TypeToPanel attribute
							' * @param count     The feature to be added to the TypeToPanel attribute
							' */
							-addTypeToPanel(nextType : JRefactory_v2.6.24.org.acm.seguin.summary.TypeSummary, gbc : JRefactory_v2.6.24.java.awt.GridBagConstraints, count : JavaPrimitiveTypes.int)
							'/** 
							' * Initializes the panel
							' */
							-init()
							'/** 
							' * Creates a list of type summaries
							' * @return    Description of the Returned Value
							' */
							-listTypes(): JRefactory_v2.6.24.java.util.Iterator
							'/** 
							' * Used to reload the class list
							' * @param init  Description of Parameter
							' */
							load(init : JRefactory_v2.6.24.org.acm.seguin.summary.PackageSummary)
							'/** 
							' * The main program for the ClassListPanel class
							' * @param args  The command line arguments
							' */
							{static} main(args : JRefactory_v2.6.24.java.lang.String)
						}
						'/** 
						' * Adapter that tells the UML diagram to jump to a specific type
						' * @author    Chris Seguin
						' */
						'DP role: adapter
						class JumpToTypeAdapter {
							-typeSummary: JRefactory_v2.6.24.org.acm.seguin.summary.TypeSummary
							-umlPackage: JRefactory_v2.6.24.org.acm.seguin.uml.UMLPackage
							'/** 
							' * Constructor for the JumpToTypeAdapter object
							' * @param initPanel  Description of Parameter
							' * @param initType   Description of Parameter
							' */
							<<Create>> JumpToTypeAdapter(initPanel : JRefactory_v2.6.24.org.acm.seguin.uml.UMLPackage, initType : JRefactory_v2.6.24.org.acm.seguin.summary.TypeSummary)
							'/** 
							' * The mouse has been clicked on the type
							' * @param e  the mouse click
							' */
							mouseClicked(e : JRefactory_v2.6.24.java.awt.event.MouseEvent)
						}
						JRefactory_v2.6.24.javax.swing.JPanel <|-- ClassListPanel
						JRefactory_v2.6.24.java.awt.event.MouseAdapter <|-- JumpToTypeAdapter
						JRefactory_v2.6.24.org.acm.seguin.summary.PackageSummary "summary" <-- ClassListPanel
						JRefactory_v2.6.24.org.acm.seguin.uml.UMLPackage "umlPackage" <-- ClassListPanel
						JRefactory_v2.6.24.org.acm.seguin.summary.TypeSummary "typeSummary" <-- JumpToTypeAdapter
						JRefactory_v2.6.24.org.acm.seguin.uml.UMLPackage "umlPackage" <-- JumpToTypeAdapter
					}
				}
				package uml {
					'DP role: adaptee
					class UMLPackage {
						-classListPanel: JRefactory_v2.6.24.org.acm.seguin.ide.common.ClassListPanel
						-currentLine: JRefactory_v2.6.24.org.acm.seguin.uml.line.SegmentedLine
						-first: JavaPrimitiveTypes.boolean
						-hasChanged: JavaPrimitiveTypes.boolean
						-loading: JavaPrimitiveTypes.boolean
						-packageName: JRefactory_v2.6.24.java.lang.String
						-scrollPane: JRefactory_v2.6.24.javax.swing.JScrollPane
						-summary: JRefactory_v2.6.24.org.acm.seguin.summary.PackageSummary
						<<Create>> UMLPackage(packageSummary : JRefactory_v2.6.24.org.acm.seguin.summary.PackageSummary)
						<<Create>> UMLPackage(filename : JRefactory_v2.6.24.java.lang.String)
						<<Create>> UMLPackage(input : JRefactory_v2.6.24.java.io.InputStream)
						-addMouseAdapter()
						clear()
						-defaultValues()
						drag(actual : JRefactory_v2.6.24.java.awt.Point)
						drop()
						#find(id : JRefactory_v2.6.24.java.lang.String): UMLType
						#find(panel1 : JRefactory_v2.6.24.java.lang.String, panel2 : JRefactory_v2.6.24.java.lang.String): JRefactory_v2.6.24.org.acm.seguin.uml.line.SegmentedLine
						#findType(searching : JRefactory_v2.6.24.org.acm.seguin.summary.TypeSummary): UMLType
						getFile(): JRefactory_v2.6.24.java.io.File
						getMinimumSize(): JRefactory_v2.6.24.java.awt.Dimension
						getPackageName(): JRefactory_v2.6.24.java.lang.String
						getPreferredSize(): JRefactory_v2.6.24.java.awt.Dimension
						getSummary(): JRefactory_v2.6.24.org.acm.seguin.summary.PackageSummary
						getTitle(): JRefactory_v2.6.24.java.lang.String
						getTypes(): UMLType
						hit(actual : JRefactory_v2.6.24.java.awt.Point)
						isDirty(): JavaPrimitiveTypes.boolean
						jumpTo(type : JRefactory_v2.6.24.org.acm.seguin.summary.TypeSummary)
						paint(g : JRefactory_v2.6.24.java.awt.Graphics)
						print(g : JRefactory_v2.6.24.java.awt.Graphics, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
						reload()
						removeAssociation(field : UMLField)
						-reset()
						save()
						setClassListPanel(value : JRefactory_v2.6.24.org.acm.seguin.ide.common.ClassListPanel)
						setDirty()
						setLoading(value : JavaPrimitiveTypes.boolean)
						setScrollPane(value : JRefactory_v2.6.24.javax.swing.JScrollPane)
						setSummary(value : JRefactory_v2.6.24.org.acm.seguin.summary.PackageSummary)
						updateClassListPanel()
					}
					JRefactory_v2.6.24.org.acm.seguin.uml.line.LinedPanel <|-- UMLPackage
					JRefactory_v2.6.24.org.acm.seguin.io.Saveable <|.. UMLPackage
					JRefactory_v2.6.24.org.acm.seguin.uml.line.EndPointPanel <|-- UMLType
					ISourceful <|.. UMLType
					JRefactory_v2.6.24.javax.swing.JPanel <|-- RoleHolder
					JRefactory_v2.6.24.java.awt.event.MouseAdapter <|-- UMLMouseAdapter
					UMLLine <|-- UMLField
					ISourceful <|.. UMLField
					JRefactory_v2.6.24.org.acm.seguin.uml.line.EndPointPanel <|-- UMLLine
					JRefactory_v2.6.24.javax.swing.Icon <|.. UMLIcon
					JRefactory_v2.6.24.org.acm.seguin.ide.common.ClassListPanel "classListPanel" <-- UMLPackage
					JRefactory_v2.6.24.org.acm.seguin.uml.line.SegmentedLine "currentLine" <-- UMLPackage
					JavaPrimitiveTypes.boolean "first" <-- UMLPackage
					JavaPrimitiveTypes.boolean "hasChanged" <-- UMLPackage
					JavaPrimitiveTypes.boolean "loading" <-- UMLPackage
					JRefactory_v2.6.24.java.lang.String "packageName" <-- UMLPackage
					JRefactory_v2.6.24.javax.swing.JScrollPane "scrollPane" <-- UMLPackage
					JRefactory_v2.6.24.org.acm.seguin.summary.PackageSummary "summary" <-- UMLPackage
					JavaPrimitiveTypes.int "DEFAULT" <-- UMLType
					JavaPrimitiveTypes.int "FOREIGN" <-- UMLType
					JavaPrimitiveTypes.int "SELECTED" <-- UMLType
					JavaPrimitiveTypes.int "TITLE_BORDER" <-- UMLType
					JavaPrimitiveTypes.int "borderWidth" <-- UMLType
					JRefactory_v2.6.24.java.awt.Color "defaultBG" <-- UMLType
					JRefactory_v2.6.24.java.awt.Color "foreignBG" <-- UMLType
					JavaPrimitiveTypes.int "high" <-- UMLType
					JavaPrimitiveTypes.int "lineSize" <-- UMLType
					JRefactory_v2.6.24.org.acm.seguin.uml.line.SizableLabel "nameLabel" <-- UMLType
					UMLPackage "parent" <-- UMLType
					JavaPrimitiveTypes.int "high" <-- RoleHolder
					JRefactory_v2.6.24.java.util.LinkedList "labels" <-- RoleHolder
					JRefactory_v2.6.24.org.acm.seguin.uml.line.DragPanelAdapter "panelDragAdapter" <-- RoleHolder
					JRefactory_v2.6.24.javax.swing.JPanel "child" <-- UMLMouseAdapter
					UMLPackage "current" <-- UMLMouseAdapter
					UMLType "type" <-- UMLMouseAdapter
					UMLMouseAdapter "popupMenuListener" <-- RoleHolder
					JavaPrimitiveTypes.int "wide" <-- RoleHolder
					RoleHolder "roles" <-- UMLType
					JRefactory_v2.6.24.java.awt.Color "selectedBG" <-- UMLType
					JRefactory_v2.6.24.java.awt.Color "selectedForeignBG" <-- UMLType
					JavaPrimitiveTypes.int "state" <-- UMLType
					JavaPrimitiveTypes.int "titleHeight" <-- UMLType
					JRefactory_v2.6.24.org.acm.seguin.summary.TypeSummary "type" <-- UMLType
					JavaPrimitiveTypes.int "wide" <-- UMLType
					JavaPrimitiveTypes.int "DEFAULT" <-- UMLLine
					JavaPrimitiveTypes.int "PRIVATE" <-- UMLLine
					JavaPrimitiveTypes.int "PROTECTED" <-- UMLLine
					JavaPrimitiveTypes.int "PROTECTED_PRIVATE" <-- UMLLine
					JavaPrimitiveTypes.int "PUBLIC" <-- UMLLine
					JRefactory_v2.6.24.java.awt.Font "abstractFont" <-- UMLLine
					JRefactory_v2.6.24.java.awt.Font "abstractTitleFont" <-- UMLLine
					JRefactory_v2.6.24.java.awt.Font "defaultFont" <-- UMLLine
					JRefactory_v2.6.24.java.awt.Font "font" <-- UMLLine
					JavaPrimitiveTypes.int "high" <-- UMLLine
					JavaPrimitiveTypes.int "iconHeight" <-- UMLIcon
					JavaPrimitiveTypes.int "iconWidth" <-- UMLIcon
					JavaPrimitiveTypes.double "scale" <-- UMLIcon
					UMLIcon "icon" <-- UMLLine
					JavaPrimitiveTypes.int "iconHeight" <-- UMLLine
					JavaPrimitiveTypes.int "iconMargin" <-- UMLLine
					JavaPrimitiveTypes.int "iconWidth" <-- UMLLine
					JRefactory_v2.6.24.org.acm.seguin.uml.line.SizableLabel "label" <-- UMLLine
					JavaPrimitiveTypes.int "labelMargin" <-- UMLLine
					UMLType "parent" <-- UMLLine
					JavaPrimitiveTypes.int "protection" <-- UMLLine
					JRefactory_v2.6.24.java.awt.Color "protectionColors 0..*" <-- UMLLine
					JRefactory_v2.6.24.java.awt.Font "staticFont" <-- UMLLine
					JRefactory_v2.6.24.java.awt.Font "titleFont" <-- UMLLine
					JavaPrimitiveTypes.int "wide" <-- UMLLine
					JavaPrimitiveTypes.boolean "association" <-- UMLField
					UMLPackage "current" <-- UMLField
					JRefactory_v2.6.24.org.acm.seguin.uml.line.DragPanelAdapter "fieldDragAdapter" <-- UMLField
					JRefactory_v2.6.24.org.acm.seguin.uml.line.DragPanelAdapter "parentDragAdapter" <-- UMLField
					JRefactory_v2.6.24.org.acm.seguin.summary.FieldSummary "summary" <-- UMLField
				}
			}
		}
	}
	package java {
		package awt {
			package event {
				'DP role: target
				class MouseAdapter {
				}
			}
		}
	}
}
@enduml
