@startuml
'Design pattern Adapter
package "JRefactory v2.6.24" as JRefactory_v2.6.24 {
	package org {
		package acm {
			package seguin {
				package uml {
					package jpg {
						'/** 
						' * Object that handles a mouse event on the save operation.
						' * @author    Chris Seguin
						' */
						'DP role: adaptee
						class SaveAdapter {
							-diagram: JRefactory_v2.6.24.org.acm.seguin.uml.UMLPackage
							-{static} directory: JRefactory_v2.6.24.java.io.File
							'/** 
							' * Constructor for the SaveAdapter object
							' * @param packageDiagram  Description of Parameter
							' */
							<<Create>> SaveAdapter(packageDiagram : JRefactory_v2.6.24.org.acm.seguin.uml.UMLPackage)
							'/** 
							' * Performs the action
							' * @param evt  Description of Parameter
							' */
							actionPerformed(evt : JRefactory_v2.6.24.java.awt.event.ActionEvent)
							'/** 
							' * Gets the Filename to save the file as
							' * @return    The Filename value
							' */
							-getFilename(): JRefactory_v2.6.24.java.lang.String
						}
						JRefactory_v2.6.24.java.awt.event.ActionListener <|.. SaveAdapter
						JRefactory_v2.6.24.org.acm.seguin.uml.UMLPackage "diagram" <-- SaveAdapter
						JRefactory_v2.6.24.java.io.File "directory" <-- SaveAdapter
					}
					JRefactory_v2.6.24.org.acm.seguin.uml.line.LinedPanel <|-- UMLPackage
					JRefactory_v2.6.24.org.acm.seguin.io.Saveable <|.. UMLPackage
					JRefactory_v2.6.24.org.acm.seguin.uml.line.EndPointPanel <|-- UMLType
					ISourceful <|.. UMLType
					JRefactory_v2.6.24.javax.swing.JPanel <|-- RoleHolder
					JRefactory_v2.6.24.java.awt.event.MouseAdapter <|-- UMLMouseAdapter
					UMLLine <|-- UMLField
					ISourceful <|.. UMLField
					JRefactory_v2.6.24.org.acm.seguin.uml.line.EndPointPanel <|-- UMLLine
					JRefactory_v2.6.24.javax.swing.Icon <|.. UMLIcon
					JRefactory_v2.6.24.org.acm.seguin.ide.common.ClassListPanel "classListPanel" <-- UMLPackage
					JRefactory_v2.6.24.org.acm.seguin.uml.line.SegmentedLine "currentLine" <-- UMLPackage
					JavaPrimitiveTypes.boolean "first" <-- UMLPackage
					JavaPrimitiveTypes.boolean "hasChanged" <-- UMLPackage
					JavaPrimitiveTypes.boolean "loading" <-- UMLPackage
					JRefactory_v2.6.24.java.lang.String "packageName" <-- UMLPackage
					JRefactory_v2.6.24.javax.swing.JScrollPane "scrollPane" <-- UMLPackage
					JRefactory_v2.6.24.org.acm.seguin.summary.PackageSummary "summary" <-- UMLPackage
					JavaPrimitiveTypes.int "DEFAULT" <-- UMLType
					JavaPrimitiveTypes.int "FOREIGN" <-- UMLType
					JavaPrimitiveTypes.int "SELECTED" <-- UMLType
					JavaPrimitiveTypes.int "TITLE_BORDER" <-- UMLType
					JavaPrimitiveTypes.int "borderWidth" <-- UMLType
					JRefactory_v2.6.24.java.awt.Color "defaultBG" <-- UMLType
					JRefactory_v2.6.24.java.awt.Color "foreignBG" <-- UMLType
					JavaPrimitiveTypes.int "high" <-- UMLType
					JavaPrimitiveTypes.int "lineSize" <-- UMLType
					JRefactory_v2.6.24.org.acm.seguin.uml.line.SizableLabel "nameLabel" <-- UMLType
					UMLPackage "parent" <-- UMLType
					JavaPrimitiveTypes.int "high" <-- RoleHolder
					JRefactory_v2.6.24.java.util.LinkedList "labels" <-- RoleHolder
					JRefactory_v2.6.24.org.acm.seguin.uml.line.DragPanelAdapter "panelDragAdapter" <-- RoleHolder
					JRefactory_v2.6.24.javax.swing.JPanel "child" <-- UMLMouseAdapter
					UMLPackage "current" <-- UMLMouseAdapter
					UMLType "type" <-- UMLMouseAdapter
					UMLMouseAdapter "popupMenuListener" <-- RoleHolder
					JavaPrimitiveTypes.int "wide" <-- RoleHolder
					RoleHolder "roles" <-- UMLType
					JRefactory_v2.6.24.java.awt.Color "selectedBG" <-- UMLType
					JRefactory_v2.6.24.java.awt.Color "selectedForeignBG" <-- UMLType
					JavaPrimitiveTypes.int "state" <-- UMLType
					JavaPrimitiveTypes.int "titleHeight" <-- UMLType
					JRefactory_v2.6.24.org.acm.seguin.summary.TypeSummary "type" <-- UMLType
					JavaPrimitiveTypes.int "wide" <-- UMLType
					JavaPrimitiveTypes.int "DEFAULT" <-- UMLLine
					JavaPrimitiveTypes.int "PRIVATE" <-- UMLLine
					JavaPrimitiveTypes.int "PROTECTED" <-- UMLLine
					JavaPrimitiveTypes.int "PROTECTED_PRIVATE" <-- UMLLine
					JavaPrimitiveTypes.int "PUBLIC" <-- UMLLine
					JRefactory_v2.6.24.java.awt.Font "abstractFont" <-- UMLLine
					JRefactory_v2.6.24.java.awt.Font "abstractTitleFont" <-- UMLLine
					JRefactory_v2.6.24.java.awt.Font "defaultFont" <-- UMLLine
					JRefactory_v2.6.24.java.awt.Font "font" <-- UMLLine
					JavaPrimitiveTypes.int "high" <-- UMLLine
					JavaPrimitiveTypes.int "iconHeight" <-- UMLIcon
					JavaPrimitiveTypes.int "iconWidth" <-- UMLIcon
					JavaPrimitiveTypes.double "scale" <-- UMLIcon
					UMLIcon "icon" <-- UMLLine
					JavaPrimitiveTypes.int "iconHeight" <-- UMLLine
					JavaPrimitiveTypes.int "iconMargin" <-- UMLLine
					JavaPrimitiveTypes.int "iconWidth" <-- UMLLine
					JRefactory_v2.6.24.org.acm.seguin.uml.line.SizableLabel "label" <-- UMLLine
					JavaPrimitiveTypes.int "labelMargin" <-- UMLLine
					UMLType "parent" <-- UMLLine
					JavaPrimitiveTypes.int "protection" <-- UMLLine
					JRefactory_v2.6.24.java.awt.Color "protectionColors 0..*" <-- UMLLine
					JRefactory_v2.6.24.java.awt.Font "staticFont" <-- UMLLine
					JRefactory_v2.6.24.java.awt.Font "titleFont" <-- UMLLine
					JavaPrimitiveTypes.int "wide" <-- UMLLine
					JavaPrimitiveTypes.boolean "association" <-- UMLField
					UMLPackage "current" <-- UMLField
					JRefactory_v2.6.24.org.acm.seguin.uml.line.DragPanelAdapter "fieldDragAdapter" <-- UMLField
					JRefactory_v2.6.24.org.acm.seguin.uml.line.DragPanelAdapter "parentDragAdapter" <-- UMLField
					JRefactory_v2.6.24.org.acm.seguin.summary.FieldSummary "summary" <-- UMLField
				}
			}
		}
	}
}
@enduml
