@startuml
'Design pattern Composite
package "PMD v1.8" as PMD_v1.8 {
	package net {
		package sourceforge {
			package pmd {
				package ast {
					'DP role: component
					interface Node {
						'/** 
						' * Accept the visitor. 
						' */
						jjtAccept(visitor : JavaParserVisitor, data : PMD_v1.8.java.lang.Object): PMD_v1.8.java.lang.Object
						'/** 
						' * This method tells the node to add its argument to the node's list of children.  
						' */
						jjtAddChild(n : Node, i : JavaPrimitiveTypes.int)
						'/** 
						' * This method is called after all the child nodes have been added. 
						' */
						jjtClose()
						'/** 
						' * This method returns a child node.  The children are numbered from zero, left to right.
						' * @param i the child index. Must be nonnegative and less than{@link #jjtGetNumChildren}.
						' */
						jjtGetChild(i : JavaPrimitiveTypes.int): Node
						'/** 
						' * Return the number of children the node has. 
						' */
						jjtGetNumChildren(): JavaPrimitiveTypes.int
						jjtGetParent(): Node
						'/** 
						' * This method is called after the node has been made the current node.  It indicates that child nodes can now be added to it. 
						' */
						jjtOpen()
						'/** 
						' * This pair of methods are used to inform the node of its parent. 
						' */
						jjtSetParent(n : Node)
					}
					Node <|.. SimpleNode
					JavaParserTreeConstants <|.. JavaParser
					JavaParserConstants <|.. JavaParser
					JavaParserConstants <|.. JavaParserTokenManager
					SimpleNode <|-- ASTCompilationUnit
					PMD_v1.8.java.lang.RuntimeException <|-- ParseException
					SimpleNode <|-- ASTVariableDeclaratorId
					SimpleNode <|-- ASTType
					SimpleNode <|-- AccessNode
					AccessFlags <|.. AccessNode
					SimpleNode <|-- ASTMethodDeclarator
					SimpleNode <|-- ASTPackageDeclaration
					SimpleNode <|-- ASTImportDeclaration
					SimpleNode <|-- ASTName
					SimpleNode <|-- ASTTypeDeclaration
					AccessNode <|-- ASTClassDeclaration
					SimpleNode <|-- ASTUnmodifiedClassDeclaration
					SimpleNode <|-- ASTClassBody
					AccessNode <|-- ASTNestedClassDeclaration
					SimpleNode <|-- ASTClassBodyDeclaration
					AccessNode <|-- ASTEnumDeclaration
					SimpleNode <|-- ASTEnumElement
					SimpleNode <|-- ASTMethodDeclarationLookahead
					AccessNode <|-- ASTInterfaceDeclaration
					SimpleNode <|-- ASTUnmodifiedInterfaceDeclaration
					AccessNode <|-- ASTNestedInterfaceDeclaration
					SimpleNode <|-- ASTInterfaceMemberDeclaration
					AccessNode <|-- ASTFieldDeclaration
					SimpleNode <|-- ASTVariableDeclarator
					SimpleNode <|-- ASTVariableInitializer
					SimpleNode <|-- ASTArrayInitializer
					AccessNode <|-- ASTMethodDeclaration
					SimpleNode <|-- ASTFormalParameters
					AccessNode <|-- ASTFormalParameter
					AccessNode <|-- ASTConstructorDeclaration
					SimpleNode <|-- ASTExplicitConstructorInvocation
					SimpleNode <|-- ASTInitializer
					SimpleNode <|-- ASTPrimitiveType
					SimpleNode <|-- ASTResultType
					SimpleNode <|-- ASTNameList
					SimpleNode <|-- ASTExpression
					SimpleNode <|-- ASTAssignmentOperator
					SimpleNode <|-- ASTConditionalExpression
					SimpleNode <|-- ASTConditionalOrExpression
					SimpleNode <|-- ASTConditionalAndExpression
					SimpleNode <|-- ASTInclusiveOrExpression
					SimpleNode <|-- ASTExclusiveOrExpression
					SimpleNode <|-- ASTAndExpression
					SimpleNode <|-- ASTEqualityExpression
					SimpleNode <|-- ASTInstanceOfExpression
					SimpleNode <|-- ASTRelationalExpression
					SimpleNode <|-- ASTShiftExpression
					SimpleNode <|-- ASTAdditiveExpression
					SimpleNode <|-- ASTMultiplicativeExpression
					SimpleNode <|-- ASTUnaryExpression
					SimpleNode <|-- ASTPreIncrementExpression
					SimpleNode <|-- ASTPreDecrementExpression
					SimpleNode <|-- ASTUnaryExpressionNotPlusMinus
					SimpleNode <|-- ASTCastLookahead
					SimpleNode <|-- ASTPostfixExpression
					SimpleNode <|-- ASTCastExpression
					SimpleNode <|-- ASTPrimaryExpression
					SimpleNode <|-- ASTPrimaryPrefix
					SimpleNode <|-- ASTPrimarySuffix
					SimpleNode <|-- ASTLiteral
					SimpleNode <|-- ASTBooleanLiteral
					SimpleNode <|-- ASTNullLiteral
					SimpleNode <|-- ASTArguments
					SimpleNode <|-- ASTArgumentList
					SimpleNode <|-- ASTAllocationExpression
					SimpleNode <|-- ASTArrayDimsAndInits
					SimpleNode <|-- ASTStatement
					SimpleNode <|-- ASTLabeledStatement
					SimpleNode <|-- ASTBlock
					SimpleNode <|-- ASTBlockStatement
					AccessNode <|-- ASTLocalVariableDeclaration
					SimpleNode <|-- ASTEmptyStatement
					SimpleNode <|-- ASTStatementExpression
					SimpleNode <|-- ASTSwitchStatement
					SimpleNode <|-- ASTSwitchLabel
					SimpleNode <|-- ASTIfStatement
					SimpleNode <|-- ASTWhileStatement
					SimpleNode <|-- ASTDoStatement
					SimpleNode <|-- ASTForStatement
					SimpleNode <|-- ASTForInit
					SimpleNode <|-- ASTStatementExpressionList
					SimpleNode <|-- ASTForUpdate
					SimpleNode <|-- ASTBreakStatement
					SimpleNode <|-- ASTContinueStatement
					SimpleNode <|-- ASTReturnStatement
					SimpleNode <|-- ASTThrowStatement
					SimpleNode <|-- ASTSynchronizedStatement
					SimpleNode <|-- ASTTryStatement
					SimpleNode <|-- ASTAssertStatement
					JavaPrimitiveTypes.int "beginColumn" <-- SimpleNode
					JavaPrimitiveTypes.int "beginLine" <-- SimpleNode
					Node "children 0..*" <-- SimpleNode
					JavaPrimitiveTypes.boolean "discardable" <-- SimpleNode
					JavaPrimitiveTypes.int "endColumn" <-- SimpleNode
					JavaPrimitiveTypes.int "endLine" <-- SimpleNode
					JavaPrimitiveTypes.int "id" <-- SimpleNode
					PMD_v1.8.java.lang.String "image" <-- SimpleNode
					Node "parent" <-- SimpleNode
					JavaPrimitiveTypes.int "JJTADDITIVEEXPRESSION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTALLOCATIONEXPRESSION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTANDEXPRESSION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTARGUMENTLIST" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTARGUMENTS" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTARRAYDIMSANDINITS" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTARRAYINITIALIZER" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTASSERTSTATEMENT" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTASSIGNMENTOPERATOR" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTBLOCK" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTBLOCKSTATEMENT" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTBOOLEANLITERAL" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTBREAKSTATEMENT" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTCASTEXPRESSION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTCASTLOOKAHEAD" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTCLASSBODY" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTCLASSBODYDECLARATION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTCLASSDECLARATION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTCOMPILATIONUNIT" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTCONDITIONALANDEXPRESSION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTCONDITIONALEXPRESSION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTCONDITIONALOREXPRESSION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTCONSTRUCTORDECLARATION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTCONTINUESTATEMENT" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTDOSTATEMENT" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTEMPTYSTATEMENT" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTENUMDECLARATION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTENUMELEMENT" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTEQUALITYEXPRESSION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTEXCLUSIVEOREXPRESSION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTEXPLICITCONSTRUCTORINVOCATION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTEXPRESSION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTFIELDDECLARATION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTFORINIT" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTFORMALPARAMETER" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTFORMALPARAMETERS" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTFORSTATEMENT" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTFORUPDATE" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTIFSTATEMENT" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTIMPORTDECLARATION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTINCLUSIVEOREXPRESSION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTINITIALIZER" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTINSTANCEOFEXPRESSION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTINTERFACEDECLARATION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTINTERFACEMEMBERDECLARATION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTLABELEDSTATEMENT" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTLITERAL" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTLOCALVARIABLEDECLARATION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTMETHODDECLARATION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTMETHODDECLARATIONLOOKAHEAD" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTMETHODDECLARATOR" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTMULTIPLICATIVEEXPRESSION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTNAME" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTNAMELIST" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTNESTEDCLASSDECLARATION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTNESTEDINTERFACEDECLARATION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTNULLLITERAL" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTPACKAGEDECLARATION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTPOSTFIXEXPRESSION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTPREDECREMENTEXPRESSION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTPREINCREMENTEXPRESSION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTPRIMARYEXPRESSION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTPRIMARYPREFIX" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTPRIMARYSUFFIX" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTPRIMITIVETYPE" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTRELATIONALEXPRESSION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTRESULTTYPE" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTRETURNSTATEMENT" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTSHIFTEXPRESSION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTSTATEMENT" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTSTATEMENTEXPRESSION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTSTATEMENTEXPRESSIONLIST" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTSWITCHLABEL" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTSWITCHSTATEMENT" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTSYNCHRONIZEDSTATEMENT" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTTHROWSTATEMENT" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTTRYSTATEMENT" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTTYPE" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTTYPEDECLARATION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTUNARYEXPRESSION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTUNARYEXPRESSIONNOTPLUSMINUS" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTUNMODIFIEDCLASSDECLARATION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTUNMODIFIEDINTERFACEDECLARATION" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTVARIABLEDECLARATOR" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTVARIABLEDECLARATORID" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTVARIABLEINITIALIZER" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "JJTWHILESTATEMENT" <-- JavaParserTreeConstants
					PMD_v1.8.java.lang.String "jjtNodeName 0..*" <-- JavaParserTreeConstants
					JavaPrimitiveTypes.int "ABSTRACT" <-- JavaParserConstants
					JavaPrimitiveTypes.int "ANDASSIGN" <-- JavaParserConstants
					JavaPrimitiveTypes.int "ASSIGN" <-- JavaParserConstants
					JavaPrimitiveTypes.int "BANG" <-- JavaParserConstants
					JavaPrimitiveTypes.int "BIT_AND" <-- JavaParserConstants
					JavaPrimitiveTypes.int "BIT_OR" <-- JavaParserConstants
					JavaPrimitiveTypes.int "BOOLEAN" <-- JavaParserConstants
					JavaPrimitiveTypes.int "BREAK" <-- JavaParserConstants
					JavaPrimitiveTypes.int "BYTE" <-- JavaParserConstants
					JavaPrimitiveTypes.int "CASE" <-- JavaParserConstants
					JavaPrimitiveTypes.int "CATCH" <-- JavaParserConstants
					JavaPrimitiveTypes.int "CHAR" <-- JavaParserConstants
					JavaPrimitiveTypes.int "CHARACTER_LITERAL" <-- JavaParserConstants
					JavaPrimitiveTypes.int "CLASS" <-- JavaParserConstants
					JavaPrimitiveTypes.int "COLON" <-- JavaParserConstants
					JavaPrimitiveTypes.int "COMMA" <-- JavaParserConstants
					JavaPrimitiveTypes.int "CONST" <-- JavaParserConstants
					JavaPrimitiveTypes.int "CONTINUE" <-- JavaParserConstants
					JavaPrimitiveTypes.int "DECIMAL_LITERAL" <-- JavaParserConstants
					JavaPrimitiveTypes.int "DECR" <-- JavaParserConstants
					JavaPrimitiveTypes.int "DEFAULT" <-- JavaParserConstants
					JavaPrimitiveTypes.int "DIGIT" <-- JavaParserConstants
					JavaPrimitiveTypes.int "DO" <-- JavaParserConstants
					JavaPrimitiveTypes.int "DOT" <-- JavaParserConstants
					JavaPrimitiveTypes.int "DOUBLE" <-- JavaParserConstants
					JavaPrimitiveTypes.int "ELSE" <-- JavaParserConstants
					JavaPrimitiveTypes.int "EOF" <-- JavaParserConstants
					JavaPrimitiveTypes.int "EQ" <-- JavaParserConstants
					JavaPrimitiveTypes.int "EXPONENT" <-- JavaParserConstants
					JavaPrimitiveTypes.int "EXTENDS" <-- JavaParserConstants
					JavaPrimitiveTypes.int "FALSE" <-- JavaParserConstants
					JavaPrimitiveTypes.int "FINAL" <-- JavaParserConstants
					JavaPrimitiveTypes.int "FINALLY" <-- JavaParserConstants
					JavaPrimitiveTypes.int "FLOAT" <-- JavaParserConstants
					JavaPrimitiveTypes.int "FLOATING_POINT_LITERAL" <-- JavaParserConstants
					JavaPrimitiveTypes.int "FOR" <-- JavaParserConstants
					JavaPrimitiveTypes.int "FORMAL_COMMENT" <-- JavaParserConstants
					JavaPrimitiveTypes.int "GE" <-- JavaParserConstants
					JavaPrimitiveTypes.int "GOTO" <-- JavaParserConstants
					JavaPrimitiveTypes.int "GT" <-- JavaParserConstants
					JavaPrimitiveTypes.int "HEX_LITERAL" <-- JavaParserConstants
					JavaPrimitiveTypes.int "HOOK" <-- JavaParserConstants
					JavaPrimitiveTypes.int "IDENTIFIER" <-- JavaParserConstants
					JavaPrimitiveTypes.int "IF" <-- JavaParserConstants
					JavaPrimitiveTypes.int "IMPLEMENTS" <-- JavaParserConstants
					JavaPrimitiveTypes.int "IMPORT" <-- JavaParserConstants
					JavaPrimitiveTypes.int "INCR" <-- JavaParserConstants
					JavaPrimitiveTypes.int "INSTANCEOF" <-- JavaParserConstants
					JavaPrimitiveTypes.int "INT" <-- JavaParserConstants
					JavaPrimitiveTypes.int "INTEGER_LITERAL" <-- JavaParserConstants
					JavaPrimitiveTypes.int "INTERFACE" <-- JavaParserConstants
					JavaPrimitiveTypes.int "IN_FORMAL_COMMENT" <-- JavaParserConstants
					JavaPrimitiveTypes.int "IN_MULTI_LINE_COMMENT" <-- JavaParserConstants
					JavaPrimitiveTypes.int "LBRACE" <-- JavaParserConstants
					JavaPrimitiveTypes.int "LBRACKET" <-- JavaParserConstants
					JavaPrimitiveTypes.int "LE" <-- JavaParserConstants
					JavaPrimitiveTypes.int "LETTER" <-- JavaParserConstants
					JavaPrimitiveTypes.int "LONG" <-- JavaParserConstants
					JavaPrimitiveTypes.int "LPAREN" <-- JavaParserConstants
					JavaPrimitiveTypes.int "LSHIFT" <-- JavaParserConstants
					JavaPrimitiveTypes.int "LSHIFTASSIGN" <-- JavaParserConstants
					JavaPrimitiveTypes.int "LT" <-- JavaParserConstants
					JavaPrimitiveTypes.int "MINUS" <-- JavaParserConstants
					JavaPrimitiveTypes.int "MINUSASSIGN" <-- JavaParserConstants
					JavaPrimitiveTypes.int "MULTI_LINE_COMMENT" <-- JavaParserConstants
					JavaPrimitiveTypes.int "NATIVE" <-- JavaParserConstants
					JavaPrimitiveTypes.int "NE" <-- JavaParserConstants
					JavaPrimitiveTypes.int "NEW" <-- JavaParserConstants
					JavaPrimitiveTypes.int "NULL" <-- JavaParserConstants
					JavaPrimitiveTypes.int "OCTAL_LITERAL" <-- JavaParserConstants
					JavaPrimitiveTypes.int "ORASSIGN" <-- JavaParserConstants
					JavaPrimitiveTypes.int "PACKAGE" <-- JavaParserConstants
					JavaPrimitiveTypes.int "PLUS" <-- JavaParserConstants
					JavaPrimitiveTypes.int "PLUSASSIGN" <-- JavaParserConstants
					JavaPrimitiveTypes.int "PRIVATE" <-- JavaParserConstants
					JavaPrimitiveTypes.int "PROTECTED" <-- JavaParserConstants
					JavaPrimitiveTypes.int "PUBLIC" <-- JavaParserConstants
					JavaPrimitiveTypes.int "RBRACE" <-- JavaParserConstants
					JavaPrimitiveTypes.int "RBRACKET" <-- JavaParserConstants
					JavaPrimitiveTypes.int "REM" <-- JavaParserConstants
					JavaPrimitiveTypes.int "REMASSIGN" <-- JavaParserConstants
					JavaPrimitiveTypes.int "RETURN" <-- JavaParserConstants
					JavaPrimitiveTypes.int "RPAREN" <-- JavaParserConstants
					JavaPrimitiveTypes.int "RSIGNEDSHIFT" <-- JavaParserConstants
					JavaPrimitiveTypes.int "RSIGNEDSHIFTASSIGN" <-- JavaParserConstants
					JavaPrimitiveTypes.int "RUNSIGNEDSHIFT" <-- JavaParserConstants
					JavaPrimitiveTypes.int "RUNSIGNEDSHIFTASSIGN" <-- JavaParserConstants
					JavaPrimitiveTypes.int "SC_AND" <-- JavaParserConstants
					JavaPrimitiveTypes.int "SC_OR" <-- JavaParserConstants
					JavaPrimitiveTypes.int "SEMICOLON" <-- JavaParserConstants
					JavaPrimitiveTypes.int "SHORT" <-- JavaParserConstants
					JavaPrimitiveTypes.int "SINGLE_LINE_COMMENT" <-- JavaParserConstants
					JavaPrimitiveTypes.int "SLASH" <-- JavaParserConstants
					JavaPrimitiveTypes.int "SLASHASSIGN" <-- JavaParserConstants
					JavaPrimitiveTypes.int "STAR" <-- JavaParserConstants
					JavaPrimitiveTypes.int "STARASSIGN" <-- JavaParserConstants
					JavaPrimitiveTypes.int "STATIC" <-- JavaParserConstants
					JavaPrimitiveTypes.int "STRICTFP" <-- JavaParserConstants
					JavaPrimitiveTypes.int "STRING_LITERAL" <-- JavaParserConstants
					JavaPrimitiveTypes.int "SUPER" <-- JavaParserConstants
					JavaPrimitiveTypes.int "SWITCH" <-- JavaParserConstants
					JavaPrimitiveTypes.int "SYNCHRONIZED" <-- JavaParserConstants
					JavaPrimitiveTypes.int "THIS" <-- JavaParserConstants
					JavaPrimitiveTypes.int "THROW" <-- JavaParserConstants
					JavaPrimitiveTypes.int "THROWS" <-- JavaParserConstants
					JavaPrimitiveTypes.int "TILDE" <-- JavaParserConstants
					JavaPrimitiveTypes.int "TRANSIENT" <-- JavaParserConstants
					JavaPrimitiveTypes.int "TRUE" <-- JavaParserConstants
					JavaPrimitiveTypes.int "TRY" <-- JavaParserConstants
					JavaPrimitiveTypes.int "VOID" <-- JavaParserConstants
					JavaPrimitiveTypes.int "VOLATILE" <-- JavaParserConstants
					JavaPrimitiveTypes.int "WHILE" <-- JavaParserConstants
					JavaPrimitiveTypes.int "XOR" <-- JavaParserConstants
					JavaPrimitiveTypes.int "XORASSIGN" <-- JavaParserConstants
					JavaPrimitiveTypes.int "_DEFAULT" <-- JavaParserConstants
					PMD_v1.8.java.lang.String "tokenImage 0..*" <-- JavaParserConstants
					JavaPrimitiveTypes.boolean "isJDK15" <-- JavaParser
					JavaPrimitiveTypes.int "arg" <-- JJCalls
					JavaPrimitiveTypes.int "beginColumn" <-- Token
					JavaPrimitiveTypes.int "beginLine" <-- Token
					JavaPrimitiveTypes.int "endColumn" <-- Token
					JavaPrimitiveTypes.int "endLine" <-- Token
					PMD_v1.8.java.lang.String "image" <-- Token
					JavaPrimitiveTypes.int "kind" <-- Token
					Token "first" <-- JJCalls
					JavaPrimitiveTypes.int "gen" <-- JJCalls
					JJCalls "jj_2_rtns 0..*" <-- JavaParser
					JavaPrimitiveTypes.int "jj_endpos" <-- JavaParser
					PMD_v1.8.java.util.Vector "jj_expentries" <-- JavaParser
					JavaPrimitiveTypes.int "jj_expentry 0..*" <-- JavaParser
					JavaPrimitiveTypes.int "jj_gc" <-- JavaParser
					JavaPrimitiveTypes.int "jj_gen" <-- JavaParser
					JavaPrimitiveTypes.int "jj_kind" <-- JavaParser
					JavaPrimitiveTypes.int "jj_la" <-- JavaParser
					JavaPrimitiveTypes.int "jj_la1 0..*" <-- JavaParser
					JavaPrimitiveTypes.int "jj_la1_0 0..*" <-- JavaParser
					JavaPrimitiveTypes.int "jj_la1_1 0..*" <-- JavaParser
					JavaPrimitiveTypes.int "jj_la1_2 0..*" <-- JavaParser
					JavaPrimitiveTypes.int "jj_la1_3 0..*" <-- JavaParser
					Token "jj_lastpos" <-- JavaParser
					JavaPrimitiveTypes.int "jj_lasttokens 0..*" <-- JavaParser
					LookaheadSuccess "jj_ls" <-- JavaParser
					Token "jj_nt" <-- JavaParser
					JavaPrimitiveTypes.int "jj_ntk" <-- JavaParser
					JavaPrimitiveTypes.boolean "jj_rescan" <-- JavaParser
					Token "jj_scanpos" <-- JavaParser
					JavaPrimitiveTypes.boolean "jj_semLA" <-- JavaParser
					PMD_v1.8.java.util.Stack "marks" <-- JJTJavaParserState
					JavaPrimitiveTypes.int "mk" <-- JJTJavaParserState
					JavaPrimitiveTypes.boolean "node_created" <-- JJTJavaParserState
					PMD_v1.8.java.util.Stack "nodes" <-- JJTJavaParserState
					JavaPrimitiveTypes.int "sp" <-- JJTJavaParserState
					JJTJavaParserState "jjtree" <-- JavaParser
					JavaPrimitiveTypes.boolean "lookingAhead" <-- JavaParser
					Token "token" <-- JavaParser
					JavaPrimitiveTypes.char "curChar" <-- JavaParserTokenManager
					JavaPrimitiveTypes.int "curLexState" <-- JavaParserTokenManager
					PMD_v1.8.java.io.PrintStream "debugStream" <-- JavaParserTokenManager
					JavaPrimitiveTypes.int "defaultLexState" <-- JavaParserTokenManager
					PMD_v1.8.java.lang.StringBuffer "image" <-- JavaParserTokenManager
					CharStream "input_stream" <-- JavaParserTokenManager
					JavaPrimitiveTypes.long "jjbitVec0 0..*" <-- JavaParserTokenManager
					JavaPrimitiveTypes.long "jjbitVec2 0..*" <-- JavaParserTokenManager
					JavaPrimitiveTypes.long "jjbitVec3 0..*" <-- JavaParserTokenManager
					JavaPrimitiveTypes.long "jjbitVec4 0..*" <-- JavaParserTokenManager
					JavaPrimitiveTypes.long "jjbitVec5 0..*" <-- JavaParserTokenManager
					JavaPrimitiveTypes.long "jjbitVec6 0..*" <-- JavaParserTokenManager
					JavaPrimitiveTypes.long "jjbitVec7 0..*" <-- JavaParserTokenManager
					JavaPrimitiveTypes.long "jjbitVec8 0..*" <-- JavaParserTokenManager
					JavaPrimitiveTypes.int "jjimageLen" <-- JavaParserTokenManager
					JavaPrimitiveTypes.int "jjmatchedKind" <-- JavaParserTokenManager
					JavaPrimitiveTypes.int "jjmatchedPos" <-- JavaParserTokenManager
					JavaPrimitiveTypes.int "jjnewLexState 0..*" <-- JavaParserTokenManager
					JavaPrimitiveTypes.int "jjnewStateCnt" <-- JavaParserTokenManager
					JavaPrimitiveTypes.int "jjnextStates 0..*" <-- JavaParserTokenManager
					JavaPrimitiveTypes.int "jjround" <-- JavaParserTokenManager
					JavaPrimitiveTypes.int "jjrounds 0..*" <-- JavaParserTokenManager
					JavaPrimitiveTypes.int "jjstateSet 0..*" <-- JavaParserTokenManager
					PMD_v1.8.java.lang.String "jjstrLiteralImages 0..*" <-- JavaParserTokenManager
					JavaPrimitiveTypes.long "jjtoMore 0..*" <-- JavaParserTokenManager
					JavaPrimitiveTypes.long "jjtoSkip 0..*" <-- JavaParserTokenManager
					JavaPrimitiveTypes.long "jjtoSpecial 0..*" <-- JavaParserTokenManager
					JavaPrimitiveTypes.long "jjtoToken 0..*" <-- JavaParserTokenManager
					JavaPrimitiveTypes.int "lengthOfMatch" <-- JavaParserTokenManager
					PMD_v1.8.java.lang.String "lexStateNames 0..*" <-- JavaParserTokenManager
					JavaParserTokenManager "token_source" <-- JavaParser
					JavaPrimitiveTypes.boolean "usingAssertAsIdentifier" <-- JavaParser
					Token "currentToken" <-- ParseException
					PMD_v1.8.java.lang.String "eol" <-- ParseException
					JavaPrimitiveTypes.int "expectedTokenSequences 0..*" <-- ParseException
					JavaPrimitiveTypes.boolean "specialConstructor" <-- ParseException
					PMD_v1.8.java.lang.String "tokenImage 0..*" <-- ParseException
					JavaParser "parser" <-- SimpleNode
					JavaPrimitiveTypes.int "dimensions" <-- ASTType
					JavaPrimitiveTypes.boolean "isArray" <-- ASTType
					JavaPrimitiveTypes.short "ACC_ABSTRACT" <-- AccessFlags
					JavaPrimitiveTypes.short "ACC_FINAL" <-- AccessFlags
					JavaPrimitiveTypes.short "ACC_INTERFACE" <-- AccessFlags
					JavaPrimitiveTypes.short "ACC_NATIVE" <-- AccessFlags
					JavaPrimitiveTypes.short "ACC_PRIVATE" <-- AccessFlags
					JavaPrimitiveTypes.short "ACC_PROTECTED" <-- AccessFlags
					JavaPrimitiveTypes.short "ACC_PUBLIC" <-- AccessFlags
					JavaPrimitiveTypes.short "ACC_STATIC" <-- AccessFlags
					JavaPrimitiveTypes.short "ACC_STRICT" <-- AccessFlags
					JavaPrimitiveTypes.short "ACC_SUPER" <-- AccessFlags
					JavaPrimitiveTypes.short "ACC_SYNCHRONIZED" <-- AccessFlags
					JavaPrimitiveTypes.short "ACC_TRANSIENT" <-- AccessFlags
					JavaPrimitiveTypes.short "ACC_VOLATILE" <-- AccessFlags
					JavaPrimitiveTypes.short "accessFlags" <-- AccessNode
					PMD_v1.8.net.sourceforge.pmd.symboltable.Scope "scope" <-- SimpleNode
					JavaPrimitiveTypes.boolean "isImportOnDemand" <-- ASTImportDeclaration
					JavaPrimitiveTypes.boolean "hasExplicitExtends" <-- ASTUnmodifiedClassDeclaration
					JavaPrimitiveTypes.boolean "hasExplicitImplements" <-- ASTUnmodifiedClassDeclaration
					PMD_v1.8.java.lang.String "thisOrSuper" <-- ASTExplicitConstructorInvocation
					JavaPrimitiveTypes.boolean "isStatic" <-- ASTInitializer
					JavaPrimitiveTypes.boolean "usesSuperModifier" <-- ASTPrimaryPrefix
					JavaPrimitiveTypes.boolean "usesThisModifier" <-- ASTPrimaryPrefix
					JavaPrimitiveTypes.boolean "isArguments" <-- ASTPrimarySuffix
					JavaPrimitiveTypes.boolean "isTrue" <-- ASTBooleanLiteral
					JavaPrimitiveTypes.boolean "hasElse" <-- ASTIfStatement
					JavaPrimitiveTypes.boolean "hasCatch" <-- ASTTryStatement
					JavaPrimitiveTypes.boolean "hasFinally" <-- ASTTryStatement
				}
			}
		}
	}
}
@enduml
