@startuml
'Design pattern Observer
package "JHotDraw v5.1" as JHotDraw_v5.1 {
	package CH {
		package ifa {
			package draw {
				package framework {
					'/** 
					' * Drawing is a container for figures. <p> Drawing sends out DrawingChanged events to DrawingChangeListeners whenever a part of its area was invalidated. <hr> <b>Design Patterns</b><P> <img src="images/red-ball-small.gif" width=6 height=6 alt=" o "> <b><a href=../pattlets/sld026.htm>Observer</a></b><br> The Observer pattern is used to decouple the Drawing from its views and to enable multiple views.<hr>
					' * @see Figure
					' * @see DrawingView
					' * @see FigureChangeListener
					' */
					'DP role: subject
					interface Drawing {
						'/** 
						' * Adds a figure and sets its container to refer to this drawing.
						' * @return the figure that was inserted.
						' */
						add(figure : Figure): Figure
						'/** 
						' * Adds a vector of figures.
						' */
						addAll(newFigures : JHotDraw_v5.1.java.util.Vector)
						'/** 
						' * Adds a listener for this drawing.
						' */
						addDrawingChangeListener(listener : DrawingChangeListener)
						'/** 
						' * Brings a figure to the front.
						' */
						bringToFront(figure : Figure)
						'/** 
						' * Draws all the figures back to front.
						' */
						draw(g : JHotDraw_v5.1.java.awt.Graphics)
						'/** 
						' * Gets the listeners of a drawing.
						' */
						drawingChangeListeners(): JHotDraw_v5.1.java.util.Enumeration
						'/** 
						' * Invalidates a rectangle and merges it with the existing damaged area.
						' */
						figureInvalidated(e : FigureChangeEvent)
						'/** 
						' * Handles a removeFrfigureRequestRemove request that is passed up the figure container hierarchy.
						' * @see FigureChangeListener
						' */
						figureRequestRemove(e : FigureChangeEvent)
						'/** 
						' * Forces an update of the drawing change listeners.
						' */
						figureRequestUpdate(e : FigureChangeEvent)
						'/** 
						' * Returns an enumeration to iterate in Z-order back to front over the figures.
						' */
						figures(): FigureEnumeration
						'/** 
						' * Returns an enumeration to iterate in Z-order front to back over the figures.
						' */
						figuresReverse(): FigureEnumeration
						'/** 
						' * Finds a top level Figure. Use this call for hit detection that should not descend into the figure's children.
						' */
						findFigure(x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int): Figure
						'/** 
						' * Finds a top level Figure that intersects the given rectangle.
						' */
						findFigure(r : JHotDraw_v5.1.java.awt.Rectangle): Figure
						'/** 
						' * Finds a top level Figure that intersects the given rectangle. It supresses the passed in figure. Use this method to ignore a figure that is temporarily inserted into the drawing.
						' */
						findFigure(r : JHotDraw_v5.1.java.awt.Rectangle, without : Figure): Figure
						'/** 
						' * Finds a figure but descends into a figure's children. Use this method to implement <i>click-through</i> hit detection, that is, you want to detect the inner most figure containing the given point.
						' */
						findFigureInside(x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int): Figure
						'/** 
						' * Finds a figure but descends into a figure's children. It supresses the passed in figure. Use this method to ignore a figure that is temporarily inserted into the drawing.
						' * @param x the x coordinate
						' * @param y the y coordinate
						' * @param without the figure to be ignored duringthe find.
						' */
						findFigureInsideWithout(x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int, without : Figure): Figure
						'/** 
						' * Finds a top level Figure, but supresses the passed in figure. Use this method to ignore a figure that is temporarily inserted into the drawing.
						' * @param x the x coordinate
						' * @param y the y coordinate
						' * @param without the figure to be ignored duringthe find.
						' */
						findFigureWithout(x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int, without : Figure): Figure
						'/** 
						' * Acquires the drawing lock.
						' */
						lock()
						'/** 
						' * Removes a figure from the figure list, but doesn't release it. Use this method to temporarily manipulate a figure outside of the drawing.
						' */
						orphan(figure : Figure): Figure
						'/** 
						' * Removes a vector of figures from the figure's list without releasing the figures.
						' * @see orphan
						' */
						orphanAll(newFigures : JHotDraw_v5.1.java.util.Vector)
						'/** 
						' * Releases the drawing and its contained figures.
						' */
						release()
						'/** 
						' * Removes the figure from the drawing and releases it.
						' */
						remove(figure : Figure): Figure
						'/** 
						' * Removes a vector of figures .
						' * @see remove
						' */
						removeAll(figures : JHotDraw_v5.1.java.util.Vector)
						'/** 
						' * Removes a listener from this drawing.
						' */
						removeDrawingChangeListener(listener : DrawingChangeListener)
						'/** 
						' * Replaces a figure in the drawing without removing it from the drawing.
						' */
						replace(figure : Figure, replacement : Figure)
						'/** 
						' * Sends a figure to the back of the drawing.
						' */
						sendToBack(figure : Figure)
						'/** 
						' * Releases the drawing lock.
						' */
						unlock()
					}
					'DP role: observer
					interface DrawingChangeListener {
						drawingInvalidated(e : DrawingChangeEvent)
						drawingRequestUpdate(e : DrawingChangeEvent)
					}
					JHotDraw_v5.1.CH.ifa.draw.util.Storable <|-- Drawing
					FigureChangeListener <|-- Drawing
					JHotDraw_v5.1.java.io.Serializable <|-- Drawing
					JHotDraw_v5.1.java.util.EventListener <|-- FigureChangeListener
					JHotDraw_v5.1.java.util.EventObject <|-- FigureChangeEvent
					JHotDraw_v5.1.CH.ifa.draw.util.Storable <|-- Figure
					JHotDraw_v5.1.java.lang.Cloneable <|-- Figure
					JHotDraw_v5.1.java.io.Serializable <|-- Figure
					JHotDraw_v5.1.CH.ifa.draw.util.Storable <|-- Locator
					JHotDraw_v5.1.java.io.Serializable <|-- Locator
					JHotDraw_v5.1.java.lang.Cloneable <|-- Locator
					JHotDraw_v5.1.java.io.Serializable <|-- Connector
					JHotDraw_v5.1.CH.ifa.draw.util.Storable <|-- Connector
					Figure <|-- ConnectionFigure
					FigureChangeListener <|-- ConnectionFigure
					JHotDraw_v5.1.java.util.Enumeration <|-- FigureEnumeration
					JHotDraw_v5.1.java.util.EventListener <|-- DrawingChangeListener
					JHotDraw_v5.1.java.util.EventObject <|-- DrawingChangeEvent
					JHotDraw_v5.1.java.awt.image.ImageObserver <|-- DrawingView
					DrawingChangeListener <|-- DrawingView
					JHotDraw_v5.1.java.io.Serializable <|-- Painter
					JHotDraw_v5.1.java.awt.Rectangle "fRectangle" <-- FigureChangeEvent
					JHotDraw_v5.1.java.awt.Rectangle "fgEmptyRectangle" <-- FigureChangeEvent
					JHotDraw_v5.1.java.awt.Rectangle "fRectangle" <-- DrawingChangeEvent
					JavaPrimitiveTypes.int "HANDLESIZE" <-- Handle
					JHotDraw_v5.1.java.lang.String "TYPE" <-- FigureSelection
					JavaPrimitiveTypes.byte "fData 0..*" <-- FigureSelection
				}
				package standard {
					'/** 
					' * The standard implementation of the Drawing interface.
					' * @see Drawing
					' */
					'DP role: concreteSubject
					class StandardDrawing {
						-drawingSerializedDataVersion: JavaPrimitiveTypes.int
						-fDrawingLockHolder: JHotDraw_v5.1.java.lang.Thread
						-fListeners: JHotDraw_v5.1.java.util.Vector
						-{const} serialVersionUID: JavaPrimitiveTypes.long = -2602151437447962046
						'/** 
						' * Constructs the Drawing.
						' */
						<<Create>> StandardDrawing()
						'/** 
						' * Adds a listener for this drawing.
						' */
						addDrawingChangeListener(listener : JHotDraw_v5.1.CH.ifa.draw.framework.DrawingChangeListener)
						basicDisplayBox(p1 : JHotDraw_v5.1.java.awt.Point, p2 : JHotDraw_v5.1.java.awt.Point)
						'/** 
						' * Gets the display box. This is the union of all figures.
						' */
						displayBox(): JHotDraw_v5.1.java.awt.Rectangle
						'/** 
						' * Adds a listener for this drawing.
						' */
						drawingChangeListeners(): JHotDraw_v5.1.java.util.Enumeration
						'/** 
						' * Invalidates a rectangle and merges it with the existing damaged area.
						' * @see FigureChangeListener
						' */
						figureInvalidated(e : JHotDraw_v5.1.CH.ifa.draw.framework.FigureChangeEvent)
						'/** 
						' * Handles a removeFromDrawing request that is passed up the figure container hierarchy.
						' * @see FigureChangeListener
						' */
						figureRequestRemove(e : JHotDraw_v5.1.CH.ifa.draw.framework.FigureChangeEvent)
						'/** 
						' * Forces an update
						' */
						figureRequestUpdate(e : JHotDraw_v5.1.CH.ifa.draw.framework.FigureChangeEvent)
						'/** 
						' * Return's the figure's handles. This is only used when a drawing is nested inside another drawing.
						' */
						handles(): JHotDraw_v5.1.java.util.Vector
						'/** 
						' * Acquires the drawing lock.
						' */
						lock()
						-readObject(s : JHotDraw_v5.1.java.io.ObjectInputStream)
						'/** 
						' * Removes the figure from the drawing and releases it.
						' */
						remove(figure : JHotDraw_v5.1.CH.ifa.draw.framework.Figure): JHotDraw_v5.1.CH.ifa.draw.framework.Figure
						'/** 
						' * Removes a listener from this drawing.
						' */
						removeDrawingChangeListener(listener : JHotDraw_v5.1.CH.ifa.draw.framework.DrawingChangeListener)
						'/** 
						' * Releases the drawing lock.
						' */
						unlock()
					}
					'/** 
					' * The standard implementation of DrawingView.
					' * @see DrawingView
					' * @see Painter
					' * @see Tool
					' */
					'DP role: concreteObserver
					class StandardDrawingView {
						-drawingViewSerializedDataVersion: JavaPrimitiveTypes.int
						-fBackgrounds: JHotDraw_v5.1.java.util.Vector
						-fConstrainer: JHotDraw_v5.1.CH.ifa.draw.framework.PointConstrainer
						-fDamage: JHotDraw_v5.1.java.awt.Rectangle
						-fDrawing: JHotDraw_v5.1.CH.ifa.draw.framework.Drawing
						-fEditor: JHotDraw_v5.1.CH.ifa.draw.framework.DrawingEditor
						-fForegrounds: JHotDraw_v5.1.java.util.Vector
						-fLastClick: JHotDraw_v5.1.java.awt.Point
						-fSelection: JHotDraw_v5.1.java.util.Vector
						-fSelectionHandles: JHotDraw_v5.1.java.util.Vector
						-fUpdateStrategy: JHotDraw_v5.1.CH.ifa.draw.framework.Painter
						-fViewSize: JHotDraw_v5.1.java.awt.Dimension
						-{const} serialVersionUID: JavaPrimitiveTypes.long = -3878153366174603336
						'/** 
						' * Constructs the view.
						' */
						<<Create>> StandardDrawingView(editor : JHotDraw_v5.1.CH.ifa.draw.framework.DrawingEditor, width : JavaPrimitiveTypes.int, height : JavaPrimitiveTypes.int)
						'/** 
						' * Adds a figure to the drawing.
						' * @return the added figure.
						' */
						add(figure : JHotDraw_v5.1.CH.ifa.draw.framework.Figure): JHotDraw_v5.1.CH.ifa.draw.framework.Figure
						'/** 
						' * Adds a vector of figures to the drawing.
						' */
						addAll(figures : JHotDraw_v5.1.java.util.Vector)
						'/** 
						' * Adds a background.
						' */
						addBackground(painter : JHotDraw_v5.1.CH.ifa.draw.framework.Painter)
						'/** 
						' * Adds a foreground.
						' */
						addForeground(painter : JHotDraw_v5.1.CH.ifa.draw.framework.Painter)
						'/** 
						' * Adds a figure to the current selection.
						' */
						addToSelection(figure : JHotDraw_v5.1.CH.ifa.draw.framework.Figure)
						'/** 
						' * Adds a vector of figures to the current selection.
						' */
						addToSelectionAll(figures : JHotDraw_v5.1.java.util.Vector)
						'/** 
						' * Refreshes the drawing if there is some accumulated damage
						' */
						checkDamage()
						-checkMinimumSize()
						'/** 
						' * Clears the current selection.
						' */
						clearSelection()
						'/** 
						' * Constrains a point to the current grid.
						' */
						#constrainPoint(p : JHotDraw_v5.1.java.awt.Point): JHotDraw_v5.1.java.awt.Point
						'/** 
						' * Draws the contents of the drawing view. The view has three layers: background, drawing, handles. The layers are drawn in back to front order.
						' */
						drawAll(g : JHotDraw_v5.1.java.awt.Graphics)
						'/** 
						' * Draws the background. If a background pattern is set it is used to fill the background. Otherwise the background is filled in the background color.
						' */
						drawBackground(g : JHotDraw_v5.1.java.awt.Graphics)
						'/** 
						' * Draws the drawing.
						' */
						drawDrawing(g : JHotDraw_v5.1.java.awt.Graphics)
						'/** 
						' * Draws the currently active handles.
						' */
						drawHandles(g : JHotDraw_v5.1.java.awt.Graphics)
						-drawPainters(g : JHotDraw_v5.1.java.awt.Graphics, v : JHotDraw_v5.1.java.util.Vector)
						'/** 
						' * Gets the drawing.
						' */
						drawing(): JHotDraw_v5.1.CH.ifa.draw.framework.Drawing
						drawingInvalidated(e : JHotDraw_v5.1.CH.ifa.draw.framework.DrawingChangeEvent)
						drawingRequestUpdate(e : JHotDraw_v5.1.CH.ifa.draw.framework.DrawingChangeEvent)
						'/** 
						' * Gets the editor.
						' */
						editor(): JHotDraw_v5.1.CH.ifa.draw.framework.DrawingEditor
						'/** 
						' * Finds a handle at the given coordinates.
						' * @return the hit handle, null if no handle is found.
						' */
						findHandle(x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int): JHotDraw_v5.1.CH.ifa.draw.framework.Handle
						'/** 
						' * Freezes the view by acquiring the drawing lock.
						' * @see Drawing#lock
						' */
						freezeView()
						'/** 
						' * Gets the current constrainer.
						' */
						getConstrainer(): JHotDraw_v5.1.CH.ifa.draw.framework.PointConstrainer
						'/** 
						' * Gets the current selection as a FigureSelection. A FigureSelection can be cut, copied, pasted.
						' */
						getFigureSelection(): JHotDraw_v5.1.CH.ifa.draw.framework.FigureSelection
						'/** 
						' * Gets the minimum dimension of the drawing.
						' */
						getMinimumSize(): JHotDraw_v5.1.java.awt.Dimension
						'/** 
						' * Gets the preferred dimension of the drawing..
						' */
						getPreferredSize(): JHotDraw_v5.1.java.awt.Dimension
						'/** 
						' * Handles cursor keys by moving all the selected figures one grid point in the cursor direction.
						' */
						#handleCursorKey(key : JavaPrimitiveTypes.int)
						isFocusTraversable(): JavaPrimitiveTypes.boolean
						'/** 
						' * Handles key down events. Cursor keys are handled by the view the other key events are delegated to the currently active tool.
						' * @return whether the event was handled.
						' */
						keyPressed(e : JHotDraw_v5.1.java.awt.event.KeyEvent)
						keyReleased(e : JHotDraw_v5.1.java.awt.event.KeyEvent)
						keyTyped(e : JHotDraw_v5.1.java.awt.event.KeyEvent)
						'/** 
						' * Gets the position of the last click inside the view.
						' */
						lastClick(): JHotDraw_v5.1.java.awt.Point
						mouseClicked(e : JHotDraw_v5.1.java.awt.event.MouseEvent)
						'/** 
						' * Handles mouse drag events. The event is delegated to the currently active tool.
						' * @return whether the event was handled.
						' */
						mouseDragged(e : JHotDraw_v5.1.java.awt.event.MouseEvent)
						mouseEntered(e : JHotDraw_v5.1.java.awt.event.MouseEvent)
						mouseExited(e : JHotDraw_v5.1.java.awt.event.MouseEvent)
						'/** 
						' * Handles mouse move events. The event is delegated to the currently active tool.
						' * @return whether the event was handled.
						' */
						mouseMoved(e : JHotDraw_v5.1.java.awt.event.MouseEvent)
						'/** 
						' * Handles mouse down events. The event is delegated to the currently active tool.
						' * @return whether the event was handled.
						' */
						mousePressed(e : JHotDraw_v5.1.java.awt.event.MouseEvent)
						'/** 
						' * Handles mouse up events. The event is delegated to the currently active tool.
						' * @return whether the event was handled.
						' */
						mouseReleased(e : JHotDraw_v5.1.java.awt.event.MouseEvent)
						-moveSelection(dx : JavaPrimitiveTypes.int, dy : JavaPrimitiveTypes.int)
						'/** 
						' * Paints the drawing view. The actual drawing is delegated to the current update strategy.
						' * @see Painter
						' */
						paint(g : JHotDraw_v5.1.java.awt.Graphics)
						-readObject(s : JHotDraw_v5.1.java.io.ObjectInputStream)
						'/** 
						' * Removes a figure from the drawing.
						' * @return the removed figure
						' */
						remove(figure : JHotDraw_v5.1.CH.ifa.draw.framework.Figure): JHotDraw_v5.1.CH.ifa.draw.framework.Figure
						'/** 
						' * Removes a background.
						' */
						removeBackground(painter : JHotDraw_v5.1.CH.ifa.draw.framework.Painter)
						'/** 
						' * Removes a foreground.
						' */
						removeForeground(painter : JHotDraw_v5.1.CH.ifa.draw.framework.Painter)
						'/** 
						' * Removes a figure from the selection.
						' */
						removeFromSelection(figure : JHotDraw_v5.1.CH.ifa.draw.framework.Figure)
						repairDamage()
						'/** 
						' * Gets the currently selected figures.
						' * @return a vector with the selected figures. The vectoris a copy of the current selection.
						' */
						selection(): JHotDraw_v5.1.java.util.Vector
						'/** 
						' * Informs that the current selection changed. By default this event is forwarded to the drawing editor.
						' */
						#selectionChanged()
						'/** 
						' * Gets the number of selected figures.
						' */
						selectionCount(): JavaPrimitiveTypes.int
						'/** 
						' * Gets an enumeration over the currently selected figures.
						' */
						selectionElements(): JHotDraw_v5.1.CH.ifa.draw.framework.FigureEnumeration
						'/** 
						' * Gets an enumeration of the currently active handles.
						' */
						-selectionHandles(): JHotDraw_v5.1.java.util.Enumeration
						'/** 
						' * Gets the currently selected figures in Z order.
						' * @see #selection
						' * @return a vector with the selected figures. The vectoris a copy of the current selection.
						' */
						selectionZOrdered(): JHotDraw_v5.1.java.util.Vector
						'/** 
						' * Sets the grid spacing that is used to constrain points.
						' */
						setConstrainer(c : JHotDraw_v5.1.CH.ifa.draw.framework.PointConstrainer)
						'/** 
						' * Sets the current display update strategy.
						' * @see UpdateStrategy
						' */
						setDisplayUpdate(updateStrategy : JHotDraw_v5.1.CH.ifa.draw.framework.Painter)
						'/** 
						' * Sets and installs another drawing in the view.
						' */
						setDrawing(d : JHotDraw_v5.1.CH.ifa.draw.framework.Drawing)
						'/** 
						' * Sets the view's editor.
						' */
						setEditor(editor : JHotDraw_v5.1.CH.ifa.draw.framework.DrawingEditor)
						'/** 
						' * If a figure isn't selected it is added to the selection. Otherwise it is removed from the selection.
						' */
						toggleSelection(figure : JHotDraw_v5.1.CH.ifa.draw.framework.Figure)
						'/** 
						' * Gets the current tool.
						' */
						tool(): JHotDraw_v5.1.CH.ifa.draw.framework.Tool
						'/** 
						' * Unfreezes the view by releasing the drawing lock.
						' * @see Drawing#unlock
						' */
						unfreezeView()
						'/** 
						' * Updates the drawing view.
						' */
						update(g : JHotDraw_v5.1.java.awt.Graphics)
					}
					CompositeFigure <|-- StandardDrawing
					JHotDraw_v5.1.CH.ifa.draw.framework.Drawing <|.. StandardDrawing
					AbstractFigure <|-- CompositeFigure
					JHotDraw_v5.1.CH.ifa.draw.framework.FigureChangeListener <|.. CompositeFigure
					JHotDraw_v5.1.CH.ifa.draw.framework.Figure <|.. AbstractFigure
					JHotDraw_v5.1.java.awt.Panel <|-- StandardDrawingView
					JHotDraw_v5.1.CH.ifa.draw.framework.DrawingView <|.. StandardDrawingView
					JHotDraw_v5.1.java.awt.event.MouseListener <|.. StandardDrawingView
					JHotDraw_v5.1.java.awt.event.MouseMotionListener <|.. StandardDrawingView
					JHotDraw_v5.1.java.awt.event.KeyListener <|.. StandardDrawingView
					JavaPrimitiveTypes.int "abstractFigureSerializedDataVersion" <-- AbstractFigure
					JHotDraw_v5.1.CH.ifa.draw.framework.FigureChangeListener "fListener" <-- AbstractFigure
					JavaPrimitiveTypes.long "serialVersionUID" <-- AbstractFigure
					JavaPrimitiveTypes.int "compositeFigureSerializedDataVersion" <-- CompositeFigure
					JHotDraw_v5.1.java.util.Vector "fFigures" <-- CompositeFigure
					JavaPrimitiveTypes.long "serialVersionUID" <-- CompositeFigure
					JavaPrimitiveTypes.int "drawingSerializedDataVersion" <-- StandardDrawing
					JHotDraw_v5.1.java.lang.Thread "fDrawingLockHolder" <-- StandardDrawing
					JHotDraw_v5.1.java.util.Vector "fListeners" <-- StandardDrawing
					JavaPrimitiveTypes.long "serialVersionUID" <-- StandardDrawing
					JavaPrimitiveTypes.int "drawingViewSerializedDataVersion" <-- StandardDrawingView
					JHotDraw_v5.1.java.util.Vector "fBackgrounds" <-- StandardDrawingView
					JHotDraw_v5.1.CH.ifa.draw.framework.PointConstrainer "fConstrainer" <-- StandardDrawingView
					JHotDraw_v5.1.java.awt.Rectangle "fDamage" <-- StandardDrawingView
					JHotDraw_v5.1.CH.ifa.draw.framework.Drawing "fDrawing" <-- StandardDrawingView
					JHotDraw_v5.1.CH.ifa.draw.framework.DrawingEditor "fEditor" <-- StandardDrawingView
					JHotDraw_v5.1.java.util.Vector "fForegrounds" <-- StandardDrawingView
					JHotDraw_v5.1.java.awt.Point "fLastClick" <-- StandardDrawingView
					JHotDraw_v5.1.java.util.Vector "fSelection" <-- StandardDrawingView
					JHotDraw_v5.1.java.util.Vector "fSelectionHandles" <-- StandardDrawingView
					JHotDraw_v5.1.CH.ifa.draw.framework.Painter "fUpdateStrategy" <-- StandardDrawingView
					JHotDraw_v5.1.java.awt.Dimension "fViewSize" <-- StandardDrawingView
					JavaPrimitiveTypes.long "serialVersionUID" <-- StandardDrawingView
				}
				package samples {
					package javadraw {
						'DP role: concreteSubject
						class BouncingDrawing {
							-bouncingDrawingSerializedDataVersion: JavaPrimitiveTypes.int
							-{const} serialVersionUID: JavaPrimitiveTypes.long = -8566272817418441758
							<<Create>> BouncingDrawing()
							add(figure : JHotDraw_v5.1.CH.ifa.draw.framework.Figure): JHotDraw_v5.1.CH.ifa.draw.framework.Figure
							animationStep()
							remove(figure : JHotDraw_v5.1.CH.ifa.draw.framework.Figure): JHotDraw_v5.1.CH.ifa.draw.framework.Figure
							replace(figure : JHotDraw_v5.1.CH.ifa.draw.framework.Figure, replacement : JHotDraw_v5.1.CH.ifa.draw.framework.Figure)
						}
						JHotDraw_v5.1.CH.ifa.draw.standard.StandardDrawing <|-- BouncingDrawing
						JHotDraw_v5.1.CH.ifa.draw.util.Animatable <|.. BouncingDrawing
						JavaPrimitiveTypes.int "bouncingDrawingSerializedDataVersion" <-- BouncingDrawing
						JavaPrimitiveTypes.long "serialVersionUID" <-- BouncingDrawing
					}
				}
			}
		}
	}
}
@enduml
