@startuml
'Design pattern State
package "JHotDraw v5.1" as JHotDraw_v5.1 {
	package CH {
		package ifa {
			package draw {
				package framework {
					'/** 
					' * DrawingView renders a Drawing and listens to its changes. It receives user input and delegates it to the current tool. <hr> <b>Design Patterns</b><P> <img src="images/red-ball-small.gif" width=6 height=6 alt=" o "> <b><a href=../pattlets/sld026.htm>Observer</a></b><br> DrawingView observes drawing for changes via the DrawingListener interface.<br> <img src="images/red-ball-small.gif" width=6 height=6 alt=" o "> <b><a href=../pattlets/sld032.htm>State</a></b><br> DrawingView plays the role of the StateContext in the State pattern. Tool is the State.<br> <img src="images/red-ball-small.gif" width=6 height=6 alt=" o "> <b><a href=../pattlets/sld034.htm>Strategy</a></b><br> DrawingView is the StrategyContext in the Strategy pattern with regard to the UpdateStrategy. <br> DrawingView is the StrategyContext for the PointConstrainer.
					' * @see Drawing
					' * @see Painter
					' * @see Tool
					' */
					'DP role: context
					interface DrawingView {
						'/** 
						' * Adds a figure to the drawing.
						' * @return the added figure.
						' */
						add(figure : Figure): Figure
						'/** 
						' * Adds a vector of figures to the drawing.
						' */
						addAll(figures : JHotDraw_v5.1.java.util.Vector)
						'/** 
						' * Adds a figure to the current selection.
						' */
						addToSelection(figure : Figure)
						'/** 
						' * Adds a vector of figures to the current selection.
						' */
						addToSelectionAll(figures : JHotDraw_v5.1.java.util.Vector)
						'/** 
						' * Checks whether the drawing has some accumulated damage
						' */
						checkDamage()
						'/** 
						' * Clears the current selection.
						' */
						clearSelection()
						'/** 
						' * Creates an image with the given dimensions
						' */
						createImage(width : JavaPrimitiveTypes.int, height : JavaPrimitiveTypes.int): JHotDraw_v5.1.java.awt.Image
						'/** 
						' * Draws the contents of the drawing view. The view has three layers: background, drawing, handles. The layers are drawn in back to front order.
						' */
						drawAll(g : JHotDraw_v5.1.java.awt.Graphics)
						'/** 
						' * Draws the background. If a background pattern is set it is used to fill the background. Otherwise the background is filled in the background color.
						' */
						drawBackground(g : JHotDraw_v5.1.java.awt.Graphics)
						'/** 
						' * Draws the drawing.
						' */
						drawDrawing(g : JHotDraw_v5.1.java.awt.Graphics)
						'/** 
						' * Draws the currently active handles.
						' */
						drawHandles(g : JHotDraw_v5.1.java.awt.Graphics)
						'/** 
						' * Gets the drawing.
						' */
						drawing(): Drawing
						'/** 
						' * Gets the editor.
						' */
						editor(): DrawingEditor
						'/** 
						' * Finds a handle at the given coordinates.
						' * @return the hit handle, null if no handle is found.
						' */
						findHandle(x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int): Handle
						'/** 
						' * Freezes the view by acquiring the drawing lock.
						' * @see Drawing#lock
						' */
						freezeView()
						'/** 
						' * Gets the background color of the DrawingView
						' */
						getBackground(): JHotDraw_v5.1.java.awt.Color
						'/** 
						' * Gets the current grid setting.
						' */
						getConstrainer(): PointConstrainer
						'/** 
						' * Gets the current selection as a FigureSelection. A FigureSelection can be cut, copied, pasted.
						' */
						getFigureSelection(): FigureSelection
						'/** 
						' * Gets a graphic to draw into
						' */
						getGraphics(): JHotDraw_v5.1.java.awt.Graphics
						'/** 
						' * Gets the minimum dimension of the drawing.
						' */
						getMinimumSize(): JHotDraw_v5.1.java.awt.Dimension
						'/** 
						' * Gets the preferred dimension of the drawing..
						' */
						getPreferredSize(): JHotDraw_v5.1.java.awt.Dimension
						'/** 
						' * Gets the size of the drawing.
						' */
						getSize(): JHotDraw_v5.1.java.awt.Dimension
						'/** 
						' * Gets the position of the last click inside the view.
						' */
						lastClick(): JHotDraw_v5.1.java.awt.Point
						'/** 
						' * Paints the drawing view. The actual drawing is delegated to the current update strategy.
						' * @see Painter
						' */
						paint(g : JHotDraw_v5.1.java.awt.Graphics)
						'/** 
						' * Removes a figure from the drawing.
						' * @return the removed figure
						' */
						remove(figure : Figure): Figure
						'/** 
						' * Removes a figure from the selection.
						' */
						removeFromSelection(figure : Figure)
						'/** 
						' * Repair the damaged area
						' */
						repairDamage()
						'/** 
						' * Gets the currently selected figures.
						' * @return a vector with the selected figures. The vectoris a copy of the current selection.
						' */
						selection(): JHotDraw_v5.1.java.util.Vector
						'/** 
						' * Gets the number of selected figures.
						' */
						selectionCount(): JavaPrimitiveTypes.int
						'/** 
						' * Gets an enumeration over the currently selected figures.
						' */
						selectionElements(): FigureEnumeration
						'/** 
						' * Gets the currently selected figures in Z order.
						' * @see #selection
						' * @return a vector with the selected figures. The vectoris a copy of the current selection.
						' */
						selectionZOrdered(): JHotDraw_v5.1.java.util.Vector
						'/** 
						' * Gets the background color of the DrawingView
						' */
						setBackground(c : JHotDraw_v5.1.java.awt.Color)
						'/** 
						' * Sets the current point constrainer.
						' */
						setConstrainer(p : PointConstrainer)
						'/** 
						' * Sets the cursor of the DrawingView
						' */
						setCursor(c : JHotDraw_v5.1.java.awt.Cursor)
						'/** 
						' * Sets the current display update strategy.
						' * @see UpdateStrategy
						' */
						setDisplayUpdate(updateStrategy : Painter)
						'/** 
						' * Sets and installs another drawing in the view.
						' */
						setDrawing(d : Drawing)
						'/** 
						' * Sets the view's editor.
						' */
						setEditor(editor : DrawingEditor)
						'/** 
						' * If a figure isn't selected it is added to the selection. Otherwise it is removed from the selection.
						' */
						toggleSelection(figure : Figure)
						'/** 
						' * Gets the current tool.
						' */
						tool(): Tool
						'/** 
						' * Unfreezes the view by releasing the drawing lock.
						' * @see Drawing#unlock
						' */
						unfreezeView()
					}
					'DP role: state
					interface Tool {
						activate()
						deactivate()
						keyDown(evt : JHotDraw_v5.1.java.awt.event.KeyEvent, key : JavaPrimitiveTypes.int)
						mouseDown(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
						mouseDrag(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
						mouseMove(evt : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
						mouseUp(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
					}
					JHotDraw_v5.1.java.awt.image.ImageObserver <|-- DrawingView
					DrawingChangeListener <|-- DrawingView
					JHotDraw_v5.1.java.util.EventListener <|-- DrawingChangeListener
					JHotDraw_v5.1.java.util.EventObject <|-- DrawingChangeEvent
					JHotDraw_v5.1.CH.ifa.draw.util.Storable <|-- Drawing
					FigureChangeListener <|-- Drawing
					JHotDraw_v5.1.java.io.Serializable <|-- Drawing
					JHotDraw_v5.1.java.util.EventListener <|-- FigureChangeListener
					JHotDraw_v5.1.java.util.EventObject <|-- FigureChangeEvent
					JHotDraw_v5.1.CH.ifa.draw.util.Storable <|-- Figure
					JHotDraw_v5.1.java.lang.Cloneable <|-- Figure
					JHotDraw_v5.1.java.io.Serializable <|-- Figure
					JHotDraw_v5.1.CH.ifa.draw.util.Storable <|-- Locator
					JHotDraw_v5.1.java.io.Serializable <|-- Locator
					JHotDraw_v5.1.java.lang.Cloneable <|-- Locator
					JHotDraw_v5.1.java.io.Serializable <|-- Connector
					JHotDraw_v5.1.CH.ifa.draw.util.Storable <|-- Connector
					Figure <|-- ConnectionFigure
					FigureChangeListener <|-- ConnectionFigure
					JHotDraw_v5.1.java.util.Enumeration <|-- FigureEnumeration
					JHotDraw_v5.1.java.io.Serializable <|-- Painter
					JHotDraw_v5.1.java.awt.Rectangle "fRectangle" <-- DrawingChangeEvent
					JHotDraw_v5.1.java.awt.Rectangle "fRectangle" <-- FigureChangeEvent
					JHotDraw_v5.1.java.awt.Rectangle "fgEmptyRectangle" <-- FigureChangeEvent
					JavaPrimitiveTypes.int "HANDLESIZE" <-- Handle
					JHotDraw_v5.1.java.lang.String "TYPE" <-- FigureSelection
					JavaPrimitiveTypes.byte "fData 0..*" <-- FigureSelection
				}
				package standard {
					'/** 
					' * Default implementation support for Tools.
					' * @see DrawingView
					' * @see Tool
					' */
					'DP role: concreteState
					class AbstractTool {
						#fAnchorX: JavaPrimitiveTypes.int
						#fAnchorY: JavaPrimitiveTypes.int
						#fView: JHotDraw_v5.1.CH.ifa.draw.framework.DrawingView
						'/** 
						' * Constructs a tool for the given view.
						' */
						<<Create>> AbstractTool(itsView : JHotDraw_v5.1.CH.ifa.draw.framework.DrawingView)
						'/** 
						' * Activates the tool for the given view. This method is called whenever the user switches to this tool. Use this method to reinitialize a tool.
						' */
						activate()
						'/** 
						' * Deactivates the tool. This method is called whenever the user switches to another tool. Use this method to do some clean-up when the tool is switched. Subclassers should always call super.deactivate.
						' */
						deactivate()
						'/** 
						' * Gets the tool's drawing.
						' */
						drawing(): JHotDraw_v5.1.CH.ifa.draw.framework.Drawing
						'/** 
						' * Gets the tool's editor.
						' */
						editor(): JHotDraw_v5.1.CH.ifa.draw.framework.DrawingEditor
						'/** 
						' * Handles key down events in the drawing view.
						' */
						keyDown(evt : JHotDraw_v5.1.java.awt.event.KeyEvent, key : JavaPrimitiveTypes.int)
						'/** 
						' * Handles mouse down events in the drawing view.
						' */
						mouseDown(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
						'/** 
						' * Handles mouse drag events in the drawing view.
						' */
						mouseDrag(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
						'/** 
						' * Handles mouse moves (if the mouse button is up).
						' */
						mouseMove(evt : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
						'/** 
						' * Handles mouse up in the drawing view.
						' */
						mouseUp(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
						'/** 
						' * Gets the tool's view.
						' */
						view(): JHotDraw_v5.1.CH.ifa.draw.framework.DrawingView
					}
					'/** 
					' * A tool that can be used to connect figures, to split connections, and to join two segments of a connection. ConnectionTools turns the visibility of the Connectors on when it enters a figure. The connection object to be created is specified by a prototype. <hr> <b>Design Patterns</b><P> <img src="images/red-ball-small.gif" width=6 height=6 alt=" o "> <b><a href=../pattlets/sld029.htm>Prototype</a></b><br> ConnectionTools creates the connection by cloning a prototype. <hr>
					' * @see ConnectionFigure
					' * @see Object#clone
					' */
					'DP role: concreteState
					class ConnectionTool {
						-fConnection: JHotDraw_v5.1.CH.ifa.draw.framework.ConnectionFigure
						-fConnectorTarget: JHotDraw_v5.1.CH.ifa.draw.framework.Connector
						-fEditedConnection: JHotDraw_v5.1.CH.ifa.draw.framework.ConnectionFigure
						-fEndConnector: JHotDraw_v5.1.CH.ifa.draw.framework.Connector
						-fPrototype: JHotDraw_v5.1.CH.ifa.draw.framework.ConnectionFigure
						-fSplitPoint: JavaPrimitiveTypes.int
						-fStartConnector: JHotDraw_v5.1.CH.ifa.draw.framework.Connector
						-fTarget: JHotDraw_v5.1.CH.ifa.draw.framework.Figure
						<<Create>> ConnectionTool(view : JHotDraw_v5.1.CH.ifa.draw.framework.DrawingView, prototype : JHotDraw_v5.1.CH.ifa.draw.framework.ConnectionFigure)
						'/** 
						' * Creates the ConnectionFigure. By default the figure prototype is cloned.
						' */
						#createConnection(): JHotDraw_v5.1.CH.ifa.draw.framework.ConnectionFigure
						'/** 
						' * Gets the currently created figure
						' */
						#createdFigure(): JHotDraw_v5.1.CH.ifa.draw.framework.ConnectionFigure
						deactivate()
						-findConnectableFigure(x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int, drawing : JHotDraw_v5.1.CH.ifa.draw.framework.Drawing): JHotDraw_v5.1.CH.ifa.draw.framework.Figure
						'/** 
						' * Finds an existing connection figure.
						' */
						#findConnection(x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int, drawing : JHotDraw_v5.1.CH.ifa.draw.framework.Drawing): JHotDraw_v5.1.CH.ifa.draw.framework.ConnectionFigure
						'/** 
						' * Finds a connection start figure.
						' */
						#findConnectionStart(x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int, drawing : JHotDraw_v5.1.CH.ifa.draw.framework.Drawing): JHotDraw_v5.1.CH.ifa.draw.framework.Figure
						-findConnector(x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int, f : JHotDraw_v5.1.CH.ifa.draw.framework.Figure): JHotDraw_v5.1.CH.ifa.draw.framework.Connector
						'/** 
						' * Finds a connectable figure target.
						' */
						#findSource(x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int, drawing : JHotDraw_v5.1.CH.ifa.draw.framework.Drawing): JHotDraw_v5.1.CH.ifa.draw.framework.Figure
						'/** 
						' * Finds a connectable figure target.
						' */
						#findTarget(x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int, drawing : JHotDraw_v5.1.CH.ifa.draw.framework.Drawing): JHotDraw_v5.1.CH.ifa.draw.framework.Figure
						#getEndConnector(): JHotDraw_v5.1.CH.ifa.draw.framework.Connector
						#getStartConnector(): JHotDraw_v5.1.CH.ifa.draw.framework.Connector
						#getTarget(): JHotDraw_v5.1.CH.ifa.draw.framework.Connector
						'/** 
						' * Manipulates connections in a context dependent way. If the mouse down hits a figure start a new connection. If the mousedown hits a connection split a segment or join two segments.
						' */
						mouseDown(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
						'/** 
						' * Adjust the created connection or split segment.
						' */
						mouseDrag(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
						'/** 
						' * Handles mouse move events in the drawing view.
						' */
						mouseMove(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
						'/** 
						' * Connects the figures if the mouse is released over another figure.
						' */
						mouseUp(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
						#trackConnectors(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
					}
					'/** 
					' * A tool to create new figures. The figure to be created is specified by a prototype. <hr> <b>Design Patterns</b><P> <img src="images/red-ball-small.gif" width=6 height=6 alt=" o "> <b><a href=../pattlets/sld029.htm>Prototype</a></b><br> CreationTool creates new figures by cloning a prototype. <hr>
					' * @see Figure
					' * @see Object#clone
					' */
					'DP role: concreteState
					class CreationTool {
						-fAnchorPoint: JHotDraw_v5.1.java.awt.Point
						-fCreatedFigure: JHotDraw_v5.1.CH.ifa.draw.framework.Figure
						-fPrototype: JHotDraw_v5.1.CH.ifa.draw.framework.Figure
						'/** 
						' * Initializes a CreationTool with the given prototype.
						' */
						<<Create>> CreationTool(view : JHotDraw_v5.1.CH.ifa.draw.framework.DrawingView, prototype : JHotDraw_v5.1.CH.ifa.draw.framework.Figure)
						'/** 
						' * Constructs a CreationTool without a prototype. This is for subclassers overriding createFigure.
						' */
						#<<Create>> CreationTool(view : JHotDraw_v5.1.CH.ifa.draw.framework.DrawingView)
						'/** 
						' * Sets the cross hair cursor.
						' */
						activate()
						'/** 
						' * Creates a new figure by cloning the prototype.
						' */
						#createFigure(): JHotDraw_v5.1.CH.ifa.draw.framework.Figure
						'/** 
						' * Gets the currently created figure
						' */
						#createdFigure(): JHotDraw_v5.1.CH.ifa.draw.framework.Figure
						'/** 
						' * Creates a new figure by cloning the prototype.
						' */
						mouseDown(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
						'/** 
						' * Adjusts the extent of the created figure
						' */
						mouseDrag(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
						'/** 
						' * Checks if the created figure is empty. If it is, the figure is removed from the drawing.
						' * @see Figure#isEmpty
						' */
						mouseUp(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
					}
					'/** 
					' * DragTracker implements the dragging of the clicked figure.
					' * @see SelectionTool
					' */
					'DP role: concreteState
					class DragTracker {
						-fAnchorFigure: JHotDraw_v5.1.CH.ifa.draw.framework.Figure
						-fLastX: JavaPrimitiveTypes.int
						-fLastY: JavaPrimitiveTypes.int
						-fMoved: JavaPrimitiveTypes.boolean
						<<Create>> DragTracker(view : JHotDraw_v5.1.CH.ifa.draw.framework.DrawingView, anchor : JHotDraw_v5.1.CH.ifa.draw.framework.Figure)
						mouseDown(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
						mouseDrag(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
					}
					'/** 
					' * HandleTracker implements interactions with the handles of a Figure.
					' * @see SelectionTool
					' */
					'DP role: concreteState
					class HandleTracker {
						-fAnchorHandle: JHotDraw_v5.1.CH.ifa.draw.framework.Handle
						<<Create>> HandleTracker(view : JHotDraw_v5.1.CH.ifa.draw.framework.DrawingView, anchorHandle : JHotDraw_v5.1.CH.ifa.draw.framework.Handle)
						mouseDown(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
						mouseDrag(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
						mouseUp(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
					}
					'/** 
					' * SelectAreaTracker implements a rubberband selection of an area.
					' */
					'DP role: concreteState
					class SelectAreaTracker {
						-fSelectGroup: JHotDraw_v5.1.java.awt.Rectangle
						<<Create>> SelectAreaTracker(view : JHotDraw_v5.1.CH.ifa.draw.framework.DrawingView)
						-drawXORRect(r : JHotDraw_v5.1.java.awt.Rectangle)
						-eraseRubberBand()
						mouseDown(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
						mouseDrag(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
						mouseUp(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
						-rubberBand(x1 : JavaPrimitiveTypes.int, y1 : JavaPrimitiveTypes.int, x2 : JavaPrimitiveTypes.int, y2 : JavaPrimitiveTypes.int)
						-selectGroup(toggle : JavaPrimitiveTypes.boolean)
					}
					'/** 
					' * Tool to select and manipulate figures. A selection tool is in one of three states, e.g., background selection, figure selection, handle manipulation. The different states are handled by different child tools. <hr> <b>Design Patterns</b><P> <img src="images/red-ball-small.gif" width=6 height=6 alt=" o "> <b><a href=../pattlets/sld032.htm>State</a></b><br> SelectionTool is the StateContext and child is the State. The SelectionTool delegates state specific behavior to its current child tool. <hr>
					' */
					'DP role: concreteState
					class SelectionTool {
						-fChild: JHotDraw_v5.1.CH.ifa.draw.framework.Tool
						<<Create>> SelectionTool(view : JHotDraw_v5.1.CH.ifa.draw.framework.DrawingView)
						'/** 
						' * Factory method to create an area tracker. It is used to select an area.
						' */
						#createAreaTracker(view : JHotDraw_v5.1.CH.ifa.draw.framework.DrawingView): JHotDraw_v5.1.CH.ifa.draw.framework.Tool
						'/** 
						' * Factory method to create a Drag tracker. It is used to drag a figure.
						' */
						#createDragTracker(view : JHotDraw_v5.1.CH.ifa.draw.framework.DrawingView, f : JHotDraw_v5.1.CH.ifa.draw.framework.Figure): JHotDraw_v5.1.CH.ifa.draw.framework.Tool
						'/** 
						' * Factory method to create a Handle tracker. It is used to track a handle.
						' */
						#createHandleTracker(view : JHotDraw_v5.1.CH.ifa.draw.framework.DrawingView, handle : JHotDraw_v5.1.CH.ifa.draw.framework.Handle): JHotDraw_v5.1.CH.ifa.draw.framework.Tool
						'/** 
						' * Handles mouse down events and starts the corresponding tracker.
						' */
						mouseDown(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
						'/** 
						' * Handles mouse drag events. The events are forwarded to the current tracker.
						' */
						mouseDrag(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
						'/** 
						' * Handles mouse up events. The events are forwarded to the current tracker.
						' */
						mouseUp(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
					}
					JHotDraw_v5.1.CH.ifa.draw.framework.Tool <|.. AbstractTool
					AbstractTool <|-- ActionTool
					AbstractTool <|-- ConnectionTool
					AbstractTool <|-- CreationTool
					AbstractTool <|-- DragTracker
					AbstractTool <|-- HandleTracker
					JHotDraw_v5.1.CH.ifa.draw.framework.Figure <|.. AbstractFigure
					AbstractTool <|-- SelectAreaTracker
					AbstractTool <|-- SelectionTool
					JavaPrimitiveTypes.int "fAnchorX" <-- AbstractTool
					JavaPrimitiveTypes.int "fAnchorY" <-- AbstractTool
					JHotDraw_v5.1.CH.ifa.draw.framework.DrawingView "fView" <-- AbstractTool
					JHotDraw_v5.1.CH.ifa.draw.framework.ConnectionFigure "fConnection" <-- ConnectionTool
					JHotDraw_v5.1.CH.ifa.draw.framework.Connector "fConnectorTarget" <-- ConnectionTool
					JHotDraw_v5.1.CH.ifa.draw.framework.ConnectionFigure "fEditedConnection" <-- ConnectionTool
					JHotDraw_v5.1.CH.ifa.draw.framework.Connector "fEndConnector" <-- ConnectionTool
					JHotDraw_v5.1.CH.ifa.draw.framework.ConnectionFigure "fPrototype" <-- ConnectionTool
					JavaPrimitiveTypes.int "fSplitPoint" <-- ConnectionTool
					JHotDraw_v5.1.CH.ifa.draw.framework.Connector "fStartConnector" <-- ConnectionTool
					JHotDraw_v5.1.CH.ifa.draw.framework.Figure "fTarget" <-- ConnectionTool
					JHotDraw_v5.1.java.awt.Point "fAnchorPoint" <-- CreationTool
					JHotDraw_v5.1.CH.ifa.draw.framework.Figure "fCreatedFigure" <-- CreationTool
					JHotDraw_v5.1.CH.ifa.draw.framework.Figure "fPrototype" <-- CreationTool
					JHotDraw_v5.1.CH.ifa.draw.framework.Figure "fAnchorFigure" <-- DragTracker
					JavaPrimitiveTypes.int "fLastX" <-- DragTracker
					JavaPrimitiveTypes.int "fLastY" <-- DragTracker
					JavaPrimitiveTypes.boolean "fMoved" <-- DragTracker
					JHotDraw_v5.1.CH.ifa.draw.framework.Handle "fAnchorHandle" <-- HandleTracker
					JavaPrimitiveTypes.int "abstractFigureSerializedDataVersion" <-- AbstractFigure
					JHotDraw_v5.1.CH.ifa.draw.framework.FigureChangeListener "fListener" <-- AbstractFigure
					JavaPrimitiveTypes.long "serialVersionUID" <-- AbstractFigure
					JHotDraw_v5.1.java.awt.Rectangle "fSelectGroup" <-- SelectAreaTracker
					JHotDraw_v5.1.CH.ifa.draw.framework.Tool "fChild" <-- SelectionTool
				}
				package figures {
					'/** 
					' * BorderTool decorates the clicked figure with a BorderDecorator.
					' * @see BorderDecorator
					' */
					'DP role: concreteState
					class BorderTool {
						<<Create>> BorderTool(view : JHotDraw_v5.1.CH.ifa.draw.framework.DrawingView)
						'/** 
						' * Decorates the clicked figure with a border.
						' */
						action(figure : JHotDraw_v5.1.CH.ifa.draw.framework.Figure)
					}
					'/** 
					' * Tool to create new or edit existing text figures. The editing behavior is implemented by overlaying the Figure providing the text with a FloatingTextField.<p> A tool interaction is done once a Figure that is not a TextHolder is clicked.
					' * @see TextHolder
					' * @see FloatingTextField
					' */
					'DP role: concreteState
					class TextTool {
						-fTextField: JHotDraw_v5.1.CH.ifa.draw.util.FloatingTextField
						-fTypingTarget: JHotDraw_v5.1.CH.ifa.draw.standard.TextHolder
						<<Create>> TextTool(view : JHotDraw_v5.1.CH.ifa.draw.framework.DrawingView, prototype : JHotDraw_v5.1.CH.ifa.draw.framework.Figure)
						'/** 
						' * Sets the text cursor.
						' */
						activate()
						#beginEdit(figure : JHotDraw_v5.1.CH.ifa.draw.standard.TextHolder)
						'/** 
						' * Terminates the editing of a text figure.
						' */
						deactivate()
						#endEdit()
						-fieldBounds(figure : JHotDraw_v5.1.CH.ifa.draw.standard.TextHolder): JHotDraw_v5.1.java.awt.Rectangle
						'/** 
						' * If the pressed figure is a TextHolder it can be edited otherwise a new text figure is created.
						' */
						mouseDown(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
						mouseDrag(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
						mouseUp(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
					}
					'/** 
					' * Tool to create new or edit existing text figures. A new text figure is connected with the clicked figure.
					' * @see TextHolder
					' */
					'DP role: concreteState
					class ConnectedTextTool {
						fConnected: JavaPrimitiveTypes.boolean
						<<Create>> ConnectedTextTool(view : JHotDraw_v5.1.CH.ifa.draw.framework.DrawingView, prototype : JHotDraw_v5.1.CH.ifa.draw.framework.Figure)
						'/** 
						' * If the pressed figure is a TextHolder it can be edited otherwise a new text figure is created.
						' */
						activate()
						'/** 
						' * If the pressed figure is a TextHolder it can be edited otherwise a new text figure is created.
						' */
						mouseDown(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
					}
					'/** 
					' * Tool to scribble a PolyLineFigure
					' * @see PolyLineFigure
					' */
					'DP role: concreteState
					class ScribbleTool {
						-fLastX: JavaPrimitiveTypes.int
						-fLastY: JavaPrimitiveTypes.int
						-fScribble: PolyLineFigure
						<<Create>> ScribbleTool(view : JHotDraw_v5.1.CH.ifa.draw.framework.DrawingView)
						activate()
						deactivate()
						mouseDown(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
						mouseDrag(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
						-point(x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
					}
					JHotDraw_v5.1.CH.ifa.draw.standard.ActionTool <|-- BorderTool
					JHotDraw_v5.1.CH.ifa.draw.standard.CreationTool <|-- TextTool
					TextTool <|-- ConnectedTextTool
					JHotDraw_v5.1.CH.ifa.draw.standard.AbstractFigure <|-- AttributeFigure
					JHotDraw_v5.1.java.lang.Cloneable <|.. FigureAttributes
					JHotDraw_v5.1.java.io.Serializable <|.. FigureAttributes
					JHotDraw_v5.1.CH.ifa.draw.standard.AbstractTool <|-- ScribbleTool
					JHotDraw_v5.1.CH.ifa.draw.standard.AbstractFigure <|-- PolyLineFigure
					JHotDraw_v5.1.CH.ifa.draw.util.Storable <|-- LineDecoration
					JHotDraw_v5.1.java.lang.Cloneable <|-- LineDecoration
					JHotDraw_v5.1.java.io.Serializable <|-- LineDecoration
					JHotDraw_v5.1.CH.ifa.draw.util.FloatingTextField "fTextField" <-- TextTool
					JHotDraw_v5.1.CH.ifa.draw.standard.TextHolder "fTypingTarget" <-- TextTool
					JavaPrimitiveTypes.boolean "fConnected" <-- ConnectedTextTool
					JavaPrimitiveTypes.int "attributeFigureSerializedDataVersion" <-- AttributeFigure
					JHotDraw_v5.1.java.util.Hashtable "fMap" <-- FigureAttributes
					JavaPrimitiveTypes.int "figureAttributesSerializedDataVersion" <-- FigureAttributes
					JavaPrimitiveTypes.long "serialVersionUID" <-- FigureAttributes
					FigureAttributes "fAttributes" <-- AttributeFigure
					FigureAttributes "fgDefaultAttributes" <-- AttributeFigure
					JavaPrimitiveTypes.long "serialVersionUID" <-- AttributeFigure
					JavaPrimitiveTypes.int "fLastX" <-- ScribbleTool
					JavaPrimitiveTypes.int "fLastY" <-- ScribbleTool
					JavaPrimitiveTypes.int "ARROW_TIP_BOTH" <-- PolyLineFigure
					JavaPrimitiveTypes.int "ARROW_TIP_END" <-- PolyLineFigure
					JavaPrimitiveTypes.int "ARROW_TIP_NONE" <-- PolyLineFigure
					JavaPrimitiveTypes.int "ARROW_TIP_START" <-- PolyLineFigure
					LineDecoration "fEndDecoration" <-- PolyLineFigure
					JHotDraw_v5.1.java.awt.Color "fFrameColor" <-- PolyLineFigure
					JHotDraw_v5.1.java.util.Vector "fPoints" <-- PolyLineFigure
					LineDecoration "fStartDecoration" <-- PolyLineFigure
					JavaPrimitiveTypes.int "polyLineFigureSerializedDataVersion" <-- PolyLineFigure
					JavaPrimitiveTypes.long "serialVersionUID" <-- PolyLineFigure
					PolyLineFigure "fScribble" <-- ScribbleTool
				}
				package samples {
					package pert {
						'/** 
						' * A more efficient version of the generic Pert creation tool that is not based on cloning.
						' */
						'DP role: concreteState
						class PertFigureCreationTool {
							<<Create>> PertFigureCreationTool(view : JHotDraw_v5.1.CH.ifa.draw.framework.DrawingView)
							'/** 
							' * Creates a new PertFigure.
							' */
							#createFigure(): JHotDraw_v5.1.CH.ifa.draw.framework.Figure
						}
						JHotDraw_v5.1.CH.ifa.draw.standard.CreationTool <|-- PertFigureCreationTool
					}
					package javadraw {
						'DP role: concreteState
						class FollowURLTool {
							-fApplet: JHotDraw_v5.1.java.applet.Applet
							<<Create>> FollowURLTool(view : JHotDraw_v5.1.CH.ifa.draw.framework.DrawingView, applet : JHotDraw_v5.1.java.applet.Applet)
							'/** 
							' * Handles mouse move events in the drawing view.
							' */
							mouseMove(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
							'/** 
							' * Handles mouse up in the drawing view.
							' */
							mouseUp(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
						}
						'/** 
						' * A SelectionTool that interprets double clicks to inspect the clicked figure
						' */
						'DP role: concreteState
						class MySelectionTool {
							<<Create>> MySelectionTool(view : JHotDraw_v5.1.CH.ifa.draw.framework.DrawingView)
							#inspectFigure(f : JHotDraw_v5.1.CH.ifa.draw.framework.Figure)
							'/** 
							' * Handles mouse down events and starts the corresponding tracker.
							' */
							mouseDown(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
						}
						'/** 
						' * A tool to attach URLs to figures. The URLs are stored in the figure's "URL" attribute. The URL text is entered with a FloatingTextField.
						' * @see FloatingTextField
						' */
						'DP role: concreteState
						class URLTool {
							-fTextField: JHotDraw_v5.1.CH.ifa.draw.util.FloatingTextField
							-fURLTarget: JHotDraw_v5.1.CH.ifa.draw.framework.Figure
							<<Create>> URLTool(view : JHotDraw_v5.1.CH.ifa.draw.framework.DrawingView)
							-beginEdit(figure : JHotDraw_v5.1.CH.ifa.draw.framework.Figure)
							deactivate(view : JHotDraw_v5.1.CH.ifa.draw.framework.DrawingView)
							endAction(e : JHotDraw_v5.1.java.awt.event.ActionEvent)
							-endEdit()
							-fieldBounds(figure : JHotDraw_v5.1.CH.ifa.draw.framework.Figure): JHotDraw_v5.1.java.awt.Rectangle
							-getURL(figure : JHotDraw_v5.1.CH.ifa.draw.framework.Figure): JHotDraw_v5.1.java.lang.String
							mouseDown(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
							mouseUp(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
							-setURL(figure : JHotDraw_v5.1.CH.ifa.draw.framework.Figure, url : JHotDraw_v5.1.java.lang.String)
						}
						JHotDraw_v5.1.CH.ifa.draw.standard.AbstractTool <|-- FollowURLTool
						JHotDraw_v5.1.CH.ifa.draw.standard.SelectionTool <|-- MySelectionTool
						JHotDraw_v5.1.CH.ifa.draw.standard.AbstractTool <|-- URLTool
						JHotDraw_v5.1.java.applet.Applet "fApplet" <-- FollowURLTool
						JHotDraw_v5.1.CH.ifa.draw.util.FloatingTextField "fTextField" <-- URLTool
						JHotDraw_v5.1.CH.ifa.draw.framework.Figure "fURLTarget" <-- URLTool
					}
				}
				package contrib {
					'/** 
					' */
					'DP role: concreteState
					class PolygonTool {
						-fLastX: JavaPrimitiveTypes.int
						-fLastY: JavaPrimitiveTypes.int
						-fPolygon: PolygonFigure
						<<Create>> PolygonTool(view : JHotDraw_v5.1.CH.ifa.draw.framework.DrawingView)
						activate()
						-addPoint(x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
						deactivate()
						mouseDown(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
						mouseDrag(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
						mouseMove(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
						mouseUp(e : JHotDraw_v5.1.java.awt.event.MouseEvent, x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
					}
					JHotDraw_v5.1.CH.ifa.draw.standard.AbstractTool <|-- PolygonTool
					JHotDraw_v5.1.CH.ifa.draw.figures.AttributeFigure <|-- PolygonFigure
					JavaPrimitiveTypes.int "fLastX" <-- PolygonTool
					JavaPrimitiveTypes.int "fLastY" <-- PolygonTool
					JavaPrimitiveTypes.int "TOO_CLOSE" <-- PolygonFigure
					JHotDraw_v5.1.java.awt.Polygon "fPoly" <-- PolygonFigure
					JavaPrimitiveTypes.int "polygonFigureSerializedDataVersion" <-- PolygonFigure
					JavaPrimitiveTypes.long "serialVersionUID" <-- PolygonFigure
					PolygonFigure "fPolygon" <-- PolygonTool
				}
			}
		}
	}
}
@enduml
