@startuml
package dpd_jdt {
	package Prototype {
		package nonprototype {
			'The implementation of hierarchy nodes factory for the java loader.
			'@author Petr Hamernik
			class JavaElementNodeFactory {
				-{const} CLASS_ACTIONS: SystemAction [*]
				{const} DEFAULT: DefaultFactory
				-{const} DEFAULT_ACTIONS: SystemAction [*]
				-FACTORY_GETTER_NODE: Node
				-{const} INITIALIZER_ACTIONS: SystemAction [*]
				-tree: JavaPrimitiveTypes.boolean
				'Creates new factory.
				<<Create>> JavaElementNodeFactory()
				#createClassChildren(element : ClassElement): Children
				'Returns the node asociated with specified element.
				'@return ElementNode
				createClassNode(element : ClassElement): Node
				'Returns the node asociated with specified element.
				'@return ElementNode
				createConstructorNode(element : ConstructorElement): Node
				'Returns the node asociated with specified element.
				'@return ElementNode
				createFieldNode(element : FieldElement): Node
				'Returns the node asociated with specified element.
				'@return ElementNode
				createInitializerNode(element : InitializerElement): Node
				'Returns the node asociated with specified element.
				'@return ElementNode
				createMethodNode(element : MethodElement): Node
				'Returns true if generate nodes for tree.
				'@returns true if generate nodes for tree.
				getGenerateForTree(): JavaPrimitiveTypes.boolean
				'If true generate nodes for tree.
				setGenerateForTree(tree : JavaPrimitiveTypes.boolean)
			}
		}
	}
	Prototype.nonprototype.DefaultFactory <|-- Prototype.nonprototype.JavaElementNodeFactory
	Prototype.nonprototype.ElementNodeFactory <|.. Prototype.nonprototype.DefaultFactory
	Prototype.nonprototype.IconStrings <|-- Prototype.nonprototype.DefaultFactory
	Prototype.nonprototype.SystemAction "CATEGORY_ACTIONS 0..*" <-- Prototype.nonprototype.DefaultFactory
	java.lang.String "CATEGORY_ICONS 0..*" <-- Prototype.nonprototype.DefaultFactory
	JavaPrimitiveTypes.int "FILTERS 0..*" <-- Prototype.nonprototype.DefaultFactory
	java.lang.String "NAMES 0..*" <-- Prototype.nonprototype.DefaultFactory
	java.lang.String "SHORTDESCRS 0..*" <-- Prototype.nonprototype.DefaultFactory
	JavaPrimitiveTypes.boolean "writeable" <-- Prototype.nonprototype.DefaultFactory
	Prototype.nonprototype.ClassElement "element" <-- Prototype.nonprototype.DefaultFactory.ElementCategoryNode
	JavaPrimitiveTypes.int "newTypeIndex" <-- Prototype.nonprototype.DefaultFactory.ElementCategoryNode
	Prototype.nonprototype.SystemAction "CLASS_ACTIONS 0..*" <-- Prototype.nonprototype.JavaElementNodeFactory
	Prototype.nonprototype.DefaultFactory "DEFAULT" <-- Prototype.nonprototype.JavaElementNodeFactory
	Prototype.nonprototype.SystemAction "DEFAULT_ACTIONS 0..*" <-- Prototype.nonprototype.JavaElementNodeFactory
	Prototype.nonprototype.Node "FACTORY_GETTER_NODE" <-- Prototype.nonprototype.JavaElementNodeFactory
	Prototype.nonprototype.SystemAction "INITIALIZER_ACTIONS 0..*" <-- Prototype.nonprototype.JavaElementNodeFactory
	JavaPrimitiveTypes.boolean "tree" <-- Prototype.nonprototype.JavaElementNodeFactory
}
@enduml
