@startuml
package dpd_jdt {
	package Res {
		package name {
			'A triangle with same dimensions as its enclosing rectangle, and apex at any of 8 places
			class TriangleFigure {
				#fRotation: JavaPrimitiveTypes.int
				{static} rotations: JavaPrimitiveTypes.double [*]
				<<Create>> TriangleFigure()
				<<Create>> TriangleFigure(origin : java.awt.Point, corner : java.awt.Point)
				center(): java.awt.Point
				chop(p : java.awt.Point): java.awt.Point
				clone(): java.lang.Object
				connectionInsets(): java.awt.Insets
				containsPoint(x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int): JavaPrimitiveTypes.boolean
				draw(g : java.awt.Graphics)
				handles(): java.util.Vector
				'Return the polygon describing the triangle
				polygon(): java.awt.Polygon
				read(dr : StorableInput)
				rotate(angle : JavaPrimitiveTypes.double)
				write(dw : StorableOutput)
			}
		}
	}
	Res.name.RectangleFigure <|-- Res.name.TriangleFigure
	Res.name.AttributeFigure <|-- Res.name.RectangleFigure
	java.awt.Rectangle "fDisplayBox" <-- Res.name.RectangleFigure
	JavaPrimitiveTypes.int "rectangleFigureSerializedDataVersion" <-- Res.name.RectangleFigure
	JavaPrimitiveTypes.long "serialVersionUID" <-- Res.name.RectangleFigure
	JavaPrimitiveTypes.int "fRotation" <-- Res.name.TriangleFigure
	JavaPrimitiveTypes.double "rotations 0..*" <-- Res.name.TriangleFigure
}
@enduml
