@startuml
package dpd_jdt {
	package context {
		package name {
			'Description of the Class
			'@author    Chris Seguin
			class Menucontext {
				<<Create>> Menucontext()
				'Description of the Method
				'@return    Description of the Returned Value
				{static} build(): ActionGroup
				'Description of the Method
				'@return    Description of the Returned Value
				{static} buildField(): ActionGroup
				'Description of the Method
				'@return    Description of the Returned Value
				{static} buildMethod(): ActionGroup
				'Description of the Method
				'@return    Description of the Returned Value
				-{static} buildType(): ActionGroup
			}
		}
	}
}
@enduml
