@startuml
package dpd_jdt {
	package Builder {
		package nonbuilder {
			'A line figure.
			class LineFigure {
				-lineFigureSerializedDataVersion: JavaPrimitiveTypes.int
				-{const} serialVersionUID: JavaPrimitiveTypes.long = 511503575249212371
				'Constructs a LineFigure with both start and end set to Point(0,0).
				<<Create>> LineFigure()
				basicDisplayBox(origin : java.awt.Point, corner : java.awt.Point)
				'Gets a copy of the end point.
				endPoint(): java.awt.Point
				'Sets the end point.
				endPoint(x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
				'Sets the start and end point.
				setPoints(start : java.awt.Point, end : java.awt.Point)
				'Gets a copy of the start point.
				startPoint(): java.awt.Point
				'Sets the start point.
				startPoint(x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
			}
		}
	}
	Builder.nonbuilder.PolyLineFigure <|-- Builder.nonbuilder.LineFigure
	Builder.nonbuilder.AbstractFigure <|-- Builder.nonbuilder.PolyLineFigure
	JavaPrimitiveTypes.int "ARROW_TIP_BOTH" <-- Builder.nonbuilder.PolyLineFigure
	JavaPrimitiveTypes.int "ARROW_TIP_END" <-- Builder.nonbuilder.PolyLineFigure
	JavaPrimitiveTypes.int "ARROW_TIP_NONE" <-- Builder.nonbuilder.PolyLineFigure
	JavaPrimitiveTypes.int "ARROW_TIP_START" <-- Builder.nonbuilder.PolyLineFigure
	Builder.nonbuilder.LineDecoration "fEndDecoration" <-- Builder.nonbuilder.PolyLineFigure
	java.awt.Color "fFrameColor" <-- Builder.nonbuilder.PolyLineFigure
	java.util.Vector "fPoints" <-- Builder.nonbuilder.PolyLineFigure
	Builder.nonbuilder.LineDecoration "fStartDecoration" <-- Builder.nonbuilder.PolyLineFigure
	JavaPrimitiveTypes.int "polyLineFigureSerializedDataVersion" <-- Builder.nonbuilder.PolyLineFigure
	JavaPrimitiveTypes.long "serialVersionUID" <-- Builder.nonbuilder.PolyLineFigure
	JavaPrimitiveTypes.int "lineFigureSerializedDataVersion" <-- Builder.nonbuilder.LineFigure
	JavaPrimitiveTypes.long "serialVersionUID" <-- Builder.nonbuilder.LineFigure
}
@enduml
