@startuml
package dpd_jdt {
	package Builder {
		package nonbuilder {
			class BouncingDrawing {
				-bouncingDrawingSerializedDataVersion: JavaPrimitiveTypes.int
				-{const} serialVersionUID: JavaPrimitiveTypes.long = -8566272817418441758
				<<Create>> BouncingDrawing()
				add(figure : Figure): Figure
				animationStep()
				remove(figure : Figure): Figure
				replace(figure : Figure, replacement : Figure)
			}
		}
	}
	Builder.nonbuilder.StandardDrawing <|-- Builder.nonbuilder.BouncingDrawing
	Builder.nonbuilder.Animatable <|-- Builder.nonbuilder.BouncingDrawing
	Builder.nonbuilder.CompositeFigure <|-- Builder.nonbuilder.StandardDrawing
	Builder.nonbuilder.Drawing <|-- Builder.nonbuilder.StandardDrawing
	java.lang.Cloneable <|-- Builder.nonbuilder.Figure
	java.io.Serializable <|-- Builder.nonbuilder.Figure
	JavaPrimitiveTypes.int "drawingSerializedDataVersion" <-- Builder.nonbuilder.StandardDrawing
	java.lang.Thread "fDrawingLockHolder" <-- Builder.nonbuilder.StandardDrawing
	java.util.Vector "fListeners" <-- Builder.nonbuilder.StandardDrawing
	JavaPrimitiveTypes.long "serialVersionUID" <-- Builder.nonbuilder.StandardDrawing
	JavaPrimitiveTypes.int "bouncingDrawingSerializedDataVersion" <-- Builder.nonbuilder.BouncingDrawing
	JavaPrimitiveTypes.long "serialVersionUID" <-- Builder.nonbuilder.BouncingDrawing
}
@enduml
