@startuml
package dpd_jdt {
	package Builder {
		package nonbuilder {
			'Pretty printer action button
			'@author    Chris Seguin
			class PrintAction {
				-enabled: JavaPrimitiveTypes.boolean
				-support: java.beans.PropertyChangeSupport
				-values: java.util.HashMap
				'Constructor for the PrintAction object
				<<Create>> PrintAction()
				'The pretty printer action
				'@param evt  the action that occurred
				actionPerformed(evt : java.awt.event.ActionEvent)
				'Adds a feature to the PropertyChangeListener attribute of the PrettyPrinterAction object
				'@param listener  The feature to be added to the PropertyChangeListenerattribute
				addPropertyChangeListener(listener : java.beans.PropertyChangeListener)
				'Gets the ActiveNode attribute of the PrintAction object
				'@return    The ActiveNode value
				-getActiveNode(): Node
				'Gets the initial string from the IDE
				'@return    The file in string format
				#getFilenameFromIDE(): java.lang.String
				'Gets the initial string from the IDE
				'@return    The file in string format
				#getStringFromIDE(): java.lang.String
				'Gets the Value attribute of the PrettyPrinterAction object
				'@param key  Description of Parameter
				'@return      The Value value
				getValue(key : java.lang.String): java.lang.Object
				'Gets the Enabled attribute of the PrettyPrinterAction object
				'@return    The Enabled value
				isEnabled(): JavaPrimitiveTypes.boolean
				'Sets the Value attribute of the PrettyPrinterAction object
				'@param key    The new key value
				'@param value  The new value value
				putValue(key : java.lang.String, value : java.lang.Object)
				'Removes a listener
				'@param listener  the listener to be removed
				removePropertyChangeListener(listener : java.beans.PropertyChangeListener)
				'Sets the Enabled attribute of the PrettyPrinterAction object
				'@param value  The new Enabled value
				setEnabled(value : JavaPrimitiveTypes.boolean)
			}
		}
	}
	javax.swing.Action <|.. Builder.nonbuilder.PrintAction
	Builder.nonbuilder.TextPrinter <|-- Builder.nonbuilder.PrintAction
	JavaPrimitiveTypes.boolean "enabled" <-- Builder.nonbuilder.PrintAction
	java.beans.PropertyChangeSupport "support" <-- Builder.nonbuilder.PrintAction
	java.util.HashMap "values" <-- Builder.nonbuilder.PrintAction
}
@enduml
