@startuml
package dpd_jdt {
	package Builder {
		package nonbuilder {
			'BorderDecorator decorates an arbitrary Figure with a border.
			class BorderDecorator {
				-borderDecoratorSerializedDataVersion: JavaPrimitiveTypes.int
				-{const} serialVersionUID: JavaPrimitiveTypes.long = 1205601808259084917
				<<Create>> BorderDecorator()
				<<Create>> BorderDecorator(figure : Figure)
				-border(): java.awt.Point
				connectionInsets(): java.awt.Insets
				'Gets the displaybox including the border.
				displayBox(): java.awt.Rectangle
				'Draws a the figure and decorates it with a border.
				draw(g : java.awt.Graphics)
				'Invalidates the figure extended by its border.
				figureInvalidated(e : FigureChangeEvent)
			}
		}
	}
	Builder.nonbuilder.DecoratorFigure <|-- Builder.nonbuilder.BorderDecorator
	java.lang.Cloneable <|-- Builder.nonbuilder.Figure
	java.io.Serializable <|-- Builder.nonbuilder.Figure
	JavaPrimitiveTypes.int "borderDecoratorSerializedDataVersion" <-- Builder.nonbuilder.BorderDecorator
	JavaPrimitiveTypes.long "serialVersionUID" <-- Builder.nonbuilder.BorderDecorator
}
@enduml
