@startuml
package dpd_jdt {
	package Builder {
		package nonbuilder {
			'This class defines the current version of JUnit
			class Version {
				-<<Create>> Version()
				{static} id(): java.lang.String
			}
		}
	}
}
@enduml
