@startuml
package dpd_jdt {
	package Builder {
		package nonbuilder {
			'Handles all the diagram zooming for Elixir IDE
			'@author    Chris Seguin
			class ZoomDiagram {
				<<Create>> ZoomDiagram()
				'Scales to 50%
				{static} fiftyPercent()
				'Scales to 100%
				{static} fullSize()
				'Gets the Manager attribute of the ZoomDiagram class
				'@return    The Manager value
				-{static} getManager(): ViewManager
				'Scales the diagram
				'@param manager      the manager
				'@param scaleFactor  the amount to scale
				-{static} scale(manager : UMLViewManager, scaleFactor : JavaPrimitiveTypes.double)
				'Scales to 10%
				{static} tenPercent()
				'Scales to 25%
				{static} twentyfivePercent()
				'actually performs the scaling if it is appropriate
				'@param scaleFactor  The amount to scale the diagram by
				-{static} work(scaleFactor : JavaPrimitiveTypes.double)
			}
		}
	}
	Builder.nonbuilder.ViewManager <|-- Builder.nonbuilder.UMLViewManager
	Builder.nonbuilder.DocManager <|-- Builder.nonbuilder.UMLDocManager
	Builder.nonbuilder.SingleDirClassDiagramReloader "reloader" <-- Builder.nonbuilder.UMLDocManager
	Builder.nonbuilder.UMLDocManager "docManager" <-- Builder.nonbuilder.UMLViewManager
	java.lang.String "filename" <-- Builder.nonbuilder.UMLViewManager
	java.lang.String "packageName" <-- Builder.nonbuilder.UMLViewManager
	Builder.nonbuilder.UMLPackage "packagePanel" <-- Builder.nonbuilder.UMLViewManager
	javax.swing.JScrollPane "pane" <-- Builder.nonbuilder.UMLViewManager
	Builder.nonbuilder.PackageSummary "summary" <-- Builder.nonbuilder.UMLViewManager
}
@enduml
