@startuml
package dpd_jdt {
	package Builder {
		package nonbuilder {
			'Simple adapter that exits the application when the frame is closed
			'@author    Chris Seguin
			class ExitOnCloseAdapter {
				<<Create>> ExitOnCloseAdapter()
				'The window is closing
				'@param evt  Description of Parameter
				windowClosing(evt : java.awt.event.WindowEvent)
			}
		}
	}
	java.awt.event.WindowAdapter <|-- Builder.nonbuilder.ExitOnCloseAdapter
}
@enduml
