@startuml
package dpd_jdt {
	package Builder {
		package nonbuilder {
			'View manager for a particular UML file
			'@author    Chris Seguin
			class UMLViewManager {
				-docManager: UMLDocManager
				-filename: java.lang.String
				-packageName: java.lang.String
				-packagePanel: UMLPackage
				-pane: javax.swing.JScrollPane
				-summary: PackageSummary
				'Constructor for the UMLViewManager object
				'@param parent  the parent document manager
				'@param name    the name of the file to view
				'@param base    Description of Parameter
				<<Create>> UMLViewManager(parent : UMLDocManager, name : java.lang.String, base : java.lang.String)
				'Notify the view manager that it has been closed
				closed()
				'Notify the view manager that it is about to close
				closing()
				'Get the actions currently supported (may vary with state)
				'@return    The Actions value
				getActions(): ActionEx
				'Gets the Diagram attribute of the UMLViewManager object
				'@return    The Diagram value
				getDiagram(): UMLPackage
				'Get the document manager responsible for this view
				'@return    The DocManager value
				getDocManager(): DocManager
				'Get the title of the document being viewed
				'@return    The Title value
				getTitle(): java.lang.String
				'Get the view component which renders/edits the document
				'@return    The View value
				getView(): javax.swing.JComponent
				'Loads the package name from the file
				-loadPackageName()
				'Determine whether it is ok to close the view.
				'@return    Description of the Returned Value
				okToClose(): JavaPrimitiveTypes.boolean
				'Reload the document from its storage (if it has one).
				'@return    Description of the Returned Value
				reload(): JavaPrimitiveTypes.boolean
				'Save the current document.
				'@return    Description of the Returned Value
				save(): JavaPrimitiveTypes.boolean
			}
		}
	}
	Builder.nonbuilder.ViewManager <|-- Builder.nonbuilder.UMLViewManager
	Builder.nonbuilder.DocManager <|-- Builder.nonbuilder.UMLDocManager
	Builder.nonbuilder.SingleDirClassDiagramReloader "reloader" <-- Builder.nonbuilder.UMLDocManager
	Builder.nonbuilder.UMLDocManager "docManager" <-- Builder.nonbuilder.UMLViewManager
	java.lang.String "filename" <-- Builder.nonbuilder.UMLViewManager
	java.lang.String "packageName" <-- Builder.nonbuilder.UMLViewManager
	Builder.nonbuilder.UMLPackage "packagePanel" <-- Builder.nonbuilder.UMLViewManager
	javax.swing.JScrollPane "pane" <-- Builder.nonbuilder.UMLViewManager
	Builder.nonbuilder.PackageSummary "summary" <-- Builder.nonbuilder.UMLViewManager
}
@enduml
