@startuml
package dpd_jdt {
	package Builder {
		package nonbuilder {
			'Pretty printer action button
			'@author    Chris Seguin
			class AboutAction {
				'Constructor for the AboutAction object
				<<Create>> AboutAction()
				'The pretty printer action
				'@param evt  the action that occurred
				actionPerformed(evt : java.awt.event.ActionEvent)
				'Determines if this menu item should be enabled
				'@return    The Enabled value
				isEnabled(): JavaPrimitiveTypes.boolean
			}
		}
	}
	Builder.nonbuilder.JBuilderAction <|-- Builder.nonbuilder.AboutAction
}
@enduml
