@startuml
package dpd_jdt {
	package Builder {
		package nonbuilder {
			class AnimationDecorator {
				-animationDecoratorSerializedDataVersion: JavaPrimitiveTypes.int
				-fXVelocity: JavaPrimitiveTypes.int
				-fYVelocity: JavaPrimitiveTypes.int
				-{const} serialVersionUID: JavaPrimitiveTypes.long = 7894632974364110685
				<<Create>> AnimationDecorator()
				<<Create>> AnimationDecorator(figure : Figure)
				animationStep()
				basicDisplayBox(origin : java.awt.Point, corner : java.awt.Point)
				basicMoveBy(x : JavaPrimitiveTypes.int, y : JavaPrimitiveTypes.int)
				displayBox(): java.awt.Rectangle
				read(dr : StorableInput)
				velocity(xVelocity : JavaPrimitiveTypes.int, yVelocity : JavaPrimitiveTypes.int)
				velocity(): java.awt.Point
				write(dw : StorableOutput)
			}
		}
	}
	Builder.nonbuilder.DecoratorFigure <|-- Builder.nonbuilder.AnimationDecorator
	java.lang.Cloneable <|-- Builder.nonbuilder.Figure
	java.io.Serializable <|-- Builder.nonbuilder.Figure
	JavaPrimitiveTypes.int "animationDecoratorSerializedDataVersion" <-- Builder.nonbuilder.AnimationDecorator
	JavaPrimitiveTypes.int "fXVelocity" <-- Builder.nonbuilder.AnimationDecorator
	JavaPrimitiveTypes.int "fYVelocity" <-- Builder.nonbuilder.AnimationDecorator
	JavaPrimitiveTypes.long "serialVersionUID" <-- Builder.nonbuilder.AnimationDecorator
}
@enduml
