@startuml
package dpd_jdt {
	package Builder {
		package nonbuilder {
			'A LineConnection that constrains a connection to orthogonal lines.
			class ElbowConnection {
				-elbowConnectionSerializedDataVersion: JavaPrimitiveTypes.int
				-{const} serialVersionUID: JavaPrimitiveTypes.long = 2193968743082078559
				<<Create>> ElbowConnection()
				connectedTextLocator(f : Figure): Locator
				'Gets the handles of the figure.
				handles(): java.util.Vector
				layoutConnection()
				updateConnection()
				#updatePoints()
			}
		}
	}
	Builder.nonbuilder.LineConnection <|-- Builder.nonbuilder.ElbowConnection
	Builder.nonbuilder.ConnectionFigure <|.. Builder.nonbuilder.LineConnection
	Builder.nonbuilder.PolyLineFigure <|-- Builder.nonbuilder.LineConnection
	Builder.nonbuilder.AbstractFigure <|-- Builder.nonbuilder.PolyLineFigure
	Builder.nonbuilder.Figure <|-- Builder.nonbuilder.ConnectionFigure
	java.lang.Cloneable <|-- Builder.nonbuilder.Figure
	java.io.Serializable <|-- Builder.nonbuilder.Figure
	JavaPrimitiveTypes.int "ARROW_TIP_BOTH" <-- Builder.nonbuilder.PolyLineFigure
	JavaPrimitiveTypes.int "ARROW_TIP_END" <-- Builder.nonbuilder.PolyLineFigure
	JavaPrimitiveTypes.int "ARROW_TIP_NONE" <-- Builder.nonbuilder.PolyLineFigure
	JavaPrimitiveTypes.int "ARROW_TIP_START" <-- Builder.nonbuilder.PolyLineFigure
	Builder.nonbuilder.LineDecoration "fEndDecoration" <-- Builder.nonbuilder.PolyLineFigure
	java.awt.Color "fFrameColor" <-- Builder.nonbuilder.PolyLineFigure
	java.util.Vector "fPoints" <-- Builder.nonbuilder.PolyLineFigure
	Builder.nonbuilder.LineDecoration "fStartDecoration" <-- Builder.nonbuilder.PolyLineFigure
	JavaPrimitiveTypes.int "polyLineFigureSerializedDataVersion" <-- Builder.nonbuilder.PolyLineFigure
	JavaPrimitiveTypes.long "serialVersionUID" <-- Builder.nonbuilder.PolyLineFigure
	Builder.nonbuilder.Connector "fEnd" <-- Builder.nonbuilder.LineConnection
	Builder.nonbuilder.Connector "fStart" <-- Builder.nonbuilder.LineConnection
	JavaPrimitiveTypes.int "lineConnectionSerializedDataVersion" <-- Builder.nonbuilder.LineConnection
	JavaPrimitiveTypes.long "serialVersionUID" <-- Builder.nonbuilder.LineConnection
	JavaPrimitiveTypes.int "elbowConnectionSerializedDataVersion" <-- Builder.nonbuilder.ElbowConnection
	JavaPrimitiveTypes.long "serialVersionUID" <-- Builder.nonbuilder.ElbowConnection
}
@enduml
