@startuml
package dpd_jdt {
	package Builder {
		package nonbuilder {
			'@class AbstractSelectionModel
			'@date 08-20-2001
			'@author Eric Crahen
			'@version 1.0
			abstract class AbstractSelectionModel {
				-listeners: WeakList
				<<Create>> AbstractSelectionModel()
				'Add a new listener to this model.
				'@param DiagramSelectionListener
				addSelectionListener(l : DiagramSelectionListener)
				'Fire the figure selected event.
				'@param Figure
				#fireFigureAdded(f : Figure)
				'Fire the figure removed event.
				'@param Figure
				#fireFigureRemoved(f : Figure)
				'Remove a listener to this model.
				'@param DiagramSelectionListener
				removeSelectionListener(l : DiagramSelectionListener)
			}
		}
	}
	Builder.nonbuilder.SelectionModel <|.. Builder.nonbuilder.AbstractSelectionModel
	java.lang.Cloneable <|-- Builder.nonbuilder.Figure
	java.io.Serializable <|-- Builder.nonbuilder.Figure
	Builder.nonbuilder.WeakList "listeners" <-- Builder.nonbuilder.AbstractSelectionModel
}
@enduml
