@startuml
package dpd_jdt {
	package Builder {
		package nonbuilder {
			class ActionComboBox {
				-_ACTIONS: java.util.Hashtable
				<<Create>> ActionComboBox()
				<<Create>> ActionComboBox(items : javax.swing.Action)
				addItem(a : javax.swing.Action)
				getItemAt(index : JavaPrimitiveTypes.int): java.lang.Object
				insertItemAt(a : javax.swing.Action, index : JavaPrimitiveTypes.int)
				itemStateChanged(e : java.awt.event.ItemEvent)
				removeAllItems()
				removeItem(anObject : java.lang.Object)
				removeItemAt(anIndex : JavaPrimitiveTypes.int)
			}
		}
	}
	java.awt.event.ItemListener <|.. Builder.nonbuilder.ActionComboBox
	javax.swing.JComboBox <|-- Builder.nonbuilder.ActionComboBox
	java.util.Hashtable "_ACTIONS" <-- Builder.nonbuilder.ActionComboBox
}
@enduml
