@startuml
package dpd_jdt {
	package Builder {
		package nonbuilder {
			'Stores a leaf node for a UML class diagram 
			'@author    Chris Seguin
			class UMLLeaf {
				-docManager: UMLDocManager
				-file: java.io.File
				-packageName: java.lang.String
				-parent: TNode
				'Constructor for the UMLLeaf object 
				'@param parent      the parent file 
				'@param file        the file 
				'@param docManager  the document manager
				<<Create>> UMLLeaf(parent : TNode, file : java.io.File, docManager : UMLDocManager)
				'Gets an enumeration of the children 
				'@return    An empty enumeration
				children(): java.util.Enumeration
				'Perform double-click action. Hopefully this will open the file.
				doDoubleClick()
				'Notify the TreeModel and hence the TreeModel listeners that this node has  changed
				fireChanged()
				'Can we add children to this 
				'@return    The AllowsChildren value
				getAllowsChildren(): JavaPrimitiveTypes.boolean
				'Return the child from an index 
				'@param idx  Description of Parameter 
				'@return      The ChildAt value
				getChildAt(idx : JavaPrimitiveTypes.int): javax.swing.tree.TreeNode
				'Count the children 
				'@return    The ChildCount value
				getChildCount(): JavaPrimitiveTypes.int
				'Get the full name of the node, usually composed by walking the TreePath  a/b/c etc. 
				'@return    The FullName value
				getFullName(): java.lang.String
				'Get the icon to show in the tree 
				'@param expanded  Description of Parameter 
				'@return           The Icon value
				getIcon(expanded : JavaPrimitiveTypes.boolean): javax.swing.Icon
				'Return the index of a child. This has no children so always returns -1. 
				'@param child  Description of Parameter 
				'@return        The Index value
				getIndex(child : javax.swing.tree.TreeNode): JavaPrimitiveTypes.int
				'Get the name to show in the tree 
				'@return    The Name value
				getName(): java.lang.String
				'Gets the Parent attribute of the UMLLeaf object 
				'@return    The Parent value
				getParent(): javax.swing.tree.TreeNode
				'Get the popup menu to show for this node 
				'@return    The PopupMenu value
				getPopupMenu(): javax.swing.JPopupMenu
				'Return the tooltip help to be shown when the mouse is over this node. 
				'@return    The ToolTipText value
				getToolTipText(): java.lang.String
				'Return the model which this node belongs to 
				'@return    The TreeModel value
				getTreeModel(): TModel
				'Get the TreePath which represents this node 
				'@return    The TreePath value
				getTreePath(): javax.swing.tree.TreePath
				'Gets the Leaf attribute of the UMLLeaf object 
				'@return    The Leaf value
				isLeaf(): JavaPrimitiveTypes.boolean
				'Loads the package name from the file
				-loadPackageName()
				'Sets a new name for the node. 
				'@param name  The new Name value
				setName(name : java.lang.String)
				'Sets a new parent for the node. 
				'@param value  The new Parent value
				setParent(value : TParent)
				'Sort the children of this node based on the comparator. Since there are  no children, this does nothing. 
				'@param c  the comparator
				sortChildren(c : SortUtil.Comparator)
				'Return the name of the node as its String representation 
				'@return    Gets the string representation of this node
				toString(): java.lang.String
			}
		}
	}
	Builder.nonbuilder.TNode <|-- Builder.nonbuilder.UMLLeaf
	Builder.nonbuilder.DocManager <|-- Builder.nonbuilder.UMLDocManager
	Builder.nonbuilder.SingleDirClassDiagramReloader "reloader" <-- Builder.nonbuilder.UMLDocManager
	Builder.nonbuilder.UMLDocManager "docManager" <-- Builder.nonbuilder.UMLLeaf
	java.io.File "file" <-- Builder.nonbuilder.UMLLeaf
	java.lang.String "packageName" <-- Builder.nonbuilder.UMLLeaf
	Builder.nonbuilder.TNode "parent" <-- Builder.nonbuilder.UMLLeaf
	java.lang.String "name" <-- Builder.nonbuilder.UMLLeaf.OpenFileAdapter
}
@enduml
