@startuml
package dpd_jdt {
	package Builder {
		package nonbuilder {
			'@class ValueIterator
			'@date 08-20-2001
			'@author Eric Crahen
			'@version 1.0Allows the values for a particular class of Figures to be iterated over, including nulls.
			class ValueIterator {
				-haveNext: JavaPrimitiveTypes.boolean
				-includeNulls: JavaPrimitiveTypes.boolean
				-model: DiagramModel
				-value: java.lang.Object
				'Create an iterator that will pull values for a a certain class of Figures from the  given DiagramModel
				'@param DiagramModel
				'@param Class
				<<Create>> ValueIterator(model : DiagramModel, figureClass : java.lang.Class)
				<<Create>> ValueIterator(model : DiagramModel, figureClass : java.lang.Class, includeNulls : JavaPrimitiveTypes.boolean)
				hasNext(): JavaPrimitiveTypes.boolean
				next(): java.lang.Object
			}
		}
	}
	Builder.nonbuilder.FigureIterator <|-- Builder.nonbuilder.ValueIterator
	java.lang.Cloneable <|-- Builder.nonbuilder.Figure
	java.io.Serializable <|-- Builder.nonbuilder.Figure
	JavaPrimitiveTypes.boolean "haveNext" <-- Builder.nonbuilder.ValueIterator
	JavaPrimitiveTypes.boolean "includeNulls" <-- Builder.nonbuilder.ValueIterator
	Builder.nonbuilder.DiagramModel "model" <-- Builder.nonbuilder.ValueIterator
	java.lang.Object "value" <-- Builder.nonbuilder.ValueIterator
}
@enduml
