@startuml
package dpd_jdt {
	package Builder {
		package nonbuilder {
			'@class AbstractDiagramModel
			'@date 08-20-2001
			'@author Eric Crahen
			'@version 1.0
			abstract class AbstractDiagramModel {
				-listeners: WeakList
				<<Create>> AbstractDiagramModel()
				'Add a new listener to this model.
				'@param DiagramModelListener
				addDiagramDataListener(l : DiagramModelListener)
				'Fire the figure selected event.
				'@param Figure
				#fireFigureAdded(figure : Figure)
				'Fire the figure removed event.
				'@param Figure
				#fireFigureRemoved(figure : Figure)
				'Remove a listener to this model.
				'@param DiagramModelListener
				removeDiagramDataListener(l : DiagramModelListener)
			}
		}
	}
	Builder.nonbuilder.DiagramModel <|.. Builder.nonbuilder.AbstractDiagramModel
	java.lang.Cloneable <|-- Builder.nonbuilder.Figure
	java.io.Serializable <|-- Builder.nonbuilder.Figure
	Builder.nonbuilder.WeakList "listeners" <-- Builder.nonbuilder.AbstractDiagramModel
}
@enduml
